### ISSUE TITLE
False alarm for divide-before-multiply

### ISSUE THREAD

**Issue by undergroundSimplex** [crytic/slither#1002]
For the case of `x = (a * b * c ) / d`, warning `divide-before-multiply` is triggered

**Comment by 0xalpharush** [comment]
I'm not able to reproduce this. What version of slither are you using `slither --version`?
```
"contract C {
    uint x;

    function test(uint a, uint b, uint c, uint d) external {
        x = (a * b * c ) / d;
    }
}" > a.sol && slither a.sol```
