### ISSUE TITLE
Top Level Structure Error

### ISSUE THREAD

**Issue by Timidan** [crytic/slither#1009]
I get the following error message when running slither on the Aavegotchi main repo(master branch) [here](https://github.com/aavegotchi/aavegotchi-contracts)

Error message is: `<class 'slither.solc_parsing.declarations.structure_top_level.StructureTopLevelSolc'> (<slither.solc_parsing.declarations.structure_top_level.StructureTopLevelSolc object at 0x7f988c786020> is not valid for find_variable`

**Comment by 0xalpharush** [comment]
We are aware of this and working to improve support. Tracking the issue here https://github.com/crytic/slither/issues/995

**Comment by Timidan** [comment]
Awesome..... Thanks
