### ISSUE TITLE
Filter external visibility recommendation for public functions to solc < 0.6.9

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1010]
Update this [detector](https://github.com/crytic/slither/blob/master/slither/detectors/functions/external_function.py) to filter based on the compiler version. Also, only output warning if one of the parameters is memory.
Ref: https://ethereum.stackexchange.com/questions/107578/does-using-external-over-public-in-a-library-reduce-any-gas-costs

**Comment by htadashi** [comment]
Working on this issue. Thanks for the clarification @0xalpharush :)

**Comment by 0xalpharush** [comment]
`Prior to version 0.6.9 data location for reference-type arguments was limited to calldata in external functions, memory in public functions`. Based off the docs you linked, it is possible to have a public function with memory params.
 Heuristic: If a public function is not called internally and has memory params, recommend that the user change the function to external visibility and the param data location to calldata.

**Comment by htadashi** [comment]
Ops, I wrote it wrong - sorry for the confusion. I meant to write that it is impossible to have a public function with `calldata` parameters (prior to 0.6.9). Thus public functions prior to 0.6.9 always have memory params and we don't need to check if its parameters are declared as `memory`.

Checking if a memory parameter can be changed to calldata is already detected by this line, isn't it?
https://github.com/crytic/slither/blob/168492ad899e074724b97f99cfa4d4f25934a8e5/slither/detectors/functions/external_function.py#L142-L145

**Comment by duckki** [comment]
Ultimately, it depends on the `pragma solidity` setting of the file. I wouldn't suppress this report unless the lowest compatible Solidity version is 0.6.9 or up (not the version of current compiler being used).
