### ISSUE TITLE
For loop prevents reentrancy detection

### ISSUE THREAD

**Issue by frangio** [crytic/slither#1019]
This was reported before in https://github.com/crytic/slither/issues/940 but wasn't answered, so I wanted to bring attention to it again and give simple reproduction instructions.

In the following code I expect `reentrancy-no-eth` to detect both `r1` and `r2` as errors, but only `r1` is detected.

Is this a known limitation? Is it documented? Are there any plans to fix it? Thanks.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ITarget {
    function exec() public {}
}

contract Reenter {
    uint x;

    function r1(ITarget target) public {
        if (x > 0) {
            target.exec();
            x = 0;
        }
    }

    function r2(ITarget target) public {
        if (x > 0) {
            for (uint i = 0; i < 1; i++) {
                target.exec();
            }
            x = 0;
        }
    }
}
```

**Comment by 0xalpharush** [comment]
I'm not able to replicate this locally. When I run `slither test.sol --detect reentrancy-no-eth`:
```
Reentrancy in Reenter.r1(ITarget) (test.sol#11-16):
	External calls:
	- target.exec() (test.sol#13)
	State variables written after the call(s):
	- x = 0 (test.sol#14)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1
```
Can you run `slither --version` and paste the result of slither when run on the contract above?

**Comment by montyly** [comment]
Hi @frangio, thanks for pointing this out, somehow #940 was missed for the 0.8.2 release. 

We will investigate why it happens

**Comment by Jaime-Iglesias** [comment]
> Hi @frangio, thanks for pointing this out, somehow #940 was missed for the 0.8.2 release.
> 
> We will investigate why it happens

The issue also affects `reentrancy-eth` as the detector code is very similar.

```solidity
    function bad3(ITarget target) public payable {
        if (notCalled = true) {
            for (uint256 i = 0; i < 10; i++) {
                target.exec{ value: msg.value }();
            }
        }
        notCalled = false;
    }
  ```

**Comment by 0xalpharush** [comment]
I found another instance of this. Slither detects that `nftCount` is updated after `_safeMint`, but it would miss it otherwise.
Test case: https://github.com/FrankieIsLost/smart-batched-auction/blob/dccadf0fdee5859f637ee29f46eb832e10a84b05/contracts/BatchAuction.sol#L102-L107
Patched: https://github.com/FrankieIsLost/smart-batched-auction/pull/1
