### ISSUE TITLE
solidity 0.8.11 fails

### ISSUE THREAD

**Issue by mrx23dot** [crytic/slither#1028]
compiler works great in standalone:
solc --version
-  Version: 0.8.11+commit.d7f03943.Linux.g++

solc /home/curr.txt
-   Compiler run successful, no output requested.

but fails via slither:

slither /home/curr.txt --solc-solcs-select 0.8.11
```
  File "/root/.local/share/virtualenvs/smart_contract_scanner-hEAhgL_U/lib/python3.9/site-packages/crytic_compile-0.2.2-py3.9.egg/crytic_compile/platform/solc.py", line 698, in _run_solcs_env
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation, none of the solc versions provided worked
```
source: 
[src.txt](https://github.com/crytic/slither/files/7964095/src.txt)

solc-select==0.2.1
slither==0.8.2
crytic-compile==0.2.2

Other sources work with slither + solc 0.4.x

**Comment by 0xalpharush** [comment]
Can you try running on a file with a '.sol' extension?
```
cat src.txt > src.sol
solc-select use 0.8.11
slither src.sol
```

**Comment by mrx23dot** [comment]
That one solved it! Thanks!
