### ISSUE TITLE
Allow underscore in variable naming convention

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1034]
It's pretty common to include underscores to prefix internal variables or to distinguish between arguments and state variables. We should not include these in the camel case naming convention detector

**Comment by stephenctw** [comment]
They claim to support the underscore [rule](https://github.com/crytic/slither/wiki/Detector-Documentation#rule-exceptions) but I also hit this issue.

**Comment by smallbatch-apps** [comment]
This is affecting us, too. The use of `_name` or `name_` to prevent collision is very common, and necessary. Using `_name` should not trigger an error, as it is a standard convention.

**Comment by 0xalpharush** [comment]
This lines need to be update to include internal state variables:
https://github.com/crytic/slither/blob/0ec487460690482c72cacdea6705e2c51bb3981e/slither/detectors/naming_convention/naming_convention.py#L165

**Comment by devtooligan** [comment]
**bump**
