### ISSUE TITLE
Problem with structs at file level

### ISSUE THREAD

**Issue by fabianorodrigo** [crytic/slither#1035]
Hi guys,

I'm working on a Truffle project and I'm trying to use slither to analyze my contracts.

As you can check in this repository https://github.com/fabianorodrigo/dappsoccerbet, inside structs directory I have a couple of structs at file level.

When I run `slither .`, truffle compile every contract and struct, however I've got an error that my structs doesn't exists. Am I doing something wrong or Slither does not support structs at file level yet?

Thanks in advance.

Bellow the full stdout:

`npx truffle compile --all' running (use --truffle-version truffle@x.x.x to use specific version)

Compiling your contracts...
\===========================
> Compiling ./contracts/BetToken.sol
> Compiling ./contracts/Calculator.sol
> Compiling ./contracts/Game.sol
> Compiling ./contracts/GameFactory.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/libs/StringUtils.sol
> Compiling ./contracts/libs/Utils.sol
> Compiling ./contracts/structs/Bet.sol
> Compiling ./contracts/structs/Score.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol
> Compiling @openzeppelin/contracts/utils/Context.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
> Artifacts written to /home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/build/contracts
> Compiled successfully using:
   - solc: 0.8.11+commit.d7f03943.Emscripten.clang

Traceback (most recent call last):
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 224, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/core/compilation_unit.py", line 231, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: contracts/structs/Score.sol does not exist in ['/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol']
None
Error in .
Traceback (most recent call last):
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 224, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/core/compilation_unit.py", line 231, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: contracts/structs/Score.sol does not exist in ['/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Context.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/Utils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/libs/StringUtils.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/utils/Strings.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/GameFactory.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Game.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Migrations.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/BetToken.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/access/Ownable.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol', '/home/fabianorodrigo/Projetos/solidity/dAppSoccerBet/backendOnChain/contracts/Calculator.sol']
`

**Comment by montyly** [comment]
Hi @fabianorodrigo 

Thank you for reporting this. Unfortunately, this is due to a bug in truffle (see https://github.com/trufflesuite/truffle/issues/3124), and the only solutions are to use another compilation framework, or to wrap the structure in a contract.
