### ISSUE TITLE
Improve dev install for macos

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1051]
### Describe the desired feature

https://github.com/crytic/slither/wiki/Developer-installation

If you have python2, or macos, these steps might not work

**Comment by kkagill** [comment]
had a headache installing slither on macos m1. 
not sure about python2, but I just tried with python3 on macos m1

- Download Python 3.9.x from python.org
- Open your project (truffle/hardhat with contracts folder) with VS code
- On Terminal run `python3 -m venv .venv` to create virtual env
- Then run `source .venv/bin/activate`
- In VS Code, open the Command Palette (View > Command Palette or (⇧⌘P)). Then select the Python: Select Interpreter command:
- Choose the python version i.e. `Python 3.9.x 64-bit ('.venv':venv)` you downloaded
- On Terminal run `python -m pip install --upgrade pip`
- Then run `python -m pip install slither-analyzer`
- Finally run `slither .`

**Comment by 0xalpharush** [comment]
I updated the wiki with the makefile instructions
