### ISSUE TITLE
Incorrect notification on missing config file

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1052]
### Describe the desired feature

https://github.com/crytic/slither/pull/1041 had an incorrect fix I think.

Now we are getting:
```
ERROR:Slither:File slither.config.json is not a file or does not exist
ERROR:Slither:Falling back to the default settings...
```

Even if no config file is provided. I think we should check if the arg was set, and only print a warning if it was the case.

I am not sure if we can determine with the argparser if the value was given by the user, or if its the default value. Maybe we can use `None` as a default value, and its `None`, check for `slither.config.json`'s existence?

**Comment by Jaime-Iglesias** [comment]
Looking at the argparser I think using `None` as the default is probably the best approach.

**Comment by Jaime-Iglesias** [comment]
Fixed by https://github.com/crytic/slither/pull/1054
