### ISSUE TITLE
How to remap multiple imports?

### ISSUE THREAD

**Issue by sjkelleyjr** [crytic/slither#1061]
I'm trying to run slither on some contracts, but need to remap multiple imports, when I try separating them with a semicolon, it doesn't pick up the second remapping.  What is the appropriate syntax for remapping multiple imports using slither?

**Comment by montyly** [comment]
Hi @sjkelleyjr,

Can you give a bit more context? Are you using a compilation framework (truffe/hardhat/...), or are you doing everything through solc directly?

**Comment by sjkelleyjr** [comment]
I was using brownie.  I ended up getting help and [fixing a small bug in crytic-compile](https://github.com/crytic/crytic-compile/pull/240), but I'm still curious as to why this wasn't working, so I left the issue open.

**Comment by PatrickAlphaC** [comment]
I am also running into this error:

```
slither ./contracts/Lending.sol --solc-remaps @openzeppelin/contracts=./node_modules/@openzeppelin/contracts;@chainlink/contracts=./node_modules/@chainlink/contracts --exclude naming-convention
```

and

```
slither ./contracts/Lending.sol --solc-remaps @openzeppelin/contracts=./node_modules/@openzeppelin/contracts,@chainlink/contracts=./node_modules/@chainlink/contracts --exclude naming-convention
```

Both miss the multiple imports

**Comment by elopez** [comment]
Hi @PatrickAlphaC. From looking at the code, `--solc-remaps` expects space-separated remaps (so `--solc-remaps "@foo=./bar @baz=./xyz"`)

Alternatively, you can use the [slither config file](https://github.com/crytic/slither/wiki/Usage#configuration-file) and add a list of remappings there (`solc_remaps: ["...", "..."]`)

**Comment by PatrickAlphaC** [comment]
This was perfect, thank you!!

**Comment by choesy** [comment]
Can this be easily imported from a file settings.json that looks like this (not manually). Note that i want the "remappings" part:

```json
{
	"remappings": [
		"ds-test/=lib/forge-std/lib/ds-test/src/",
		"erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
		"forge-std/=lib/forge-std/src/",
		"openzeppelin-contracts/=lib/openzeppelin-contracts/",
		"lib/forge-std:ds-test/=lib/forge-std/lib/ds-test/src/",
		"lib/openzeppelin-contracts:ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
		"lib/openzeppelin-contracts:erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
		"lib/openzeppelin-contracts:forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
		"lib/openzeppelin-contracts:openzeppelin/=lib/openzeppelin-contracts/contracts/"
	],
	"optimizer": {
		"enabled": true,
		"runs": 200
	},
	"metadata": {
		"useLiteralContent": false,
		"bytecodeHash": "ipfs"
	},
	"outputSelection": {
		"*": {
			"*": [
				"evm.bytecode",
				"evm.deployedBytecode",
				"devdoc",
				"userdoc",
				"metadata",
				"abi"
			]
		}
	},
	"evmVersion": "london",
	"libraries": {}
}
```

**Comment by elopez** [comment]
@choesy you can likely use a bit of shell scripting to do that, e.g.

```shell
 slither --solc-remaps "$(jq -cr '.remappings | join(" ")' < settings.json)" foocontract.sol
```

I'm unsure if solc supports that "scoped imports" syntax though, you may have more luck using Foundry/Hardhat instead of manually building contracts for that complex a setup.
