### ISSUE TITLE
[Bug]: --ignore-compile does not work

### ISSUE THREAD

**Issue by rsodre** [crytic/slither#1070]
### What happened?

The `--ignore-compile` or `--truffle-ignore-compile` options have no effect, slither always try to run `solc`.

And I can't get `solc` to compile the sources. Note that the built truffle json files are not in the default `build/contracts`, but is correctly pointed. Even if I move them to `build/contracts`, slither still tries to cimpile.

### Can you share code with us to reproduce this bug?

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.2;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

import "./EuclidRandomizer.sol";
import "./Whitelist.sol";

contract Euclid is ERC721, ERC721Enumerable, Ownable {
// contract contents not relevalt
}

### Version

slither 0.8.2
truffle 5.4.32
macOS 11.6.2
@openzeppelin/contracts 4.4.2

### Relevant log output

```shell
slither ./contracts/Euclid.sol --ignore-compile --truffle-ignore-compile --truffle-build-directory ../cc-dapp/src/contracts/euclid --solc-args "--base-path . --include-path ../node_modules"

Compilation warnings/errors on ./contracts/Euclid.sol:
Base path does not exist: "/projects/Truffle/cc-euclid/. "

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 529, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/slither/__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 283, in _get_targets_json
    force_legacy_json=force_legacy_json,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 533, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Base path does not exist: "/projects/Truffle/cc-euclid/. "
```

**Comment by elopez** [comment]
Hi @rsodre, thanks for the report. If you want to use the Truffle integration, you need to pass a Truffle project folder as an argument, not a standalone `.sol` file. The project folder is the one that contains `truffle.js` or `truffle-config.js`.

If you use a standalone `.sol` file as the Slither argument, Slither will trigger the [direct solc integration](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/solc.py#L184-L195) (i.e. it runs solc directly against that file), which does not support `ignore-compile`.

**Comment by rsodre** [comment]
Ok, got it.

Then why the `Base path does not exist` error? It does exist, I checked (it's just `.`)

**Comment by elopez** [comment]
I'm not sure what error you are referring to. Can you post an updated output with what you get when you run Slither with the project path? For your case it would be something like

 `slither . --truffle-build-directory foo/bar`
 
 Where `.` is the project directory (assuming you are standing there in your shell) and `foo/bar` is your custom build directory (usually `build/contracts` by default)

**Comment by rsodre** [comment]
I'm not running slither on the whole project because there are some contracts with external dependencies and test contracts that do not need to be tested.

If I just run slither on the whole project, it will not find those dependencies...

```
ValueError: /path/RandomizerTest.sol does not exist in [ALL THE CONTRACTS HERE]
```

If I delete these contracts, it gets confused because there are artifacts for the missing contracts...

```
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/RandomizerTest.sol
```

If I delete all the artifacts slither runs ok! If that's what I have to do, then ok. But I wish I could have a workflow where I do not need to delete all those files to analyze my contracts.

Running slither on a single contract, it will try to compile and not find the openZeppelin modules...

```
Error: Source "@openzeppelin/contracts/token/ERC721/ERC721.sol" not found: File not found. Searched the following locations: "".
 --> contracts/Euclid.sol:4:1:
  |
4 | import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If I add the `--include-path ./node_modules`, I also need to add `--base-path`. But I think I got the problem, the solc args was missing `=`. This works now...

```
slither ./contracts/Euclid.sol --truffle-build-directory ../cc-dapp/src/contracts/euclid --solc-args "--include-path=./node_modules --base-path=./contracts"
```

**Comment by rsodre** [comment]
Closing the issue, but would be nice to run the **truffle project** on a **single contract**, **ignoring compile**. I spent a few hours just getting solc to run.

**Comment by montyly** [comment]
Hi @rsodre, 

You can use [`--filter-paths`](https://github.com/crytic/slither/wiki/Usage#path-filtering) to exclude results from certain contracts/dependencies. If you are using standard libraries, you can also use `--exclude-dependencies` to directly exclude the dependencies.

Regarding running truffle on a single contract, I believe that would need to be implemented within truffle (and I am not aware of an existing truffle feature allowing that).

Regarding the `ValueError`, did you install all the dependencies (`yarn install` or `npm install`)? Could you share your truffle config file? For example, if you change the `contracts_directory` option, it might create issues.

Additionally, could you share the codebase where this happens?
