### ISSUE TITLE
[Bug]: Function Id returns incorrect values for functions with tuples in inputs (incorrect signature generation)

### ISSUE THREAD

**Issue by ericnordelo** [crytic/slither#1077]
### What happened?

The signature of a function with tuples is being generated with the name of the tuple, instead of the correct decoupled version (see code example).

### Can you share code with us to reproduce this bug?

```
contract A {
    struct Person {
        uint8 age;
        uint8 children;
    }

    function setPerson(Person memory _p) external {
        /* do something */
    }
}
```

// **You are returning signature as "setPerson(Person)" when the correct signature is "setPerson((uint8,uint8))"**

### Version

0.8.2

**Comment by montyly** [comment]
Hi @ericnordelo.

Thank you for reporting this. We started a refactor of the function signature a while ago, that we never finished (https://github.com/crytic/slither/pull/483), we should do another pass at it

**Comment by ericnordelo** [comment]
That would be great, I use the function-id printer a lot, and is in complex struct arguments where it is more useful.
Thank you.

**Comment by ericnordelo** [comment]
Are you guys planning to fix this any time soon? That would be appreciated. We use this feature a lot when debugging transactions. 

Thank you in advance.
