### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by 161424** [crytic/slither#1079]
### What happened?

A bug happened!

### Can you share code with us to reproduce this bug?

contract A {pragma solidity ^0.5.1;
contract BREBuy {
    
    struct ContractParam {
        uint32  totalSize ; 
        uint256 singlePrice;
        uint8  pumpRate;
        bool hasChange;
    }
    
    address owner = 0x0;
    uint32  gameIndex = 0;
    uint256 totalPrice= 0;
    bool isLock = false;
    ContractParam public setConfig;
    ContractParam public curConfig;
    
    address[] public addressArray = new address[](0);
                    
    event openLockEvent();
    event addPlayerEvent(uint32 gameIndex,address player);
    event gameOverEvent(uint32 gameIndex,uint32 totalSize,uint256 singlePrice,uint8 pumpRate,address winAddr,uint overTime);
    event stopGameEvent(uint totalBalace,uint totalSize,uint price);
          
    /* Initializes contract with initial supply tokens to the creator of the contract */
    constructor ( uint32 _totalSize,
                  uint256 _singlePrice
    )  public  {
        owner = msg.sender;
        setConfig = ContractParam(_totalSize,_singlePrice * 1 finney ,5,false);
        curConfig = ContractParam(_totalSize,_singlePrice * 1 finney ,5,false);
        startNewGame();
    }

    modifier onlyOwner {
        require(msg.sender == owner,"only owner can call this function");
        _;
    }
    
     modifier notLock {
        require(isLock == false,"contract current is lock status");
        _;
    }
    
    function isNotContract(address addr) private view returns (bool) {
        uint size;
        assembly { size := extcodesize(addr) }
        return size <= 0;
    }

    function updateLock(bool b) onlyOwner public {
        
        require(isLock != b," updateLock new status == old status");
       
        isLock = b;
       
        if(isLock) {
            stopGame();
        }else{
            startNewGame();
            emit openLockEvent();
        }
    }
    
    function stopGame() onlyOwner private {
      
      if(addressArray.length <= 0) {
          return;
      }  
      uint totalBalace = address(this).balance;
      uint price = totalBalace / addressArray.length;
      for(uint i = 0; i < addressArray.length; i++) {
          address curPlayer =  addressArray[i];
          curPlayer.transfer(price);
      }
      emit stopGameEvent(totalBalace,addressArray.length,price);
      addressArray.length=0;
    }

    function transferOwnership(address newOwner) onlyOwner public {
        if (newOwner != address(0)) {
            owner = newOwner;
        }
    }
    
    function changeConfig( uint32 _totalSize,uint256 _singlePrice,uint8 _pumpRate) onlyOwner public payable {
    
        curConfig.hasChange = true;
        if(setConfig.totalSize != _totalSize) {
            setConfig.totalSize = _totalSize;
        }
        if(setConfig.pumpRate  != _pumpRate){
            setConfig.pumpRate  = _pumpRate;
        }
        if(setConfig.singlePrice != _singlePrice * 1 finney){
            setConfig.singlePrice = _singlePrice * 1 finney;
        }
    }
    
    function startNewGame() private {
        
        gameIndex++;
        if(curConfig.hasChange) {
            if(curConfig.totalSize   != setConfig.totalSize) {
                curConfig.totalSize   = setConfig.totalSize;
            }
            if(curConfig.singlePrice != setConfig.singlePrice){
               curConfig.singlePrice = setConfig.singlePrice; 
            }
            if( curConfig.pumpRate    != setConfig.pumpRate) {
                curConfig.pumpRate    = setConfig.pumpRate;
            }
            curConfig.hasChange = false;
        }
        addressArray.length=0;
    }
    
    function getGameInfo() public view returns  (uint256,uint32,uint256,uint8,address[],uint256,bool)  {
        return (gameIndex,
                curConfig.totalSize,
                curConfig.singlePrice,
                curConfig.pumpRate,
                addressArray,
                totalPrice,
                isLock);
    }
    
    function gameResult() private {
            
      uint index  = getRamdon();
      address lastAddress = addressArray[index];
      uint totalBalace = address(this).balance;
      uint giveToOwn   = totalBalace * curConfig.pumpRate / 100;
      uint giveToActor = totalBalace - giveToOwn;
      owner.transfer(giveToOwn);
      lastAddress.transfer(giveToActor);
      emit gameOverEvent(
                    gameIndex,
                    curConfig.totalSize,
                    curConfig.singlePrice,
                    curConfig.pumpRate,
                    lastAddress,
                    now);
    }
    
    function getRamdon() private view returns (uint) {
      bytes32 ramdon = keccak256(abi.encodePacked(ramdon,now,blockhash(block.number-1)));
      for(uint i = 0; i < addressArray.length; i++) {
            ramdon = keccak256(abi.encodePacked(ramdon,now, addressArray[i]));
      }
      uint index  = uint(ramdon) % addressArray.length;
      return index;
    }
    
    function() notLock payable public{
        
        require(msg.sender == tx.origin, "msg.sender must equipt tx.origin");
        require(isNotContract(msg.sender),"msg.sender not is Contract");
        require(msg.value == curConfig.singlePrice,"msg.value error");
        totalPrice = totalPrice + msg.value;
        addressArray.push(msg.sender);
       
        emit addPlayerEvent(gameIndex,msg.sender);
        if(addressArray.length >= curConfig.totalSize) {
            gameResult();
            startNewGame();
        }
    }
}}

### Version

un `slither --version`   0.8.2

### Relevant log output

```shell
slither D:\PycharmProjects\soliditysrc\contract_dataset_ethereum\contract1\0.sol
Compilation warnings/errors on D:\PycharmProjects\soliditysrc\contract_dataset_ethereum\contract1\0.sol:
D:/PycharmProjects/soliditysrc/contract_dataset_ethereum/contract1/0.sol:118:79: Error: Data location must be "memory" for return parameter in function, but none was given.
    function getGameInfo() public view returns  (uint256,uint32,uint256,uint8,address[],uint256,bool)  {
                                                                              ^-------^

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 530, in _run_solc
    ret: Dict = json.loads(stdout)
  File "d:\ProgramData\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "d:\ProgramData\Anaconda3\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 534, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation D:/PycharmProjects/soliditysrc/contract_dataset_ethereum/contract1/0.sol:118:79: Error: Data location must be "memory" for return parameter in function, but none was given.
    function getGameInfo() public view returns  (uint256,uint32,uint256,uint8,address[],uint256,bool)  {
                                                                              ^-------^

None
Error in D:\PycharmProjects\soliditysrc\contract_dataset_ethereum\contract1\0.sol
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 530, in _run_solc
    ret: Dict = json.loads(stdout)
  File "d:\ProgramData\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "d:\ProgramData\Anaconda3\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "d:\ProgramData\Anaconda3\lib\site-packages\crytic_compile\platform\solc.py", line 534, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation D:/PycharmProjects/soliditysrc/contract_dataset_ethereum/contract1/0.sol:118:79: Error: Data location must be "memory" for return parameter in function, but none was given.
    function getGameInfo() public view returns  (uint256,uint32,uint256,uint8,address[],uint256,bool)  {
                                                                              ^-------^
```

**Comment by Jaime-Iglesias** [comment]
Hey @161424 

Look like the compilation error is in 
```solidity
function getGameInfo() public view returns  (uint256, uint32, uint256, uint8, address[], uint256,bool)
```
since you are using an array `address[]` you need to define its data location (i.e storage, memory, calldata) declaring it as:

```solidity
function getGameInfo() public view returns  (uint256, uint32, uint256, uint8, address[] memory, uint256, bool)
```

should do the trick.

Notice that this is not a bug in slither, its simply that your solidity code is not "correct" and thus does not compile.

For more information you can see the docs for your specific solidity version:
https://docs.soliditylang.org/en/v0.5.1/types.html#data-location

**Comment by 161424** [comment]
So when I don't have enough knowledge to identify the solidness vulnerability, how can I tell whether the slither compiler doesn't work because of the code vulnerability or the error is reported because of the vulnerability of the slither code itself?

**Comment by elopez** [comment]
Hi @161424, you can see Slither reported this as a compilation problem in the first output lines you copied here:

```
Compilation warnings/errors on D:\PycharmProjects\soliditysrc\contract_dataset_ethereum\contract1\0.sol:
D:/PycharmProjects/soliditysrc/contract_dataset_ethereum/contract1/0.sol:118:79: Error: Data location must be "memory" for return parameter in function, but none was given.
    function getGameInfo() public view returns  (uint256,uint32,uint256,uint8,address[],uint256,bool)  {
                                                                              ^-------^
```

If you are unsure, you should always try to compile the code first and make sure it's valid, working Solidity, before running Slither.
