### ISSUE TITLE
Fix CI's pylint speed

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1084]
It looks like pylint is taking 20-30 min to run through the github super linter. We have to investigate why it happens, and how we can speed this up

**Comment by elopez** [comment]
It looks like super linter collects a list of files and then goes through them to split the list into the different kinds of linters. This is done in a shell script. Then it runs them one by one through the linting programs.

The repository has close to ~13k files, of which 12.5k are `tests/*`, ~11.7k `tests/ast-parsing/*`, ~12.4k are sol/json/zip in `tests/*`

I feel it would be overall faster to just pip install black & pylint and run those directly in the workflow on the full project, and keep the super linter for the non-python bits.
