### ISSUE TITLE
Option to fail on presence of defects

### ISSUE THREAD

**Issue by jmcph4** [crytic/slither#1091]
### Describe the desired feature

Slither should support the return of nonzero error codes in the presence of defects. This functionality should be configurable based on severity as well. Specifically, there should be six new options:

 - `fail-on-defects`,
 - `fail-on-high`
 - `fail-on-medium`
 - `fail-on-low`
 - `fail-on-informational`
 - `fail-on-optimisation`

These options should be able to be specified via both the CLI and the configuration file format. These options would cause `slither` to return with a nonzero error code if any of the relevant defects are detected. For example,

```
# assuming there are defects, of course!
$ slither --fail-on-defects
# ...
$ echo $?
1
```

The rationale for this is mainly CI/CD integration. Slither already has [a GitHub Action workflow](https://github.com/marketplace/actions/slither-action) but it's doesn't allow automatic failure on these events (at least not from what I can tell at the moment).

**Comment by montyly** [comment]
Hi @jmcph4

Thanks for the idea, I agree with you. The current return value from Slither is non-standard and has legacy reasons - we can remove this now. We can have slither returns 0 by default (unless it crashes), and add these flags.
