### ISSUE TITLE
slither not installing on mac

### ISSUE THREAD

**Issue by davidpius95** [crytic/slither#1093]
<img width="504" alt="Screenshot 2022-03-08 at 9 53 52 AM" src="https://user-images.githubusercontent.com/47521458/157202138-00dd7233-d001-45da-a9fc-f1f4075bdae3.png">

**Comment by y1cunhui** [comment]
maybe you should run the install command first? using python or pip

**Comment by 0xalpharush** [comment]
@davidpius95 Can you provide more information? How did you install slither? Where was this error thrown? Note, this is an issue with your installation and not slither itself.

**Comment by davidpius95** [comment]
@0xalpharush i installed the extension having same error, then i install slither from my terminal using pip and also install slither by cloning the repo , i still get same error when i run slither .

**Comment by 0xalpharush** [comment]
Can you tell me the output of `which python3` and `which slither`?

**Comment by davidpius95** [comment]
<img width="1440" alt="Screenshot 2022-03-09 at 5 05 42 @0xalpharush M" src="https://user-images.githubusercontent.com/47521458/157481019-af71539b-4599-46e3-abdd-6aa67842589b.png">

**Comment by 0xalpharush** [comment]
> Can you tell me the output of which python3 and which slither?

I meant to run these in the terminal and show the output

**Comment by davidpius95** [comment]
<img width="827" alt="Screenshot 2022-03-09 at 5 16 04 PM" src="https://user-images.githubusercontent.com/47521458/157483405-637db95c-e622-4b87-94a3-518d92e4faef.png">
@0xalpharush

**Comment by 0xalpharush** [comment]
Please join our slack channel to receive further help https://empireslacking.herokuapp.com/
