### ISSUE TITLE
[Bug-Candidate]: Phi-node print missing 'f' in f-string

### ISSUE THREAD

**Issue by hbrodin** [crytic/slither#1109]
### Describe the issue:

When printing a Phi-node the string is not formatted.
There seems to be a 'f' missing ahead of the str in https://github.com/crytic/slither/blob/dev/slither/slithir/operations/phi.py#L36

### Code example to reproduce the issue:

slither tests/complex_func.sol --print slithir-ssa

### Version:

dev-branch dd91f770f61eaadc286e2af3c72fb5798e376c16

### Relevant log output:

```
Contract Increment
        Function Increment.increaseBy1()
                IRs:
                        {self.lvalue}({self.lvalue.type}) := ϕ({[str(v) for v in self._rvalues]})
                Expression: i += 1
```

**Comment by Boyan-MILANOV** [comment]
Closed by #1110
