### ISSUE TITLE
unprotected-upgrade: remove FPs

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1113]
I saw a couple of FPs on this detector due to:

- A constructor with the initializer modifier (which discards the possibility to call the init function on the implementation)
- The OZ fixes: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol#L29 / https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol#L38-L42. We can probably whitelist `onlyProxy`

**Comment by 0xalpharush** [comment]
I think the first bullet was fixed by https://github.com/crytic/slither/pull/1046. 

By whitelisting `onlyProxy` do you mean allowing initializer functions that have it as a modifier?

**Comment by montyly** [comment]
Fixed with 1122
