### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by RatanRSur** [crytic/slither#1121]
### Describe the issue:

When using `--solc-remaps`, it tries to read the remapping file as a solidity file.

`slither src/contracts/controller/Controller.sol --solc-remaps remappings.txt`
gives
```
Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
 --> remappings.txt:1:1:
  |
1 | @openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
  | ^
```
`remappings.txt`:
```
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
```

### Code example to reproduce the issue:

N/A

### Version:

0.8.2

**Comment by 0xalpharush** [comment]
The command line argument is expected to be a file path, not a file. 
Example: 
```
slither . --solc-remaps @openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/

```

**Comment by RatanRSur** [comment]
thank you! The reason this confused me is because it showed the contents of the file in the output:
```
Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
 --> remappings.txt:1:1:
  |
1 | @openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
  | ^
```

**Comment by tom2o17** [comment]
Is there anyway to handle multiple remaps in the `--solc-remaps` flag?

**Comment by elopez** [comment]
@tom2o17 see #1061, you need to separate them with spaces.

**Comment by tom2o17** [comment]
That did not seem to work. I was able to find a workaround using this pattern 

`slither --solc-remaps @=node_modules/@`

**Comment by MikyChow** [comment]
> Amazing thanks for the reference.
> 
> I was able to find a workaround using this pattern, seems to accomplish the same end.
> 
> Thought I'd share maybe some will find it helpful
> 
> `slither --solc-remaps @=node_modules/@`

this works for me ,Thanks

**Comment by Elyx0** [comment]
Digging back on this, any intention to support remapping from file as it can get quite long with 5+ remappings?

**Comment by Steiner-254** [comment]
So how are you guys dealing with the error that arises when running slither (for static analysis) on a contract that inherits from another contract???
