### ISSUE TITLE
Infinite loop in enums analyzer

### ISSUE THREAD

**Issue by kndt** [crytic/slither#1129]
### Describe the issue:

I am using slither for hardat and each time I run it gets stuck.

I then added print() statements within the code in file: `slither/solc_parsing/slither_compilation_unit_solc.py` the method `_analyze_all_enums` in line 450 has a while loop which seems to loop continuously over all the contracts until a KeyboardInterrupt 

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

contract DummyToken is Initializable, ERC20Upgradeable {
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize() public initializer {
        __ERC20_init("MyToken", "MTK");

        _mint(msg.sender, 100000 * 10**decimals());
    }
}

```

### Version:

0.8.2

### Relevant log output:

I inserted print statements within the code and figured out it was looping continuously.

![image](https://user-images.githubusercontent.com/21057231/158912362-d8da2eab-8718-4016-a46a-0a604cc79f9c.png)

**Comment by 0xalpharush** [comment]
Does your project use OpenZepplin's upgrade package? This caused an issue for another user https://github.com/crytic/slither/issues/1095. There's a fix here for that package https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/541

**Comment by kndt** [comment]
@0xalpharush Yes it does as seen in the code example above:

```solidity
import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
```

**Comment by kndt** [comment]
@0xalpharush I see the fix was merged 2 days ago Thank you :pray:
