### ISSUE TITLE
[Bug-Candidate]: Slither freezing after changed contracts to Openzeppelin Upgradeable

### ISSUE THREAD

**Issue by fabianorodrigo** [crytic/slither#1143]
### Describe the issue:

Hi!

I have this project with some simple contracts. I'm making use of Openzeppelin contracts, inheriting from Owanble and ERC20.
Until there, I was running slither and it was working pretty nice, reporting the problems with my project perfectly.

Then I decided to make part of those contracts upgradeable and change the inheritance of Openzeppelin contracts from ERC20 to ERC20Upgradeable and from Ownable to OwanbleUpgradeable. I also add another inheritance  of Initializable.

Since then, when I run slither it just freezes. I doesn't report anymore and either show me some message error.

### Code example to reproduce the issue:

The project repository is this: https://github.com/fabianorodrigo/dAppSoccerbet/, sudirectory backend-hardhat.

I've made a branch with the last commit that slither works fine called "lastSlitherWorking":  https://github.com/fabianorodrigo/dAppSoccerbet/tree/lastSlitherWorking

The next commit, with the changes to Upgradeable pattern, it stopped working. I've made a branch also "firstSlitherNotWorking":  https://github.com/fabianorodrigo/dAppSoccerbet/tree/firstSlitherNotWorking

One of the contracts change is the following:

// contracts/ETC20BetToken.sol
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/security/ReentrancyGuardUpgradeable.sol";

contract BetTokenUpgradeable is
    Initializable,
    ERC20Upgradeable,
    OwnableUpgradeable,
    UUPSUpgradeable,
    ReentrancyGuardUpgradeable
{
    event TokenMinted(
        address indexed tokenBuyer,
        uint256 quantity,
        uint256 contractBalance
    );

    function initialize() external initializer {
        __ERC20_init("Soccer Bet Token", "SBT");
        __Ownable_init();
        __ReentrancyGuard_init();
    }

    receive() external payable {
        _mint(msg.sender, msg.value);
        emit TokenMinted(msg.sender, msg.value, address(this).balance);
    }

    function exchange4Ether(uint256 _amount) external nonReentrant {
        _burn(msg.sender, _amount);
        (bool sent, ) = msg.sender.call{value: _amount}("");
        require(sent, "Fail");
    }

    function destroyContract() external onlyOwner {
        (bool sent, ) = owner().call{value: address(this).balance}("");
        require(sent, "Fail");
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        override
        onlyOwner
    {}
}

### Version:

0.8.2

### Relevant log output:

backend-hardhat > slither .
'npx hardhat compile --force' running
Compiled 29 Solidity files successfully

// and stops here forever until I press CTRL + C, then it outputs:

^CTraceback (most recent call last):
  File "/home/fabianorodrigo/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 631, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 412, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/fabianorodrigo/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 458, in _analyze_all_enums
    if not contract.underlying_contract.inheritance or all_father_analyzed:
KeyboardInterrupt

**Comment by 0xalpharush** [comment]
There is a bug in this package that you are importing: https://github.com/fabianorodrigo/dAppSoccerbet/blob/ecd666edde4da0c7ca764a58e29a0647d1d25147/backend-hardhat/hardhat.config.ts#L4
If you comment it out, slither works. Please see https://github.com/crytic/slither/issues/1095 for more info

**Comment by fabianorodrigo** [comment]
Problem, solved! Thank you!
