### ISSUE TITLE
[Bug-Candidate]: Error UserDefinedValueTypeDefinition when using custom type

### ISSUE THREAD

**Issue by dannyposiex** [crytic/slither#1152]
### Describe the issue:

I got an error UserDefinedValueTypeDefinition when using custom type `type Manager is address;`
My compiler version 0.8.8, please help to check.

### Code example to reproduce the issue:

```
contract ContractHasError {
   type Manager is address;
}
```

### Version:

0.8.2

### Relevant log output:

```
File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 257, in _parse_contract_items
    raise ParsingError("Unknown contract item: " + item[self.get_key()])
slither.solc_parsing.exceptions.ParsingError: Unknown contract item: UserDefinedValueTypeDefinition
Error: Unknown contract item: UserDefinedValueTypeDefinition
```

**Comment by dannyposiex** [comment]
Error reported here: https://empirehacking.slack.com/archives/C0BEQPJGJ/p1648617698640999

**Comment by montyly** [comment]
Hi @dannyposiex, thank you for reporting this.
We added the support for user-defined type with [Slither 0.8.3](https://github.com/crytic/slither/releases/tag/0.8.3). Running `pip install --upgrade slither-analyzer` will fix this issue
