### ISSUE TITLE
Can we use Slither to find contract constructors that are not called from another contract?

### ISSUE THREAD

**Issue by CodeGodz** [crytic/slither#1159]
Lets take this contract:
``` solidity
contract B {

    uint public cool;

    constructor(uint wow) {
        cool = wow;
    }
}


contract A {

    B public niceContract;
    uint public coolVar;

    constructor(uint x) {
        coolVar = x;
        niceContract = new B(1); // <- inits B
    }
}
```
Here the constructor of `B` gets called by `A` but the constructor of `A` doesn't get called. I want to know that `A` doesn't get initialized "automatically" such that I can do that myself before passing it to Echidna. 

I took a look at `all_functions_called` and compared this to all `is_constructor` functions, while this works for the inherited ones it does not for those called via `new`. I also saw these are excluded from `explicit_base_constructor_calls`. Is this info somewhere in the Slither object?

**Comment by montyly** [comment]
Hi @CodeGodz,

Just to be sure that I understand what you are describing: you want to detect all the contracts for which there is no `new <name>(..)` in the codebase?

If so, we can iterate over all the IRs, go over the`NewContract` opcode, and look for contracts that are never created. @0xalpharush, or @smonicas: can you help him to build such a script?

**Comment by CodeGodz** [comment]
@montyly, that indeed was what I meant. I didn't realize there was an `NewContract` operations, so the following indeed works:

```python
code = '''contract B {

    uint public cool;

    constructor(uint wow) {
        cool = wow;
    }
}


contract A {

    B public niceContract;
    uint public coolVar;

    constructor(uint x) {
        coolVar = x;
        niceContract = new B(1); // <- inits B
    }
}'''

from slither.slither import Slither
from slither.slithir.operations import NewContract

# Write output file for slither
with open('1159.sol','w') as out:
    out.write(code)

def not_init_by_new(slither):
    all_contracts = {contract.name for contract in slither.contracts}
    created_by_new = set()
    for contract in slither.contracts:
        for func in contract.functions:
            for node in func.nodes:
                for ir in node.irs:
                    if isinstance(ir, NewContract):
                        created_by_new.add(str(ir.contract_created))

    print('Not created by "new()": {}'.format(', '.join(all_contracts - created_by_new)))


slither = Slither('1159.sol')
not_init_by_new(slither)

```
Will print:
`Not created by new(): A`

I think we can close this, thanks for the tip :)
