### ISSUE TITLE
[Bug-Candidate]: Unable to re-install slither

### ISSUE THREAD

**Issue by viraj124** [crytic/slither#1160]
### Describe the issue:

Hi,

I have been using slither for sometime and the experience was great, but then I recently noticed that my slither version did not support custom errors so I kept getting "ErrorDefinition" error, and I installed slither on my mac via the git method since that is the only method that worked so I deleted the git repo and cloned again but on installation, I get this 
```
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/root/Library/Caches/com.apple.python/private', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

Is there a workaround for this?

### Code example to reproduce the issue:

Having installation issues 

### Version:

Having installation issues

**Comment by CodeGodz** [comment]
Did you try updating setuptools (`pip install --upgrade setuptools`)?

**Comment by viraj124** [comment]
I did run   `(pip install --upgrade setuptools)? but it didn't work`

**Comment by viraj124** [comment]
Hey guys, can anyone have a look I tried docker installation, was able to share a directory in container but on running `slither . `got this
`pkg_resources.DistributionNotFound: The 'crytic-compile>=0.2.2' distribution was not found and is required by slither-analyzer`

**Comment by elopez** [comment]
You should be able to install from Git with `pip install --user .` using the built-in python on Mac. If you have Homebrew python, `pip install .` works too.

A new Slither version was just released, so you can try installing from the package registry again as well 👍

**Comment by kylebakerio** [comment]
you should also be able to do `pip3 uninstall slither-analyzer` followed by `pip3 install slither-analyzer`

**Comment by 0xalpharush** [comment]
If you have a questions, please head over to our discussions page https://github.com/crytic/slither/discussions
