### ISSUE TITLE
Problems with using slither on Truffle

### ISSUE THREAD

**Issue by JoeyJoey657** [crytic/slither#1161]
![image](https://user-images.githubusercontent.com/83679909/162579203-8edc1ddc-2237-48db-9036-4fdb46a4f153.jpeg)

![image](https://user-images.githubusercontent.com/83679909/162579208-24f33033-5a31-4389-87a2-8f8d8601c2d2.jpeg)

I installed slither, but when I want to run it upon Truffle (or Hardhat) it gives me a message that 'slither' can't be recognized, any advice?^^

**Comment by elopez** [comment]
Hi! Thanks for the report. Could you tell us a bit more about what your environment is like? (Windows version, Python version, how did you install Python, etc).

Going by the error message alone, it looks like there is probably an issue with the PATH configuration on your environment, could you confirm if other Python tools work correctly? (e.g. if you `pip install black`, does `black --help` work or does it throw a similar error?)

As a workaround, you can try running `python3 -m slither .` instead for the time being.

**Comment by JoeyJoey657** [comment]
The Pip3 Black also gives me a similar error when I execute the Black--help, so I assume there's something wrong with my Python installation right?

**Comment by JoeyJoey657** [comment]
Python --version: 3.9.12 
OS: Windows 10 home

**Comment by elopez** [comment]
👍 I'll go ahead and close this issue then
