### ISSUE TITLE
Wiki edit access

### ISSUE THREAD

**Issue by CarstenNZ** [crytic/slither#1189]
### Issue
The wiki contains minor errors like broken links or incorrect comments in examples. 

### Proposed change
Provide edit access to the wiki

**Comment by dguido** [comment]
Send me an email! dan@trailofbits.com

**Comment by montyly** [comment]
Thanks @CarstenNZ for the fixes. I updated the wiki here:
- https://github.com/crytic/slither/wiki/Usage/_compare/f9e19c7f4fd9eace8d21cd9115088c442875d248...7a36512c1c95f0956c33283335aa06a5cae3e7ab
- https://github.com/crytic/slither/wiki/Adding-a-new-utility/_compare/7ae8d504cb7acf217085ef91e1a9b96cd40f7344...7a36512c1c95f0956c33283335aa06a5cae3e7ab

I haven't update the changes in the detectors wiki page, as this one is generated automatically, but I do it before the next release
