### ISSUE TITLE
Let users define a config file

### ISSUE THREAD

**Issue by AbhinavMir** [crytic/slither#1192]
### Describe the desired feature

Would be great to have something like `slither.config.json` that helps us define what we want early on so running `slither .` runs that stated configuration specifically.

**Comment by elopez** [comment]
Hi @AbhinavMir! Thanks for the idea! Slither supports using a config file, take a look at the following link:

https://github.com/crytic/slither/wiki/Usage#configuration-file

Would this cover the use case you had in mind?

**Comment by AbhinavMir** [comment]
Oh my bad! I didn't realize this, extremely sorry!
