### ISSUE TITLE
Require Clarification: incorrect-versions-of-solidity

### ISSUE THREAD

**Issue by alexdevassy** [crytic/slither#1210]
Why does slither recommend using the below specific versions of solidity? is there a specific reason or reference for this? 
0.5.16 - 0.5.17
0.6.11 - 0.6.12
0.7.5 - 0.7.6
0.8.4 - 0.8.7 Use a simple pragma version that allows any of these versions. Consider using the latest version of Solidity for testing.
https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity

**Comment by 0xalpharush** [comment]
Relevant discussion here https://github.com/crytic/slither/issues/1251#issuecomment-1160555263
