### ISSUE TITLE
[Bug-Candidate]: Unable to analyze Foundry projects out-of-the-box

### ISSUE THREAD

**Issue by psc4l** [crytic/slither#1214]
### Describe the issue:

Running `slither .` in a Foundry project resulted in the following logs

`raise InvalidCompilation(f"{filename} does not exist (are you in the correct directory?)")
crytic_compile.platform.exceptions.InvalidCompilation: . does not exist (are you in the correct directory?)`

Running `slither . --compile-force-framework foundry` seems to allow foundry to compile the files into `/out`, but I received the following message: `No contract were found in None, check the correct compilation`.

I was able to work around this by flattening the contracts into `flat-contracts/` and running `slither flat-contracts`, but `slither .` should work out-of-the-box.

### Code example to reproduce the issue:

Solidity files were arranged in the foundry format, with no .toml files. Forge version was 0.2.0.

`/src/*.sol`

### Version:

0.8.3

### Relevant log output:

```shell
slither . --compile-force-framework foundry

'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
installing solc version "0.8.13"
Successfully installed solc 0.8.13
Compiling 31 files with 0.8.13
Compiler run successful (with warnings)
Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.



No contract were found in None, check the correct compilation

solc-0.8.13 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
No contract was analyzed
. analyzed (0 contracts with 78 detectors), 1 result(s) found
```

**Comment by 0xalpharush** [comment]
Please make sure that your foundry version is up to date using `foundryup` because you may not have upstream fixes to a bug that did not provide the AST in the artifacts. I'm using `forge 0.2.0`. If the issue persists, you may need to open an issue in Foundry since it's responsible for the AST generation.

**Comment by psc4l** [comment]
foundryup was broken - it couldn't update, even though it was showing that I was using `forge 0.2.0`. Issue was fixed after I reinstalled and ran foundryup. closing issue.
