### ISSUE TITLE
[Bug-Candidate]: Unresolved reference to identifier OneWord

### ISSUE THREAD

**Issue by naszam** [crytic/slither#1219]
### Describe the issue:

Hi, 

when running slither against `Seaport`:

`slither 0x00000000006CEE72100D161c57ADA5Bb2be1CA79 --solc ~/.solc-select/artifacts/solc-0.8.13`

I get:
```
Error: unresolved reference to identifier OneWord
```

any idea?

Thanks!

### Code example to reproduce the issue:

[0x00000000006CEE72100D161c57ADA5Bb2be1CA79](https://etherscan.io/address/0x00000000006CEE72100D161c57ADA5Bb2be1CA79)

### Version:

`0.8.3`

### Relevant log output:

```shell
File "/home/naszam/.local/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 800, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier OneWord
Error:
unresolved reference to identifier OneWord
Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by 0xalpharush** [comment]
https://github.com/crytic/slither/issues/1031#issuecomment-1138037731

**Comment by naszam** [comment]
Hi @0xalpharush,

I just tried https://github.com/crytic/slither/pull/1188 out via:

`pip install "git+https://github.com/crytic/slither@top-level-yul-identifier"`

and it seems to fix the issue.

Thanks!
