### ISSUE TITLE
[Bug-Candidate]: source code is coming different across Python versions

### ISSUE THREAD

**Issue by dheerajrp** [crytic/slither#1222]
### Describe the issue:

Hi there, 
I am trying to use slither in python 3.6.9. It is working. If I try the same in python 3.7.13, the source code is not same as it was in 3.6

Source code(3.6.9):   venv361/lib/python3.6/site-packages/slither/slither.py
Source code(3.7.13): venv371/lib/python3.7/site-packages/slither/slither.py

### Code example to reproduce the issue:

Running on Ubuntu - 18.04
IDE: PyCharm

Python version: 3.7.13
```slither --version```
producing
```ModuleNotFoundError: No module named 'pygame'```

Python version: 3.6.9
```slither --version```
producing
0.8.2

### Version:

0.8.2

### Relevant log output:

```shell
(venv361) dheeraj@DLXL-LP-053:~/Desktop/slither_test$ python --version
Python 3.6.9
(venv361) dheeraj@DLXL-LP-053:~/Desktop/slither_test$ slither --version
0.8.2
------------------------------------------------------------------------------------------
(venv371) dheeraj@DLXL-LP-053:~/Desktop/slither_test$ python --version
Python 3.7.13
(venv371) dheeraj@DLXL-LP-053:~/Desktop/slither_test$ slither --version
Traceback (most recent call last):
  File "/home/dheeraj/Desktop/slither_test/venv371/bin/slither", line 5, in <module>
    from slither.__main__ import main
  File "/home/dheeraj/Desktop/slither_test/venv371/lib/python3.7/site-packages/slither/__init__.py", line 1, in <module>
    from .slither import *
  File "/home/dheeraj/Desktop/slither_test/venv371/lib/python3.7/site-packages/slither/slither.py", line 9, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
(venv371) dheeraj@DLXL-LP-053:~/Desktop/slither_test$
```

**Comment by elopez** [comment]
Thanks for the report! From the looks of it, it seems like you installed [`slither`](https://pypi.org/project/slither/) from pip,  which is a game library that depends on pygame, instead of `slither-analyzer`, the crytic tool.

**Comment by dheerajrp** [comment]
Thanks. It worked.
