### ISSUE TITLE
custom:security non-reentrant above functions

### ISSUE THREAD

**Issue by 0xHyoga** [crytic/slither#1234]
### Describe the desired feature

I think adding the `@custom:security non-reentrant` feature was great, but it doesn't make much sense to put the comment above state variables. Whether there is a reentrancy opportunity in the contract depends on how we make use of the variables, not the variables themselves. 

Would it be possible to make the feature available for `function type variables` instead? For example with the documentation from Slither (https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities): 

This would return reentrancy with slither analyzer:

```
    function withdrawBalance(){
        // send userBalance[msg.sender] Ether to msg.sender
        // if mgs.sender is a contract, it will call its fallback function
        if( ! (msg.sender.call.value(userBalance[msg.sender])() ) ){
            throw;
        }
        userBalance[msg.sender] = 0;
    }
```

This wouldn't (I added the nonReentrant modifier from OpenZeppling to be clear): 

```
    /// @custom:security non-reentrant
    function withdrawBalance() nonReentrant {
        // send userBalance[msg.sender] Ether to msg.sender
        // if mgs.sender is a contract, it will call its fallback function
        if( ! (msg.sender.call.value(userBalance[msg.sender])() ) ){
            throw;
        }
        userBalance[msg.sender] = 0;
    }

```

Thanks!

**Comment by 0xalpharush** [comment]
That's what `// slither-disable-next-line reentrancy-eth` is for. The `@custom:security non-reentrant` is meant to be used on contract addresses that are known to be trusted by developers i.e. they control both contracts and know there aren't problematic callbacks. 

Fwiw, `nonReentrant` will eventually be ignored but it requires more precise reasoning about cross-contract and cross-function reentrancy as we would prefer false positives over false negatives.

**Comment by 0xHyoga** [comment]
But shouldn't  `// slither-disable-next-line reentrancy-eth` and `@custom:security` be merged somehow in this case? It feels awkward to mark contracts in natspec as `@custom:security non-reentrant` when it doesn't really *mean* anything. If, for example, I am marking something as `@inheritdoc IERC20` the contract is expecting the variable/function to be inheriting from `IERC20`. If it doesn't exist in IERC20, my contract will not compile.

Using the `@custom:security non-reentrant` in our case is just saying that the developer is trusting the contract, nothing else. The reentrancy opportunity still exists if the same dev makes a mistake. Just my opinion. Thanks!
