### ISSUE TITLE
0.8.4 release

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1252]
## Issues:
- [x] https://github.com/crytic/slither/issues/1001
- [x] https://github.com/crytic/slither/issues/1174
- [x] https://github.com/crytic/slither/issues/1173
- [x] https://github.com/crytic/slither/issues/1211
- [x] https://github.com/crytic/slither/pull/1227
- [ ] https://github.com/crytic/slither/issues/1019

Nice to have:
- [ ] https://github.com/crytic/slither/issues/511
- [x] https://github.com/crytic/slither/issues/482
- [ ] https://github.com/crytic/slither/issues/922
- [x] https://github.com/crytic/slither/issues/1091
## PRs to review: 
Parse top level enums: 
- [x] https://github.com/crytic/slither/pull/1245

Fix ternary parsing of unused tuple type: 
- [ ] https://github.com/crytic/slither/pull/1217

Fix call conversion when library function and state variable conflict:
- [x] https://github.com/crytic/slither/pull/1230

Update dependencies, CI, move to python 3.8: 
- [x] https://github.com/crytic/slither/pull/1178

Support top level constants in Yul:
- [x] https://github.com/crytic/slither/pull/1188

Filter calldata optimization detector: 
- [x] https://github.com/crytic/slither/pull/1022

Document questions/ helpful info: 
- [x] https://github.com/crytic/slither/pull/1047

## PR ready to merge: 
https://github.com/crytic/slither/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved

**Comment by 0xalpharush** [comment]
I think we should also consider adding mypy for a subset of the project, at the very least. Namely, the following directories: `core/`, `detectors/`, `slithir/`. There were a couple bugs recently that would have been caught by type checking.

**Comment by montyly** [comment]
Another thing to do for the release: update the solc version detector, and document our process
