### ISSUE TITLE
"not in UPPER_CASE_WITH_UNDERSCORES" should not apply to public/external constants

### ISSUE THREAD

**Issue by lukehutch** [crytic/slither#1262]
### Describe the issue:

`public`/`external` fields of a contract are exported as functions, so they are part of a public API, and Slither should not report the warning `not in UPPER_CASE_WITH_UNDERSCORES` if these fields are in lowercase.

### Code example to reproduce the issue:

```
contract A { uint256 public myVal; }
```

### Version:

0.8.3

### Relevant log output:

```shell
Constant A.myVal (contracts/A.sol#1) is not in UPPER_CASE_WITH_UNDERSCORES
```
```

**Comment by 0xalpharush** [comment]
When I run slither on this contract, I only get:
```
A.myVal (test.sol#1) should be constant
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#state-variables-that-could-be-declared-constant
```
Perhaps you had something like this?
```
contract A { uint256 public constant myVal = 0; }
```

**Comment by lukehutch** [comment]
Sorry, I didn't test the minimal example Ianually typed in. Yes, if you add `constant` it should trigger the Slither warning that is masked by the warning you got instead.

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/1530
