### ISSUE TITLE
Run slither . --ignore-config

### ISSUE THREAD

**Issue by beauwilliams** [crytic/slither#1272]
### Describe the desired feature

I would like to run slither to see low severity errors on demand.

I have low severity errors ignored in my slither.config.json because I don't need them polluting the slither CI 

However, occasionally I would like to see low severity issues, I could not find a way to do this without renaming/moving/deleting the configuration files for slither

**Comment by elopez** [comment]
Hi @beauwilliams, thanks for the feature request! You can currently (indirectly) achieve this with `slither . --config-file foobar` -- if `foobar` does not exist or is not a valid config file, slither will use the default settings.

**Comment by beauwilliams** [comment]
Awesome! I think that's good enough alternative for now 👍
