### ISSUE TITLE
Remove check events when there are none

### ISSUE THREAD

**Issue by h00p30** [crytic/slither#1275]
Some ERCs like ERC165 don't emit events themselves but `slither-check-erc` still prints `## Check events`.

Example with `slither-check-erc ERC165.sol ERC165 --erc ERC165 `: 
```
## Check functions
        [✓] supportsInterface(bytes4) is present
	[✓] supportsInterface(bytes4) -> (bool) (correct return type)
	[✓] supportsInterface(bytes4) is view

## Check events
```

I think we shouldn't print that line when the erc's events array is empty.

**Comment by 0xalpharush** [comment]
I think that makes sense. Would you like to open a PR?
