### ISSUE TITLE
[Bug-Candidate]: Error when using with foundry / forge

### ISSUE THREAD

**Issue by gigamesh** [crytic/slither#1313]
### Describe the issue:

Error when using with foundry / forge

### Code example to reproduce the issue:

The code isn't public but its a pretty minimal repo:

![image](https://user-images.githubusercontent.com/32403632/181659339-6dcea9d8-a115-4b01-b711-916bcf96399c.png)

### Version:

0.8.3

### Relevant log output:

```shell
❯ slither .
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 31 files with 0.8.15
Solc 0.8.15 finished in 7.55s
Compiler run successful

Traceback (most recent call last):
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/platform/foundry.py", line 143, in compile
    compilation_unit.srcmaps_init[contract_name] = target_loaded["bytecode"][
KeyError: 'sourceMap'
None
Error in .
Traceback (most recent call last):
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/masurka/Library/Python/3.8/lib/python/site-packages/crytic_compile/platform/foundry.py", line 143, in compile
    compilation_unit.srcmaps_init[contract_name] = target_loaded["bytecode"][
KeyError: 'sourceMap'
```
```

**Comment by elopez** [comment]
Hi! Thanks for the report, this looks like an instance of issues https://github.com/crytic/crytic-compile/issues/275 & https://github.com/crytic/crytic-compile/pull/282. Do you have `.sol` files with no contracts in them by chance?

**Comment by gigamesh** [comment]
@elopez All our contracts are in a `/contracts` directory and all `.sol` files have a contract or interface. However, I'm not sure about all our dependencies in the `/lib` directory. 

Are you pretty confident that is the cause?

**Comment by elopez** [comment]
I can't say for sure, but it seems to be the same issue judging by the error you're getting. An easy way to try is adding a dummy contract (eg `contract Foo123 {}`) to all files that have no contracts and seeing if it resolves the issue.

Another thing you could do to spot the problematic file is patch `crytic_compile/platform/foundry.py` from crytic-compile (if you want to do a quick test and avoid reinstalling packages, you can find the installed file path in the error you got and edit that) and add a print statement to show the files being processed. That should give you a hint as to where to look and confirm if this is the issue.

```diff
--- a/crytic_compile/platform/foundry.py	2022-08-12 23:34:13.913066001 +0000
+++ b/crytic_compile/platform/foundry.py	2022-08-12 23:33:39.211300013 +0000
@@ -102,6 +102,7 @@
 
         for filename_txt in filenames:
             with open(filename_txt, encoding="utf8") as file_desc:
+                print(f"Processing {filename_txt} now...")
                 target_loaded = json.load(file_desc)
 
                 userdoc = target_loaded.get("userdoc", {})
```

**Comment by gigamesh** [comment]
Hmm not sure that's the issue. It processes about 60 contracts and the last one before the error is `IERC721AUpgradeable.json`, which comes from here: https://github.com/chiru-labs/ERC721A-Upgradeable/blob/main/contracts/IERC721AUpgradeable.sol

Does that give you any clues?

**Comment by gigamesh** [comment]
Ah this is probably the culprit: https://github.com/chiru-labs/ERC721A-Upgradeable/blob/main/contracts/interfaces/IERC721AUpgradeable.sol

That same pattern is used by OpenZeppelin though, so I'm surprised more people aren't reporting the same problem. 🤔 
In any case, switching the import to this one fixed it: 
https://github.com/chiru-labs/ERC721A-Upgradeable/blob/main/contracts/IERC721AUpgradeable.sol

**Comment by sjkelleyjr** [comment]
FWIW I'm running into the same issue.  It would be nice if the output told you which contract this was failing for as for projects of any real complexity, it's non-trivial to track down the dependency that's causing the issue.

**Comment by sjkelleyjr** [comment]
is there any reason why [this](https://github.com/crytic/slither/issues/1313#issuecomment-1213591044) can't be provided in the error message so folks don't need to patch the code?

**Comment by exd0tpy** [comment]
I modified `crytic_compile\crytic_compile.py` like this.

Just catch when KeyError and return 0.
```   python
    def get_line_from_offset(self, filename: Union[Filename, str], offset: int) -> Tuple[int, int]:
        """Return the line from a given offset

        Args:
            filename (Union[Filename, str]): filename
            offset (int): global offset

        Returns:
            Tuple[int, int]: (line, line offset)
        """
        if isinstance(filename, str):
            file = self.filename_lookup(filename)
        else:
            file = filename
        if file not in self._cached_offset_to_line:
            self._get_cached_offset_to_line(file)
        lines_delimiters = self._cached_offset_to_line[file]
        try:
            res = lines_delimiters[offset]
        except:
            res = (0,0)
        return res 
```
And run `slither .` than worked.

I don't know about slither code much, so why this happened and why this is work.
But this could be help for temporary fix.
