### ISSUE TITLE
Add support for brownie framework

### ISSUE THREAD

**Issue by ismail-moazami** [crytic/slither#1321]
### Describe the desired feature

Hello.
I am solidity developer that uses brownie for deploying and testing smart contracts, so I and other brownie devs need to slither integrations with brownie.
Please add support for brownie. 
Thanks.

**Comment by montyly** [comment]
Hi @ismail-moazami. We do already support brownie. If slither does not work for you, could you share the codebase where it happens?

In practice, slither looks for `brownie-config.json`, `brownie-config.yaml`, or `brownie-config.yml` to detect that the target uses brownie. If you don't use one of these config file, you can use `slither /path/to/target --compile-force-framework brownie` to force the use of brownie.

However be aware that brownie has a couple of bugs that might prevent slither from working (ex: https://github.com/eth-brownie/brownie/issues/941)
