### ISSUE TITLE
[Bug-Candidate]: sourceMapping goes OoB when '}' is last char of file

### ISSUE THREAD

**Issue by plotchy** [crytic/slither#1328]
### Describe the issue:

Have been creating a new printer for slither, and am iterating over functions in the contract and printing their code.

Noticed that the `FunctionType.CONSTRUCTOR_VARIABLES` is created when a variable is initialized in a contract.

If these types are **not** filtered out when iterating, the printer has been crashing with a OoB error when grabbing the source code.

Reporting this as it seems to be an issue with a `}` being the last char of a file, and may affect other types' sourceMapping.

### Code example to reproduce the issue:

**Fails**
```
pragma solidity ^0.8.12;
contract OoB {
    uint public a = 5;
}
```

This issue does not occur if there is a newline after the last curly brace in the contract:
**Succeeds**
```
pragma solidity ^0.8.12;
contract Not_OoB {
    uint public a = 5;
}
//newline
```

Also does not occur if there are any chars following the last curly brace:
**Succeeds**
```
pragma solidity ^0.8.12;
contract Not_OoB {
    uint public a = 5;
} //comment
```

Tested using these slither objects in the printer:
```python
for contract in self.slither.contracts:
    with open(contract.source_mapping["filename_absolute"], "r", encoding="utf8") as f:
        contract_file_lines = f.readlines()
    for function in contract.functions_declared: 
        lines = function.source_mapping["lines"]  # This grabs one line that is OoB in the first contract example
        for line in lines:
            code_line = f"{contract_file_lines[line - 1].rstrip()}\n" # Triggers Index Error
```

### Version:

0.8.3

### Relevant log output:

```shell
Error in c.sol
Traceback (most recent call last):
    code_line = f"{contract_file_lines[line - 1].rstrip()}\n"
IndexError: list index out of range
```

**Comment by 0xalpharush** [comment]
I'm not very familiar with this part of the code, but I wouldn't assume that there's a one-to-one mapping between the lines read and line numbers internally in slither (I think this is provided by solc). 

You might try something like this: 
```
for contract in slither.contracts:
    for function in contract.functions_declared: 
        start = function.source_mapping.start  
        end = function.source_mapping.end
        print(slither.source_code[function.source_mapping.filename.absolute][start:end])

```
This is using the new API as we're making a breaking change in the upcoming release.

**Comment by plotchy** [comment]
Ok, updated to latest dev branch. Your recommendation worked great 🎉

```python
for contract in self.slither.contracts:
    for function in contract.functions_declared: 
        source_code = self.slither.source_code[function.source_mapping.filename.absolute]
        start_char = function.source_mapping.start  
        end_char = function.source_mapping.end
        txt = "```js\n"
        txt += source_code[start_char:end_char] + "\n"
        txt += "```\n"
        print(txt)
```

I like the new API
