### ISSUE TITLE
Add support for top level using for directive

### ISSUE THREAD

**Issue by CodeSandwich** [crytic/slither#1352]
### Describe the issue:

I'm trying to run `slither .` on a project and I'm getting the error:
```
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 36 files with 0.8.15
Solc 0.8.15 finished in 5.35s
Compiler run successful

Traceback (most recent call last):
  File "/home/zuczek/.local/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/zuczek/.local/lib/python3.10/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/zuczek/.local/lib/python3.10/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/zuczek/.local/lib/python3.10/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/zuczek/.local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 320, in parse_top_level_from_loaded_json
    raise SlitherException(f"Top level {top_level_data[self.get_key()]} not supported")
slither.exceptions.SlitherException: Top level UsingForDirective not supported
Error:
Top level UsingForDirective not supported
Please report an issue to https://github.com/crytic/slither/issues
```

The project uses Forge (yesterday version) and Solidity 0.8.15. This is the first Slither run ever, all I did before was running `pip3 install slither-analyzer`. I haven't installed `solc` manually, Slither seems to be using Forge and whatever compiler it has inside. (If that's the case, congratulations on that integration, I love it!). I'm running Manjaro Linux. Both `python --version` and `python3 --version` yield `Python 3.10.5`.

### Code example to reproduce the issue:

https://github.com/radicle-dev/drips-contracts

### Version:

0.8.3

### Relevant log output:

```shell
I don't know where can I find the logs, if you tell me, I'll add them
```

**Comment by plotchy** [comment]
Files with `using A for B` or `using {x, y, x} for A` in a top-level scope (outside of contracts) isn't supported atm. 

Error also manifests as `InvalidCompilation`

Contract taken from Solidity docs:
https://docs.soliditylang.org/en/latest/contracts.html?highlight=using%20for#using-for
```js
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.3;

struct Data { mapping(uint => bool) flags; }
using {insert, remove, contains} for Data; // problem line

function insert(Data storage self, uint value)
    returns (bool)
{
    if (self.flags[value])
        return false; // already there
    self.flags[value] = true;
    return true;
}

function remove(Data storage self, uint value)
    returns (bool)
{
    if (!self.flags[value])
        return false; // not there
    self.flags[value] = false;
    return true;
}

function contains(Data storage self, uint value)
    view
    returns (bool)
{
    return self.flags[value];
}


contract C {
    Data knownValues;

    function register(uint value) public {
        // Here, all variables of type Data have
        // corresponding member functions.
        // The following function call is identical to
        // `Set.insert(knownValues, value)`
        require(knownValues.insert(value));
    }
}
```

```sh
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
  --> using_for.sol:12:1:
   |
12 | using {insert, remove, contains} for Data;
   | ^^^^^
```

**Comment by CodeSandwich** [comment]
Oh, that's right, the project does have one top-level `using ... for ... global;`: https://github.com/radicle-dev/drips-contracts/blob/master/src/Drips.sol#L24.

Should I open an issue in `crytic-compile`? IIUC `crytic-compile` is not a compiler, but a wrapper using whatever is used in the project. After a quick skimming it seems like dapptools is supported, but not Foundry (hence https://github.com/crytic/crytic-compile/issues/230). Does the problem come from falling back from using Foundry to a raw, obsolete version of `solc`? Or is it Slither surprised by an unexpected AST node?

**Comment by 0xalpharush** [comment]
This solidity feature hasn't been added to slither yet, so this is the correct place to have opened an issue.

**Comment by CodeSandwich** [comment]
I've tried running Slither using branch `dev-fix-usingfor` from PR https://github.com/crytic/slither/pull/1378 and indeed it doesn't throw the `Top level UsingForDirective not supported` anymore. Unfortunately it throws this strange exception:
```
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 52 files with 0.8.17
Solc 0.8.17 finished in 7.19s
Compiler run successful

Traceback (most recent call last):
  File "/home/zuczek/workspace/slither/slither/core/cfg/node.py", line 911, in _find_read_write_call
    self._high_level_calls.append((ir.destination.type.type, ir.function))
AttributeError: 'NoneType' object has no attribute 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zuczek/workspace/slither/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/zuczek/workspace/slither/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/zuczek/workspace/slither/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/zuczek/workspace/slither/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/home/zuczek/workspace/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 519, in analyze_contracts
    self._convert_to_slithir()
  File "/home/zuczek/workspace/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 713, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/zuczek/workspace/slither/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/zuczek/workspace/slither/slither/core/cfg/node.py", line 721, in slithir_generation
    self._find_read_write_call()
  File "/home/zuczek/workspace/slither/slither/core/cfg/node.py", line 914, in _find_read_write_call
    raise SlitherException(
slither.exceptions.SlitherException: Function not found on IR: TMP_320(None) = HIGH_LEVEL_CALL, dest:TMP_319(None), function:sig, arguments:['1889567281']  .
Node: EXPRESSION stdstore.target(token).sig(0x70a08231).with_key(to).checked_write(give) (lib/forge-std/src/Test.sol#104-108)
Function: tip
Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
Error:
Function not found on IR: TMP_320(None) = HIGH_LEVEL_CALL, dest:TMP_319(None), function:sig, arguments:['1889567281']  .
Node: EXPRESSION stdstore.target(token).sig(0x70a08231).with_key(to).checked_write(give) (lib/forge-std/src/Test.sol#104-108)
Function: tip
Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
Please report an issue to https://github.com/crytic/slither/issues
```
I have no idea what this exception means. Is it another issue or is the fix incomplete? The most similar exception to this one is in https://github.com/crytic/slither/issues/1295, but it's hard to tell if it's the same problem.

**Comment by smonicas** [comment]
Hi @CodeSandwich, i can't understand from only this exception if it's related to the fix or not. Could you share the codebase?

**Comment by CodeSandwich** [comment]
I've found the root issue. It turns out that Slither has a problem with the Foundry's test utils. Even the exception says that the problem was found in `lib/forge-std/src/Test.sol`. The solution is to temporarily hide the test directory from Slither: 

```bash
FOUNDRY_TEST=nonexisten slither .
```

**Comment by paulrberg** [comment]
I've just wanted to use Slither for the first time in a while, and I bumped into this immediately as soon as I run it.

My math library PRBMath [makes extensive use](https://github.com/paulrberg/prb-math/blob/0d8c865fe4f5415a9b3d910c0d03635a22a99a50/src/UD60x18.sol) of user-defined value types and top-level using for directives - so all of the library users will bump into the same issue.

**Comment by montyly** [comment]
Hi @paulrberg . We actually worked on the support this week (https://github.com/crytic/slither/pull/1378, https://github.com/crytic/slither/pull/1563). We encountered a couple of edge cases that slowed us down, but we are aiming for a release at the beginning of next week.

We will try slither on your repo to make sure it passes before the release

**Comment by paulrberg** [comment]
Great news, thanks very much, @montyly!

**Comment by PaulRBerg** [comment]
Thanks for implementing this feature, guys!

Unfortunately, we might have to re-open this issue. Slither doesn't work with chained function calls on value types:

```solidity
pragma solidity >=0.8.17;

import { UD60x18, ud } from "prb-math/UD60x18.sol";

contract Foo {
    function tryUnwrap(UD60x18 a, UD60x18 b) external pure returns (uint256 c, uint256 d) {
        // This is ok
        c = a.unwrap();
        // This triggers a bug
        d = a.mul(b).unwrap();
    }
}
```

Defining `c` works, but `d` doesn't. That is, I am getting the following error:

```text
Error:
Function not found on IR: TMP_3575(None) = HIGH_LEVEL_CALL, dest:TMP_3574(None), function:unwrap, arguments:[]  .
Node: EXPRESSION d = a.mul(b).unwrap() (src/Foo.sol#9)
Function: tryUnwrap
Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
```

I can attach the full stack trace but you should be able to replicate this by spinning up a Foundry project and installing [PRBMath](https://github.com/paulrberg/prb-math) (the latest commit from `main`).

**Comment by 0xalpharush** [comment]
@PaulRBerg I've opened an issue, and we'll get this fixed soon. Thanks for taking the time to report the bug and provide an example as it helps a ton!
