### ISSUE TITLE
[Bug-Candidate]: Command not found after install

### ISSUE THREAD

**Issue by obitubi** [crytic/slither#1367]
### Describe the issue:

Hello, I still new on using slither, after install on vscode that integrate with python, nodejs, solidity, the command to running `slither .` says command not found, I try to to recognize it, and there is issue that I must install VsC++. After installing C++, slither still can not work, command still not found, what should I do? thank you

### Code example to reproduce the issue:

$ git clone https://github.com/trailofbits/slither
Cloning into 'slither'...
remote: Enumerating objects: 48539, done.
remote: Counting objects: 100% (1348/1348), done.
remote: Compressing objects: 100% (640/640), done.
remote: Total 48539 (delta 773), reused 1242 (delta 703), pack-reused 47191Receiving objects: 100% (48539/48539), 42.79 MiB | 1.Receiving objects: 100% (48539/48539), 44.11 MiB | 848.00 KiB/s, done.
Resolving deltas:   0% (0/23168)
Resolving deltas: 100% (23168/23168), done.
Updating files: 100% (15843/15843), done.

slither .
bash: slither: command not found

$ slither --help
bash: slither: command not found

### Version:

$ slither --version
bash: slither: command not found

### Relevant log output:

```shell
command not found
```

**Comment by Haruxe** [comment]
You can follow [this](https://github.com/crytic/slither#how-to-install) portion of the README.md document to help with installing it, but in your case you have to run the python install script from the cloned repository first. You can do this by running the command `python3 setup.py install`.

**Comment by elopez** [comment]
I'll close this issue now but feel free to open a new one if you are still having issues.
