### ISSUE TITLE
Slither interpreting triple slash comments (///) as block comments (/** */)

### ISSUE THREAD

**Issue by tuv7041** [crytic/slither#1382]
### Describe the issue:

I'm trying to run slither on this smart contract: https://github.com/new-order-network/governance-token-v2/blob/e9cde694e53005e4504ae44d6462ee07e638a511/contracts/GovernanceTokenV2.sol

The contract has 3 instances of single line comment with triple slashes similar to this one:

```
    /// @dev Calculates the maximum amount of transferrable tokens for address `who`. Alias for calcMaxTransferrable for backwards compatibility.
    /// @return Number of transferrable tokens 
    function balanceUnlocked(address who) public view virtual override returns (uint256 amount){
        return calcMaxTransferrable(who);
    }
```

And when running slither, it returns errors like this one:
```

Error: Documentation tag "@return Number of transferrable tokens " does not contain the name of its return parameter.
   --> GovernanceTokenV2.sol:156:5:
    |
156 |     /// @dev Calculates the maximum amount of transferrable tokens for address `who`. Alias for calcMaxTransferrable for backwards compatibility.
    |     ^ (Relevant source part starts here and spans across multiple lines).


```

It seems like it's interpreting the single line comment as a multi line comment, and closing the block comment right before the @return. I've verified that modifying the "///" for "//" fixes the problem and slither runs OK.

### Code example to reproduce the issue:

wget https://raw.githubusercontent.com/new-order-network/governance-token-v2/e9cde694e53005e4504ae44d6462ee07e638a511/contracts/GovernanceTokenV2.sol

slither GovernanceTokenV2.sol

### Version:

0.8.3

### Relevant log output:

```shell
Compilation warnings/errors on GovernanceTokenV2.sol:
Error: Documentation tag "@return Number of locked tokens " does not contain the name of its return parameter.
   --> GovernanceTokenV2.sol:134:5:
    |
134 |     /// @dev Calculates the amount of locked tokens for address `who`
    |     ^ (Relevant source part starts here and spans across multiple lines).

Error: Documentation tag "@return Number of transferrable tokens " does not contain the name of its return parameter.
   --> GovernanceTokenV2.sol:156:5:
    |
156 |     /// @dev Calculates the maximum amount of transferrable tokens for address `who`. Alias for calcMaxTransferrable for backwards compatibility.
    |     ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by 0xalpharush** [comment]
This is an error from the solidity compiler for what appears to be a natspec violation.
https://docs.soliditylang.org/en/develop/natspec-format.html
