### ISSUE TITLE
[Bug]: Incorrect reference to Detector Documentation

### ISSUE THREAD

**Issue by rpajunen** [crytic/slither#1390]
### Describe the issue:

Incorrect shift operation error has broken [reference](https://github.com/crytic/slither/wiki/Detector-Documentation#shift-parameter-mixup) to GitHub page. 

### Code example to reproduce the issue:

Run Slither on [ERC721A](https://github.com/chiru-labs/ERC721A) contract.

### Version:

0.8.3

### Relevant log output:

```shell
ERC721A._mint(address,uint256) (node_modules/erc721a/contracts/ERC721A.sol#733-797) contains an incorrect shift operation: _packedAddressData[to] += quantity * ((1 << _BITPOS_NUMBER_MINTED) | 1) (node_modules/erc721a/contracts/ERC721A.sol#748)
ERC721A._burn(uint256,bool) (node_modules/erc721a/contracts/ERC721A.sol#917-983) contains an incorrect shift operation: _packedAddressData[from] += (1 << _BITPOS_NUMBER_BURNED) - 1 (node_modules/erc721a/contracts/ERC721A.sol#950)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#shift-parameter-mixup
```

**Comment by 0xalpharush** [comment]
This was updated https://github.com/crytic/slither/blob/64b2e0c063cf93fb479481abc432371404629f32/slither/detectors/assembly/shift_parameter_mixup.py#L19-L21
