### ISSUE TITLE
[Bug-Candidate]: --exclude-informational does not exclude Informational scanners

### ISSUE THREAD

**Issue by antonper** [crytic/slither#1408]
### Describe the issue:

--exclude-informational does not exclude Informational scanners like dead-code and solc-version

### Code example to reproduce the issue:
```solidity
pragma solidity ^0.8.0;

contract A{
    function foo() external {
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}
```

### Version:

0.9.0

### Relevant log output:

```shell
 slither --disable-color   --exclude-informational --checklist a.sol        
 Compilation warnings/errors on a.sol:

Compilation warnings/errors on a.sol:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> a.sol



A._msgData() (a.sol#7-9) is never used and should be removed
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#dead-code

Pragma version^0.8.0 (a.sol#1) allows old versions
solc-0.8.15 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
Summary
 - [dead-code](#dead-code) (1 results) (Informational)
 - [solc-version](#solc-version) (2 results) (Informational)
## dead-code
Impact: Informational
Confidence: Medium
 - [ ] ID-0
[A._msgData()](a.sol#L7-L9) is never used and should be removed

a.sol#L7-L9


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-1
Pragma version[^0.8.0](a.sol#L1) allows old versions

a.sol#L1


 - [ ] ID-2
solc-0.8.15 is not recommended for deployment

a.sol analyzed (1 contracts with 81 detectors), 3 result(s) found
```

**Comment by elopez** [comment]
Thanks for the report @antonper! From [a look at the code](https://github.com/crytic/slither/blob/aa4a57d05015a8e5e103e7d5c8d25a76a58216c0/slither/__main__.py#L223-L243), `--exclude-*` options get honored if the corresponding `--fail-*` option is not enabled. This makes sense, as requesting to fail on e.g. medium or higher issues while disabling all of the medium detectors is contradictory. However, `--fail-pedantic` is the default Slither behavior, so you will need to provide `--no-fail-pedantic` to be able to use `--exclude-informational` or `--exclude-optimization`

```sh
% slither a.sol --disable-color   --exclude-informational --checklist --no-fail-pedantic
Compilation warnings/errors on a.sol:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> a.sol


Summary
a.sol analyzed (1 contracts with 62 detectors), 0 result(s) found
```

I agree it is unintuitive though 🤔 do you have any suggestions on how to improve this?

**Comment by antonper** [comment]
In version 0.8.3 the solc-verstion and dead-code were ignored by the --exclude-informational. Did --fail-pedantic is new default starting from 0.9.0?

**Comment by elopez** [comment]
Yeah, I guess that also adds to the confusion, `--(no-)fail-pedantic` covers both "optimization" and "informational" levels, there's no separate flags for those two.

**Comment by 0xCLARITY** [comment]
> This makes sense, as requesting to fail on e.g. medium or higher issues while disabling all of the medium detectors is contradictory

Are `--exclude-*` and `--fail-*` not different ways of expressing the same thing? (For example, ignore / don't fail on any informational scanner)?

Or is the idea that with `--fail-low`, you would still run the informational scanners and log them, but not exit with a failure code?

**Comment by elopez** [comment]
> 
> Or is the idea that with `--fail-low`, you would still run the informational scanners and log them, but not exit with a failure code?

Exactly, the `--fail-*` options control the threshold used to exit with a failure code, while `--exclude-*` manages the detectors that are run. For example, if you have just a lot of informational findings, but `--fail-medium` is used, it will still show you the detections, but not exit with a failure code. If you then introduce a medium or high severity problem in the codebase, Slither will start detecting it and exiting with a failure code.

**Comment by 0xalpharush** [comment]
I think this is closed by https://github.com/crytic/slither/pull/1462 but if anyone has issues/confusion we can reopen
