### ISSUE TITLE
Slither-flat ignores custom errors defined outside of contract

### ISSUE THREAD

**Issue by MarkuSchick** [crytic/slither#1410]
### Describe the problem:

[Custom errors](https://blog.soliditylang.org/2021/04/21/custom-errors/) defined outside of a contract are not imported into the flattened contract.
This is a problem when working with contracts like [pr math](https://github.com/paulrberg/prb-math) that define the custom error outside the contract.
Below is an minimum working example showcasing the bug.

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.16;

error RevertIt();

contract Example {
  function reverts() external pure {
    revert RevertIt();
  }
}
```

### Version:

0.8.3, 0.9.0

### Flattened contract:

```solidity
pragma solidity 0.8.16;
contract Example {
    function reverts() external pure {
        revert RevertIt();
    }
}
```

**Comment by supernovahs** [comment]
@0xalpharush  I would like to work on this bug. Could you point me to the code/resources for the same?

**Comment by 0xalpharush** [comment]
@supernovahs You would need to add the top level custom errors here: https://github.com/crytic/slither/blob/7ea572723b4eddb18e716c4ae94e0d2100791127/slither/tools/flattening/flattening.py#L76-L79

The compilation unit records the top level custom errors here:
https://github.com/crytic/slither/blob/master/slither/core/compilation_unit.py#L46

**Comment by UtsavAnime** [comment]
Is there any update on this?

**Comment by saicharan1248** [comment]
there going to update in 0.9.4 or in next update?
