### ISSUE TITLE
[Bug-Candidate]: error: legacy-install-failure

### ISSUE THREAD

**Issue by agentjacker** [crytic/slither#1412]
### Describe the issue:

tried running `pip3 install slither-analyzer` when trying to install slither. I already have solc-select installed. does anyone know a fix? Also when i run slither --version it says its not recognized. i use  windows
<img width="908" alt="bfgbtr" src="https://user-images.githubusercontent.com/114850373/194427144-c8c7c065-7ef5-4166-8062-f1ad3f1436d4.png">
<img width="910" alt="nv " src="https://user-images.githubusercontent.com/114850373/194427154-67007c70-3166-4e04-ab49-52ec15147c04.png">

### Code example to reproduce the issue:

pip3 install slither-analyzer

### Version:

none

**Comment by elopez** [comment]
Hi @agentjacker! Slither depends on `pysha3`, which has a native code (C/C++) component. You need to install "Microsoft C++ Build Tools" to be able to build this dependency, as shown on the error message in your screenshot. You can get the tools from [Microsoft's site](https://visualstudio.microsoft.com/visual-cpp-build-tools/). Once the tools are installed, reboot and try installing Slither again.

**Comment by agentjacker** [comment]
hey i just did that and everything is installed. but when i tried slither --help it gave me this error
<img width="923" alt="image" src="https://user-images.githubusercontent.com/114850373/194434984-29c70a00-3102-4b07-bfa3-807489cd00a5.png">

**Comment by elopez** [comment]
You will need to add that `Scripts` directory to the system `PATH` for it to be runnable from anywhere as `slither` in the terminal. `pip` usually prints a warning letting you know that as well when installing the packages. This is not something slither-specific, you will have the same issue with other command-line Python tools.

The easy way to do so is by ticking the box marked "1" in the image below when installing Python. You can see the more manual ways to do it in this article: https://www.makeuseof.com/python-windows-path/. Note that you may need to restart for Windows to pick up the changes in PATH.

<img src=https://www.pythontutorial.net/wp-content/uploads/2020/09/Install-Python-Windows-Step-1.png>

**Comment by agentjacker** [comment]
thanks alot it worked.!!
