### ISSUE TITLE
[Bug-Candidate]: When I import Enum from library to another sol file, This enum can not be found 

### ISSUE THREAD

**Issue by dev1line** [crytic/slither#1416]
### Describe the issue:

When I import Enum from library to another sol file, This enum can not be found 

### Code example to reproduce the issue:

library NFTHelper {
    enum Type {
        ERC721,
        ERC1155,
        NONE
    }
}

### Version:

0.8.9

### Relevant log output:

```shell
Error:
Type not found enum NFTHelper.Type
```

**Comment by 0xalpharush** [comment]
@dev1line If you can share more info, we will reopen
