### ISSUE TITLE
`naming-convention` does not flag `I` or `O` variable

### ISSUE THREAD

**Issue by elopez** [crytic/slither#1418]
### Describe the issue:

Slither has a detection for usage of

* l - Lowercase letter el
* O - Uppercase letter oh
* I - Uppercase letter eye

https://docs.soliditylang.org/en/v0.8.17/style-guide.html#names-to-avoid

However this detection fails on O and I, as the code considers them "uppercase with underscores" even though there are no underscores.

Relevant code:
* https://github.com/crytic/slither/blob/fba37f2c0c8196079719432d6324e42a1a974399/slither/detectors/naming_convention/naming_convention.py#L52-L54 (will match just uppercase letters as well)
* https://github.com/crytic/slither/blob/fba37f2c0c8196079719432d6324e42a1a974399/slither/detectors/naming_convention/naming_convention.py#L120-L137 (detection code)

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

contract C {
    bool constant l = false;
    bool constant O = false;
    bool constant I = false;
    function f() public pure {}
}
```

### Version:

0.9.0

**Comment by webthethird** [comment]
Should this issue be closed? I'm cruising the open issue tracker for "good first issue" opportunities, and there are a few like this that appear to have been resolved (based on being mentioned in other issues/PRs)
