### ISSUE TITLE
[Bug-Candidate]: In SSA, EventCall is missing arguments.

### ISSUE THREAD

**Issue by charlesxsh** [crytic/slither#1438]
### Describe the issue:

when print slithir-ssa, the arguments of emit event call is missing.

### Code example to reproduce the issue:

`
contract BasicToken {
    mapping(address => uint256) balances;

    function transfer(address _to, uint256 _value) external  {
        balances[msg.sender] = balances[msg.sender] - _value;
        balances[_to] = balances[_to] + _value;
        emit Transfer(msg.sender, _to, _value);
    }
}
`

### Version:

0.9.0

### Relevant log output:

```shell
Expression: Transfer(msg.sender,_to,_value)
IRs:
   Emit Transfer()
```

**Comment by 0xalpharush** [comment]
Maybe this https://github.com/crytic/slither/issues/1345
