### ISSUE TITLE
Add property support for `is_abstract` for contracts

### ISSUE THREAD

**Issue by plotchy** [crytic/slither#1439]
### Describe the desired feature

Adding a contract property of `is_abstract` can lead to more robust detection + less false positives.
Usually `abstract` contracts are detected through checking whether there are functions that are not implemented:
```python
if not all(f.is_implemented for f in contract.functions + list(contract.modifiers)):
    # is abstract
```
However, a contract can still be `abstract` (and undeployable) [even if all functions are implemented.](https://docs.soliditylang.org/en/latest/contracts.html#abstract-contracts) This can lead to false positives amongst detectors that assume these contracts can be deployed as is.

One example is the detector for `uninitialized-state` that checks only fully-derived contracts, although the presence of `abstract` contracts amongst these can lead to false positives.

### Possible Implementation
Property should probably be set during analyzing in the solc_parsing section.
[    def _parse_contract_info(self):](https://github.com/crytic/slither/blob/463df49c67d438cd6853b80f41bdf8953c237b9a/slither/solc_parsing/declarations/contract.py#L150-L162)
Maybe there is an `abstract` `contractKind` already?

**Comment by montyly** [comment]
that's a great point @plotchy, we should do that

**Comment by plotchy** [comment]
@0xalpharush sure, can do

**Comment by 0xalpharush** [comment]
This was added in https://github.com/crytic/slither/pull/1679
