### ISSUE TITLE
[Bug-Candidate]: Slither VSCode extension not working

### ISSUE THREAD

**Issue by krypston104** [crytic/slither#1448]
### Describe the issue:

I have Slither installed and I am able to run it in my projects from the terminal  by using `python -m slither .` without any problem. However, being installed the VSCode extension, I am not able to run it from there and get the analysis results tidily displayed in it. This is the error I get when I request the analysis:

```
⸻ Starting analysis ⸻
Error: Traceback (most recent call last):
  File "C:\Python310\Lib\site-packages\slither\slither.py", line 7, in <module>
    from slither.core.compilation_unit import SlitherCompilationUnit
  File "C:\Python310\Lib\site-packages\slither\slither.py", line 7, in <module>
    from slither.core.compilation_unit import SlitherCompilationUnit
ModuleNotFoundError: No module named 'slither.core'; 'slither' is not a package

Error: Slither not found:
Please verify slither is installed with the following command: "pip install slither-analyzer"
For more information, please visit: https://github.com/crytic/slither
Refreshing explorer...
```

This is most surprising, since I can actually make it work from the terminal, as I say, and get the results displayed while the `Slither not found` error shows in the corner:

![CapturaSlither1](https://user-images.githubusercontent.com/108148253/199588572-c88da72e-4399-4127-95be-aca4a31fee2c.JPG)

![CapturaSlither2](https://user-images.githubusercontent.com/108148253/199588605-662ce2fc-00e0-440c-beb3-b7524edce873.JPG)

### Code example to reproduce the issue:

```
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

contract Migrations {
  address public owner = msg.sender;
  uint public last_completed_migration;

  modifier restricted() {
    require(
      msg.sender == owner,
      "This function is restricted to the contract's owner"
    );
    _;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }
}
```

### Version:

0.8.3

### Relevant log output:

```shell
⸻ Starting analysis ⸻
Error: Traceback (most recent call last):
  File "C:\Python310\Lib\site-packages\slither\slither.py", line 7, in <module>
    from slither.core.compilation_unit import SlitherCompilationUnit
  File "C:\Python310\Lib\site-packages\slither\slither.py", line 7, in <module>
    from slither.core.compilation_unit import SlitherCompilationUnit
ModuleNotFoundError: No module named 'slither.core'; 'slither' is not a package

Error: Slither not found:
Please verify slither is installed with the following command: "pip install slither-analyzer"
For more information, please visit: https://github.com/crytic/slither
Refreshing explorer...
```

**Comment by 0xalpharush** [comment]
It looks like you many have conflicting python configurations since you can run `python -m slither .`. I would make sure the python where slither is installed matches your PATH (configuring this will depend on your OS). If that doesn't help, let me know please.

**Comment by 0xalpharush** [comment]
If you are still experiencing this issue, please share the output of `slither-doctor .` and we will reopen
