### ISSUE TITLE
implicit, named return does not have RETURN node

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1450]
```
function test() external view returns (uint named) {
     named = 1;
     // name in return parameter list indicates implicit return
}
```
The AST does not contain a `ReturnStatement` so we never create a `RETURN` node. We can enhance slithIR with this implicit return and change the node's type.

**Comment by webthethird** [comment]
> We can enhance slithIR with this implicit return and change the node's type.

You mean change the type of the node containing the AssignmentOperation from `EXPRESSION`  to `RETURN`, right? 
Would this be done after parsing the function's CFG? And is it necessary that the node with the AssignmentOperation have no children?

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/2326
