### ISSUE TITLE
feat: support `// slither-disable-start <detectors>` and `// slither-disable-end <detectors>`

### ISSUE THREAD

**Issue by mds1** [crytic/slither#1453]
### Describe the desired feature

Right now you can only disable detectors for the next line, but it would very helpful to be able to disable them for larger blocks of code. A sample use case is writing solidity scripts with foundry: reentrancy is not a concern at all so I can disable reentrancy for the file, but I still want to run uninitialized variable checks to avoid passing the zero address as function inputs.

I feel like this shouldn't be too hard to implement since `// slither-disable-next-line` is already implemented, so if you can provide some guidance on how to add this I'm happy to take a shot to get this merged sooner 🙂

Sample usage to disable some reentrancy checks for the full file (I think this only disables one category of reentrancy checks, not sure if there's a shorthand for disabling all of them)

```solidity
// slither-disable-start reentrancy-benign

pragma solidity ^0.8.16;

import "forge-std/Script.sol";
import {Counter} from "src/Counter.sol";

contract Deploy is Script {
  Counter counter;

  function run() public {
    vm.startBroadcast();
    counter = new Counter();
  }
}
```

**Comment by 0xalpharush** [comment]
Right now, the results get filtered out here: 
https://github.com/crytic/slither/blob/4a6ba78aca5eebff237509274b48c26e011853d6/slither/core/slither_core.py#L244
It currently looks at the previous line of the result:
https://github.com/crytic/slither/blob/4a6ba78aca5eebff237509274b48c26e011853d6/slither/core/slither_core.py#L185-L196
I think it'd make sense to create and memoize a dict for each file that records what checks are disabled , and filter based off that.
```
if result["check"] in ignore_file_dict[file]:
  check if elems in results["elements"] overlap with range of start-end or have ignore comment on previous line 
```

**Comment by mds1** [comment]
Thanks! That was super helpful, just opened https://github.com/crytic/slither/pull/1461
