### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by Marvinmw** [crytic/slither#1474]
### Describe the issue:

SlitherError: Invalid compilation: 
Solidity version not found: 

I have installed all Solidity versions. In my MAC OS, solc has no --version option.
### Code example to reproduce the issue:

contract C {
    int8 constant a = -7;
    function f() public pure {
        uint[-a] memory x;
        x[0] = 2;
    }
}

### Version:

0.9.1

### Relevant log output:

```shell
InvalidCompilation                        Traceback (most recent call last)
File ~/opt/anaconda3/envs/lib/python3.10/site-packages/slither/slither.py:91, in Slither.__init__(self, target, **kwargs)
     90 else:
---> 91     crytic_compile = CryticCompile(target, **kwargs)
     92 self._crytic_compile = crytic_compile

File ~/opt/anaconda3/envs/lib/python3.10/site-packages/crytic_compile/crytic_compile.py:117, in CryticCompile.__init__(self, target, **kwargs)
    115 self._bytecode_only = False
--> 117 self._compile(**kwargs)

File ~/opt/anaconda3/envs//lib/python3.10/site-packages/crytic_compile/crytic_compile.py:548, in CryticCompile._compile(self, **kwargs)
    547 else:
--> 548     self._platform.compile(self, **kwargs)
    550 remove_metadata = kwargs.get("compile_remove_metadata", False)

File ~/opt/anaconda3/envs/lib/python3.10/site-packages/crytic_compile/platform/solc.py:154, in Solc.compile(self, crytic_compile, **kwargs)
    152 compilation_unit = CompilationUnit(crytic_compile, str(self._target))
--> 154 targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
    156 # there have been a couple of changes in solc starting from 0.8.x,

File ~/opt/anaconda3/envs/lib/python3.10/site-packages/crytic_compile/platform/solc.py:276, in _get_targets_json(compilation_unit, target, **kwargs)
    264     return _run_solcs_env(
    265         compilation_unit,
    266         target,
...
     96 for compilation_unit in crytic_compile.compilation_units.values():
     97     compilation_unit_slither = SlitherCompilationUnit(self, compilation_unit)

SlitherError: Invalid compilation: 
Solidity version not found:
```

**Comment by 0xalpharush** [comment]
It looks like you don't have solidity compiler installed. You can install it with `pip install solc-select && solc-select install [version]` where version is something like 0.8.17 or whatever version of solc you'd like to use

**Comment by Marvinmw** [comment]
> It looks like you don't have the solidity compiler installed. You can install it with `pip install solc-select && solc-select install [version]` where version is something like 0.8.17 or whatever version of solc you'd like to use.

hi, it does not work... I am using MAC OS.

**Comment by Marvinmw** [comment]
On Mac, solc does not have --version option.

**Comment by elopez** [comment]
Hi! solc for mac does have `--version`, are you sure you're running solc and not something else like solcjs?

Can run the following commands to check?

```sh
hash -r
which solc
which solc-select
```

If you installed `solc-select` to manage the different solc installations, you can get a certain solc installed and selected like this:

```sh
solc-select install 0.8.17
solc-select use 0.8.17
solc --version
```
