### ISSUE TITLE
[Bug-Candidate]: slither not found error from vscode

### ISSUE THREAD

**Issue by billtlee** [crytic/slither#1478]
### Describe the issue:

I am on OSX and am using pyenv.  I have installed slither and the vscode extension.  However, every time I start code, I am getting error saying slither not found.

### Code example to reproduce the issue:

NA

### Version:

➜  nft-marketplace git:(nightly) slither --version
0.9.0
➜  nft-marketplace git:(nightly)

**Comment by billtlee** [comment]
⸻ Slither: Solidity static analysis framework by Trail of Bits ⸻
Error: /bin/sh: slither: command not found

Error: Slither not found:
Please verify slither is installed with the following command: "pip install slither-analyzer"
For more information, please visit: https://github.com/crytic/slither

**Comment by moconnell** [comment]
Co-sign. Also on macOS (Ventura 13.2.1) and am getting this. 

I note that the error refers to `/bin/sh` and not the correct default shell `/bin/zsh`: 
```
Error: /bin/sh: slither: command not found
```
 Could this be the issue?

**Comment by 0xalpharush** [comment]
There appears to be an issue with your PYTHON_PATH. It'd be helpful to know how you install python and what your operating system is. Please check out the discussions page which has a form to get help with installation https://github.com/crytic/slither/discussions
