### ISSUE TITLE
Error: Source file requires different compiler version

### ISSUE THREAD

**Issue by WarrenPanDDDD** [crytic/slither#1479]
### Describe the issue:

My project contains solidity files with version 0.5.16 and 0.8.3, i install solc like this:
`pip install solc-select
  solc-select install all
  solc-select use 0.5.16`

But if I `solc-select use 0.5.16`, it can't compile files with version 0.8.3

What should I do?

### Code example to reproduce the issue:

```
sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          pip install solc-select
          solc-select install all
          solc-select use 0.5.16
          python -m pip install --upgrade pip
          pip install slither-analyzer 
```

Run slither:
`slither ./contracts --json slither_output_${{steps.vars.outputs.sha_short}}.json --solc-remaps '@openzeppelin=node_modules/@openzeppelin openzeppelin-solidity=node_modules/openzeppelin-solidity'`

### Version:

latest

**Comment by elopez** [comment]
Hi @WarrenPanDDDD, are you using a compilation framework like hardhat? If so, consider using the project folder as the target instead; this will let the compilation framework handle things like mixed solc versions and remaps:

```
slither . --json slither_output_${{steps.vars.outputs.sha_short}}.json
```

**Comment by WarrenPanDDDD** [comment]
@elopez Great! Thank you so much, it save my day.
