### ISSUE TITLE
Exception: Ternary operation not handled

### ISSUE THREAD

**Issue by selimekim94** [crytic/slither#1490]
### Describe the issue:

Slither crashes when analyzing [this contract](https://etherscan.io/address/0x8214de517905Baa0b4b3ca06050AAD8fe31e460F#code)

   --> crytic-export/etherscan-contracts/0x8214de517905Baa0b4b3ca06050AAD8fe31e460F-TehRocket.sol:260:5:
    |
260 |     function min(uint256 a, uint256 b) private view returns (uint256){
    |     ^ (Relevant source part starts here and spans across multiple lines).

### Code example to reproduce the issue:

function min(uint256 a, uint256 b) private view returns (uint256){
      return (a>b)?b:a;
    }

### Version:

0.9.1

**Comment by 0xalpharush** [comment]
This is related to https://github.com/crytic/slither/pull/1217

**Comment by 0xalpharush** [comment]
Can you share the error message? I can run the 0.9.1 on this contract without any error and the ternary conversion in the IR looks fine to me at first glance. (I had previously commented but I was on a dev branch related to ternary and the issue is related to my modifications.)

**Comment by 0xPhaze** [comment]
```solidity
contract Contract {
    uint256 constant a = 1 < 3 ? 1 : 3;
}
```
throws
```
$ slither .
Exception: Ternary operator are not convertible to SlithIR if 1 < 3 then 1 else 3`
$ slither --version
0.9.1
```
