### ISSUE TITLE
slither is not recognized as a name 

### ISSUE THREAD

**Issue by Yasashari** [crytic/slither#1492]
I installed solc compiler and python. Then installed slither as given below ss. When i tried to run slither it gives me a this error.
slither is not recognized as a name of a cmdlet ,  function ............ 
![slither2](https://user-images.githubusercontent.com/118436384/205507166-823a6fea-69cc-46b9-9d3b-a9775b21ab04.PNG)
![slither1](https://user-images.githubusercontent.com/118436384/205507168-67e02881-4352-4d07-b1f7-20b7df0678c8.PNG)
How to fix this issue ? Thank you.

**Comment by elopez** [comment]
Hi @Yasashari, thanks for the report! This is not an issue with Slither itself, but a problem with your Python installation on Windows. This happens when the Python `Scripts` folder is not in the system PATH, and `pip` will warn you about it the first time you install the package. The easiest way to fix this is to (re)install Python and check the `Add Python to PATH` box in the installer, then reboot your computer.

**Comment by elopez** [comment]
Hi! did you reboot after installing Python so that Windows takes the new PATH definition? Can you check if both locations are added in the environment variables config? In your case, you should have both `C:\Python310` and `C:\Python310\Scripts` in PATH. You can refer to this article for guidance: https://www.makeuseof.com/python-windows-path/

**Comment by Yasashari** [comment]
Yes. I rebooted. 
But I corrected PATH and attached herewith. 
Reboot pc and still having same error.  slither is not recognized......... 


In system variable path is like this. so I haven't changed it.

![systemvar](https://user-images.githubusercontent.com/118436384/205557676-184ef213-415b-493c-a422-0bf97e5b4828.PNG)

I changed variable for my account only. after changing it like this

![sytemvar1](https://user-images.githubusercontent.com/118436384/205557860-f080dd5c-4ac0-40e5-8053-ca3764220d11.PNG)

Rebooted again still having same issue.

**Comment by Yasashari** [comment]
I uninstall slither . ss is attached herewith. 
![gitnew1](https://user-images.githubusercontent.com/118436384/205714307-be163832-2566-46b7-a495-b536e2c92c00.PNG)


After this I tried to install slither but now I cant install it. check ss below.

![gitnew2](https://user-images.githubusercontent.com/118436384/205714507-b0ceecb0-d26d-4989-be3b-ccea903b1ea7.PNG)

I run the python -m slither. output is like this. 
![gitnew3](https://user-images.githubusercontent.com/118436384/205714694-d69e431e-313e-4ff5-b55c-8bf202329616.PNG)

**Comment by elopez** [comment]
Your pip seems to have trouble installing it; pip is unable to write the executables correctly. This could be some eager antivirus/antimalware blocking it, or some permissions issue on the Scripts directory. I'd try installing with `--user` (`pip3 uninstall slither-analyzer` and `pip3 install slither-analyzer --user`) or running the installation on an elevated/admin console.

**Comment by Yasashari** [comment]
I run pip3 uninstall slither-analyzer--user 
then  pip3 install slither-analyzer--user  All ss given below. Finally I run  pip3 install slither-analyzer to check whether can install slither. 

![new one](https://user-images.githubusercontent.com/118436384/205812830-68109e61-cacd-426d-bc1b-1a2aa264d1c6.PNG)

**Comment by Yasashari** [comment]
I did it. but unfortunately not working slither . command.  check below ss.
![slit](https://user-images.githubusercontent.com/118436384/206374715-f540fb8c-e570-4cea-a5fc-700ec50c0c01.PNG)
Can you please tell me what I did wrong ? So far I realized is I need to install both python.exe and slither in same folder ? Then only slither will open. Can I find the installed slither folder and install python to that folder ?

**Comment by elopez** [comment]
You need to run the uninstall command before any new attempts to install it, otherwise pip will not attempt to reinstall the program and it'll remain "half-installed". Can you give that a try again?

```
pip3 uninstall slither-analyzer
pip3 install slither-analyzer --user
```

Also have you tried on an elevated console like the following? (right click cmd.exe and "run as admin", then attempt to install there)

```
pip3 uninstall slither-analyzer
pip3 install slither-analyzer
```

**Comment by Yasashari** [comment]
I run above commands. After that I run slither . Then output like this. 
![sl1](https://user-images.githubusercontent.com/118436384/206632853-8384d8dd-9b63-4c0e-80d9-995aaae9db8a.PNG)
![sl2](https://user-images.githubusercontent.com/118436384/206632884-0e6ca97a-5650-4dc9-9263-728c0fc8dd5c.PNG)

**Comment by elopez** [comment]
Good, you got slither running! Don't forget to `cd` to the correct directory that you want to analyze (e.g. your hardhat or foundry project, or a folder with `.sol` files) before running `slither .`

Also I see you don't have `solc` (the solidity compiler) installed, you might want to install [`solc-select`](https://github.com/crytic/solc-select) with pip the same way you did with `slither-analyzer` and then use that to install a solc compiler: e.g  `solc-select use 0.8.13 --always-install`

**Comment by Yasashari** [comment]
You're so helpful . Thanks for your support. I installed solidity complier.  I think now I'm able to run slither . But there is a problem.

When I log into command prompt with admin privilege , then this command works fine.  ( solc --version) 
![2](https://user-images.githubusercontent.com/118436384/206771961-aca24898-9084-4a6b-a19e-7f53b808a7ed.PNG)

My normal cmd path is different. solc --version command is not work there. see the ss below.
 

![1](https://user-images.githubusercontent.com/118436384/206772804-480c4ace-d043-4111-8ab1-370e6247a8c2.PNG)

Then I put a solidity file to  C:\Windows\system32 and run slither .  you can see the output below. 
![3](https://user-images.githubusercontent.com/118436384/206773466-57c365e4-3209-41bf-a9e4-345b9a8d313b.PNG)

I think slither is work fine. But i need to put sol files in to system32. How to fix this issue ? How to set environment  path variable. I add C:\Windows\system32 to path variable but not work. How to fix this ? 
![4](https://user-images.githubusercontent.com/118436384/206775088-3f4ee36a-3536-4cb5-94e6-494af955301e.PNG)

**Comment by elopez** [comment]
I think it is just a matter of solc-select's configuration being different for the admin user and your regular user. Try running `solc-select use 0.8.13 --always-install` again from a normal user terminal and see if that solves it.

**Comment by elopez** [comment]
I'll close this issue now but feel free to open a new one if you are still having issues.

**Comment by Yasashari** [comment]
Ok. Thanks your support.
