### ISSUE TITLE
Error while running slither

### ISSUE THREAD

**Issue by NoroMeb** [crytic/slither#1540]
Getting this error :

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte

while running `slither .` on the root of my brownie project .

have someone faced this error before and could handle it ?

ps : i have all dependencies installed successfully and brownie contracts compile with no probleme .

**Comment by 0xalpharush** [comment]
Can you post the full error message trace?

**Comment by NoroMeb** [comment]
@0xalpharush 

> Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\brownie.py", line 67, in compile
    stderr_bytes.decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte
Error in .
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\brownie.py", line 67, in compile
    stderr_bytes.decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte

**Comment by 0xalpharush** [comment]
@elopez Do you have an idea what could cause this?

**Comment by elopez** [comment]
maybe there's something non-utf8 in brownie's stderr? 🤔  I think Windows used some other encoding for the terminal output.

@NoroMeb would you mind opening a terminal, navigating to your project folder with `cd` and then running the following command and attaching the generated `stderr.bin` and `stdout.bin` files in this issue? They will contain a copy of whatever you see when you run `brownie compile` but in the exact binary representation that slither & crytic-compile receive:

```sh
python3 -c "import subprocess, shutil; stdout, stderr = subprocess.Popen(['brownie', 'compile'], executable=shutil.which('brownie'), stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate(); open('stdout.bin', 'wb').write(stdout); open('stderr.bin', 'wb').write(stderr)"
```

**Comment by NoroMeb** [comment]
@elopez i tried but I have an error that github don't support binary files, what can i do ?

**Comment by elopez** [comment]
I think you can create a zip file with them and upload that @NoroMeb

**Comment by NoroMeb** [comment]
[stderr.zip](https://github.com/crytic/slither/files/10360324/stderr.zip) @elopez

**Comment by elopez** [comment]
Thanks @NoroMeb!

@0xalpharush:

```
$ file *
stderr.bin: Non-ISO extended-ASCII text, with CRLF line terminators
stdout.bin: ASCII text, with CRLF line terminators
```

stdout is usual ASCII output:

```
Brownie v1.19.0 - Python development framework for Ethereum

Project has been compiled. Build artifacts saved at (...)
```

But stderr has this message (encoded in a DOS codepage, like https://en.wikipedia.org/wiki/Code_page_850) :

```
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
```

Maybe we could sprinkle all the "debug" decode calls [with ignore or backslashreplace](https://johnlekberg.com/blog/2020-04-03-codec-errors.html):

```python
% python3
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> x = open('stderr.bin', 'rb').read()
>>> print(x.decode())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 11: invalid start byte
>>> print(x.decode(errors="ignore"))
Information: impossible de trouver des fichiers pour le(s) mod?le(s) spcifi(s).

>>> print(x.decode(errors="backslashreplace"))
Information\xff: impossible de trouver des fichiers pour le(s) mod?le(s) sp\x82cifi\x82(s).

```

**Comment by 0xalpharush** [comment]
I think this makes sense as long as it doesn't cause errors to not surface
and cause weird behavior later in the program

**Comment by elopez** [comment]
I don't understand French much, but maybe the error message "Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s)." gives you a better idea of what the underlying problem is.

I opened a PR with a fix to not fail completely if the error message has unexpected text encoding, this should also alleviate the problem: https://github.com/crytic/crytic-compile/pull/351 If you want to try it out, you should be able to install the patched versions of Slither and crytic-compile as follows:

```
pip3 uninstall crytic-compile slither-analyzer
pip3 install https://github.com/crytic/slither/archive/refs/heads/dev.zip
pip3 uninstall crytic-compile
pip3 install https://github.com/crytic/crytic-compile/archive/refs/heads/dev-fix-error-decode.zip
```

**Comment by NoroMeb** [comment]
@elopez 
getting this error :

```
ERROR: HTTP error 404 while getting https://github.com/crytic/crytic-compile/archive/refs/heads/dev-fix-error-decode.zip
ERROR: Could not install requirement https://github.com/crytic/crytic-compile/archive/refs/heads/dev-fix-error-decode.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/crytic/crytic-compile/zip/refs/heads/dev-fix-error-decode for URL https://github.com/crytic/crytic-compile/archive/refs/heads/dev-fix-error-decode.zip
```

**Comment by elopez** [comment]
The PR got merged earlier today and the branch got deleted, so you got that error. You should be ok with just installing dev now:

```
pip3 uninstall crytic-compile slither-analyzer
pip3 install https://github.com/crytic/slither/archive/refs/heads/dev.zip
```

**Comment by NoroMeb** [comment]
Does it act like main branche ?
