### ISSUE TITLE
CI: install solc version only when needed

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1543]
Wen can remove `solc-select install all` for

- https://github.com/crytic/slither/blob/master/.github/workflows/detectors.yml#L38
- https://github.com/crytic/slither/blob/master/.github/workflows/features.yml#L38
- https://github.com/crytic/slither/blob/master/.github/workflows/ci.yml#L58
- https://github.com/crytic/slither/blob/master/.github/workflows/IR.yml#L37

So that the CI only install the solc versions that are needed. Related https://github.com/crytic/solc-select/issues/113

**Comment by Pavan-Nambi** [comment]
hey can i work on this? @montyly
