### ISSUE TITLE
Add informational detector for high cyclomatic complexity

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1591]
We should probably flag anything above 11 as risky for smart contracts (see https://en.wikipedia.org/wiki/Cyclomatic_complexity#Interpretation)

We already have a function that computes it: https://github.com/crytic/slither/blob/master/slither/utils/code_complexity.py#L64.

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/1618
