### ISSUE TITLE
[Bug]: immutable-state detector incorrectly claims strings can be made immutable

### ISSUE THREAD

**Issue by area** [crytic/slither#1595]
### Describe the issue:

According to the [solidity docs](https://docs.soliditylang.org/en/latest/contracts.html#constant-and-immutable-state-variables) while strings can be declared `constant`, they can not be declared `immutable` at this time. This detector, however, asks for strings to be declared `immutable` as if they were supported. Doing so causes the solidity compilation to fail.

### Code example to reproduce the issue:

```
pragma solidity 0.8.17;

contract X {
  bool public immutable boolVar;
  string public stringVar;


  constructor(bool _boolVar, string memory _stringVar) {
    boolVar = _boolVar;
    stringVar = _stringVar;
  }
}
```

### Version:

0.9.2

**Comment by 0xalpharush** [comment]
This wasn't accounted for when reusing the `_valid_type` helper function from the constant detector. Just need to filter out string types here https://github.com/crytic/slither/blob/4c976d5af56219eeef079e03a35009af3e03644d/slither/detectors/variables/unchanged_state_variables.py#L120-L123
