### ISSUE TITLE
[Slither Analysis]: Analysis failed for a contract having '@custom' tag in natspec

### ISSUE THREAD

**Issue by Aniket-Engg** [crytic/slither#1606]
### Describe the issue:

Analysis failed for a contract having '@custom' tag in natspec. Error says:

```
Error: Documentation tag @custom:dev-run-script not valid for contracts.
```

### Code example to reproduce the issue:
```

// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

/**
 * @title Storage
 * @dev Store & retrieve value in a variable
 * @custom:dev-run-script ./scripts/deploy_with_ethers.ts
 */
contract Storage {

    uint256 number;

    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retrieve() public view returns (uint256){
        return number;
    }
}
```

### Version:

0.9.2

**Comment by 0xalpharush** [comment]
I can't reproduce this with slither 0.9.2 and solc 0.8.17. What version of solc are you using? Perhaps it is not a slither error but one from the compiler?

**Comment by Aniket-Engg** [comment]
I am using Slither GIthub action from https://github.com/crytic/slither-action . Here is the failing PR: https://github.com/Aniket-Engg/remix-default-workspace/pull/1

**Comment by Aniket-Engg** [comment]
It seems working fine when I explicitly define the solc-version, It seems that default solc version is not set to latest

**Comment by elopez** [comment]
The Github action does an attempt at guessing what solidity compiler your code needs; in this case you have pragmas that say `pragma solidity >=0.7.0 <0.9.0;` so it installed and attempted to compile with solc 0.7.0. However the natspec `@custom:` tags support seems to have been [introduced in 0.8.2](https://github.com/ethereum/solidity/blob/develop/Changelog.md#082-2021-03-02).

If you can set `solc-version` manually and avoid the guesswork, that's better 😄

**Comment by Aniket-Engg** [comment]
Yes, got it. Thanks.
