### ISSUE TITLE
type propagation for library calls on type aliases isn't correct

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1607]
Thanks for implementing this feature, guys!

Unfortunately, we might have to re-open this issue. Slither doesn't work with chained function calls on value types:

```solidity
pragma solidity >=0.8.17;

import { UD60x18 } from "prb-math/UD60x18.sol";

contract Foo {
    function tryUnwrap(UD60x18 a, UD60x18 b) external pure returns (uint256 c, uint256 d) {
        // This is ok
        c = a.unwrap();
        // This triggers a bug
        d = a.mul(b).unwrap();
    }
}
```

Defining `c` works, but `d` doesn't. That is, I am getting the following error:

```text
Error:
Function not found on IR: TMP_3575(None) = HIGH_LEVEL_CALL, dest:TMP_3574(None), function:unwrap, arguments:[]  .
Node: EXPRESSION d = a.mul(b).unwrap() (src/Foo.sol#9)
Function: tryUnwrap
Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
```

I can attach the full stack trace but you should be able to replicate this by spinning up a Foundry project and installing [PRBMath](https://github.com/paulrberg/prb-math) (the latest commit from `main`).

_Originally posted by @PaulRBerg in https://github.com/crytic/slither/issues/1352#issuecomment-1384226469_

**Comment by PaulRBerg** [comment]
Sorry to follow up on this - I wonder if there is an ETA for the fix? Or is there any way I could help here (besides making a PR, as I am not familiar with the source code of Slither)?

Running a Slither check over our contracts is one of the last items on the todo list - we're prepping up for an audit.

**Comment by 0xalpharush** [comment]
I'm having some trouble replicating this. Would you create a repo where I can reproduce this issue please? I'm getting this error: 
```
Compiler run failed
error[9582]: TypeError: Member "unwrap" not found or not visible after argument-dependent lookup in UD60x18.
  --> src/Test.sol:10:13:
   |
10 |         d = a.mul(b).unwrap();
   |             ^^^^^^^^^^^^^^^

```

**Comment by PaulRBerg** [comment]
Forge installs the latest release tag (`v3.2.0` in the case of PRBMath) - you just have to edit the `branch` config option in your `.gitmodules` to point to `main`, and then update your git submodules.

I will go open an issue in the Foundry repo about this because tags cannot be used in the `branch` option.

**Comment by 0xalpharush** [comment]
Thanks for helping with this. I was able to reproduce the bug and will work on it this week

**Comment by PaulRBerg** [comment]
I thank you, ser.
