### ISSUE TITLE
staticcall reported reported by the dedector for low-level-calls

### ISSUE THREAD

**Issue by skimaharvey** [crytic/slither#1619]
### Describe the desired feature

`staticcall` by design do not modify the state of the chain, don't you think they should not be reported by the `low-level-calls` detector? 

If so, I can happily create a PR.

**Comment by 0xalpharush** [comment]
The detector flags these so users check that proper validation is performed e.g. make sure a contract is being staticcall'ed and not an EOA. Do you have an example of a false positive?

**Comment by skimaharvey** [comment]
okok I see then I misunderstood the `low-level-calls` detector and thought that low level calls with staticcalls are issueless since by essence they do not modify the state of the evm. 
Thanks for your quick reply though
