### ISSUE TITLE
Consider Solidity 0.8.17 valid for `IncorrectSolc`

### ISSUE THREAD

**Issue by CodeSandwich** [crytic/slither#1627]
### Describe the desired feature

Solidity 0.8.17 has been released 4 months ago, and it seems fine. It also fixes at least one known bug from 0.8.16, which is the only version of the 0.8 line tolerated by `IncorrectSolc`. Devs probably should be steered toward 0.8.17, it seems to be the best version now.

**Comment by thedavidmeister** [comment]
FYI inconsistency in docs and code it seems

<img width="886" alt="Screenshot 2023-03-21 at 13 36 04" src="https://user-images.githubusercontent.com/629710/226567122-330c7898-8ffd-45a6-a9b1-ccf76aaf5280.png">
<img width="419" alt="Screenshot 2023-03-21 at 13 36 16" src="https://user-images.githubusercontent.com/629710/226567171-121890f9-72c4-405c-afb9-212947ecb88b.png">

**Comment by montyly** [comment]
@thedavidmeister : good catch. I forgot to update the wiki with the release, but it's done now. 

@CodeSandwich: closing the issue, as the recommendation has been updated to 0.8.18 with the latest slither release
