### ISSUE TITLE
support for parsing solidity assembly .slot 

### ISSUE THREAD

**Issue by charlesxsh** [crytic/slither#1654]
### Describe the desired feature

```
contract XXX {
  mapping(address => uint256) private _counters;
  function xxxxxx() {
       assembly {
              mstore(xxx, _counters.slot)
          }
  }
}
```

Slither Output
```
slither.exceptions.SlitherException: unresolved reference to identifier _counters.slot
Error:
unresolved reference to identifier _counters.slot
```

When slither is paring the solidity code with interacting with storage slot, it throws the exception.

**Comment by duckki** [comment]
Maybe related: Referencing functions defined within a assembly block crashes slither with the same "unresolved reference to identifier" error.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.17;

contract A {

    function test() internal pure {
        assembly {
            function asm_fn1() {
                revert(0, 0)
            }

            function asm_fn2() {
                asm_fn1()
            }
        }
    }
}
```

Error:
```
File "slither/slither/solc_parsing/yul/parse_yul.py", line 819, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier asm_fn1
```

**Comment by simonbindefeld** [comment]
Am running into the same issue:

```solidity
  function getPackedBucketGlobalState(uint256 bucketId) internal view returns (uint256 packedGlobalState) {
        assembly {
            mstore(0x0, bucketId)
            mstore(0x20, _bucketGlobalState.slot)
            let slot := keccak256(0x0, 0x40)
            packedGlobalState := sload(slot)
        }
    }
```
  File "/opt/homebrew/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 847, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier _bucketGlobalState.slot
ERROR:root:Error:
ERROR:root:unresolved reference to identifier _bucketGlobalState.slot
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues

**Comment by 0xalpharush** [comment]
Similar fix as https://github.com/crytic/slither/pull/1085

**Comment by dokzai** [comment]
Hi!

I am interested in helping if issue is still open but I would like more information.

Is .slot parsing already handled by the function `_parse_yul_magic_suffixes()` in the PR 1085?

https://github.com/crytic/slither/blob/master/slither/solc_parsing/yul/parse_yul.py#L763-L770

**Comment by 0xalpharush** [comment]
You're right. The issue is bit more complex that I first thought. The underlying problem is that  `get_state_variable_from_name ` only searches accessible variables i.e. not private variables in inherited contracts. However, inherited internal functions in the derived contract can access their respective contract's private variables. So, we should probably change this to `root_function.contract_declarer.get_state_variable_from_name(potential_name)`.

https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/solc_parsing/yul/parse_yul.py#L751

Here's a an example that will reproduce the issue:
```
contract YYY {
mapping(address => uint256) private _counters;
  function _getPackedBucketGlobalState(uint256 bucketId) internal view returns (uint256 packedGlobalState) {
        assembly {
            mstore(0x0, bucketId)
            mstore(0x20, _counters.slot)
            let slot := keccak256(0x0, 0x40)
            packedGlobalState := sload(slot)
        }
    }
}  
contract XXX is YYY {
    function getPackedBucketGlobalState(uint256 bucketId) external {
        _getPackedBucketGlobalState(bucketId);
    }
}
```

**Comment by 0xalpharush** [comment]
@dokzai Did you want to open a branch with your fix? It would be appreciated
