### ISSUE TITLE
Pausable printer includes checks on constructor() 

### ISSUE THREAD

**Issue by devtooligan** [crytic/slither#1671]
### Describe the issue:

Slither printer issues dialog that it wont report on constructors `Constructor and pure/view functions are not displayed`, then it reports on constructors

When fixing this, we should also consider the desired behavior if there are no applicable  functions in a contract.  Skip the contract all together, or list it with nothing beneath or `n/a` or something

This ticket could be completed along with #1670

```bash 
$ slither ./demo/test.sol --print pausable

Constructor and pure/view functions are not displayed

Zero:
+---------------+-------------------+
|      Name     | Use whenNotPaused |
+---------------+-------------------+
| constructor() |                   |
+---------------+-------------------+

One:
+---------------+-------------------+
|      Name     | Use whenNotPaused |
+---------------+-------------------+
| constructor() |                   |
+---------------+-------------------+

Two:
+---------------+-------------------+
|      Name     | Use whenNotPaused |
+---------------+-------------------+
| constructor() |                   |
+---------------+-------------------+

Test:
+----------------+-------------------+
|      Name      | Use whenNotPaused |
+----------------+-------------------+
| constructor()  |                   |
|     test()     |                   |
| test2(uint256) |                   |
| test3(uint256) |                   |
|    test4()     |                   |
+----------------+-------------------+


### Code example to reproduce the issue:

see above

### Version:

0.9.2

### Relevant log output:

_No response_

**Comment by aga7hokakological** [comment]
I would like to take this issue if no one is working. Also as mentioned that #1670 needs to be completed along with this. In #1670 I just need to change the argument name right?

**Comment by 0xalpharush** [comment]
@aga7hokakological All yours! It'd be awesome if you submitted one PR each for this issue and #1670. Feel free to ask any questions here

**Comment by aga7hokakological** [comment]
> We need to add a check that like `not function.is_constructor` here
> 
> https://github.com/crytic/slither/blob/64b2e0c063cf93fb479481abc432371404629f32/slither/printers/summary/when_not_paused.py#L48
> 
So the check is already there in 
> https://github.com/crytic/slither/blob/master/slither/printers/summary/when_not_paused.py#L13
>
I just moved this line in the above block and used continue keyword instead of False. It seems to work for 
`Constructor and pure/view functions are not displayed` this line now. That means it doesn't show the pure/view/constructor while printing but now it is not printing X for not paused. Working on that
