### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1693]
The next release will happen between March 6th - March 17.

Current todo list:

To be reviewed and merged:
- https://github.com/crytic/slither/pull/1679
- https://github.com/crytic/slither/pull/1625
- https://github.com/crytic/slither/pull/1690
- https://github.com/crytic/slither/pull/1691

To be discussed:
- https://github.com/crytic/slither/pull/1643
- https://github.com/crytic/slither/pull/1692
- https://github.com/crytic/slither/issues/1251#issuecomment-1440624207 - update the detector

Might wait for the next release;
- If we merge https://github.com/crytic/slither/pull/1666 (including #1672/#1673/#1674)
- https://github.com/crytic/slither/pull/1684

Let us know if there is anything that should be included and is not listed here

**Comment by 0xalpharush** [comment]
I think this can be included https://github.com/crytic/slither/pull/1510
