### ISSUE TITLE
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "node_modules/@openzeppelin/contracts/utils/cryptography/ECDSA.sol" not found: File not found. Searched the following locations: "".[Bug-Candidate]: 

### ISSUE THREAD

**Issue by joedakwa** [crytic/slither#1698]
### Describe the issue:

Hi, i am trying to run this command from my directory:

 when i run slither CTTXForwarder.sol --solc-remaps @openzeppelin/contracts/=node_modules/@openzeppelin/contracts/
 
I get this error 

crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "node_modules/@openzeppelin/contracts/utils/cryptography/ECDSA.sol" not found: File not found. Searched the following locations: "".[Bug-Candidate]: 

In my remappings file, i have this:

```
{
    "remappings": [ 
        "@openzeppelin/contracts/security/=node_modules/@openzeppelin/contracts/security/",
        "@openzeppelin/contracts/access/=node_modules/@openzeppelin/contracts/access/",
        "@openzeppelin/contracts/token/=node_modules/@openzeppelin/contracts/token/",
        "@openzeppelin/contracts/utils/cryptography/=node_modules/@openzeppelin/contracts/utils/cryptography/"
    ]
}
```

Can someone assist me with this?

When i run Slither . this works fine. But then i want to be able to run 

```Slither CTTXForwarder -- print call-graph```

for example.

### Code example to reproduce the issue:

```Slither CTTXForwarder -- print call-graph```

### Version:

0.9.2

**Comment by joedakwa** [comment]
> This is a current limitation of slither that doesn't have a workaround at the moment. We plan to add the ability to filter the output of slither by contract #759 like `slither . --filter-contract CTTXForwarder --print call-graph`.

Right i see thanks.

One more question; am i able to run slither against specific functions in my contract? If so, how?

**Comment by 0xalpharush** [comment]
@joedakwa No but that is within the scope of improvements planned in #759

**Comment by joedakwa** [comment]
> @joedakwa No but that is within the scope of improvements planned in #759

right ok cool should be very helpful when that is released, as can run --print-graph on specific functions :-)

**Comment by 0xalpharush** [comment]
Closing this but it's being tracked!
