### ISSUE TITLE
data dependency of named return SSA variables

### ISSUE THREAD

**Issue by Troublor** [crytic/slither#1719]
### Describe the desired feature

Given a simple function with named return variable like this:
```
contract A {
    uint a = 1;
    function foo(uint x) public returns (uint y) {
        if (x > 0) 
            y = x;
        else
            y = x + a;
    }
}
```
In the SSA SlithIR, the return variable (i.e., `returns_ssa` field of the function object) is `y_0`, and the variable being assigned in the statement `y=x` and `y=x+a` is `y_1` and `y_2`. 
There is no assignment for the return variable `y_0`, resulting that there is no data dependency of the return variable `y_0`. 
This poses a difficulty in analyzing the data dependencies of function returns using SSA. 

One possible enhancement is do a control flow analysis and find last assignment to variable `y` in all possible paths and add a PHI operation at the end of the function, e.g., `y_0 = phi[y_1, y_2]`.

**Comment by 0xalpharush** [comment]
I believe this is fixed in https://github.com/crytic/slither/pull/1102 but it requires more testing. Something helpful to know: there's also a limitation that a return node is not created for `y` https://github.com/crytic/slither/issues/1450.

**Comment by bsamuels453** [comment]
#1715 related

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/2326
