### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by galactictourist** [crytic/slither#1746]
### Describe the issue:

Tried every way I can find to install slither -- currently using the second option on the dev install page however in any case if I try to use read storage I am told to install web3 - I have done that several times - uninstalled - reinstalled - completely ripped out all python and reinstalled tried everything again and no matter what I do I cannot get slither to recognize my web3 install. If I run pip list - it's there. 

(slither-dev) iMac:slither sovryn73$ slither-read-storage bsc:0xa1faa113cbE53436Df28FF0aEe54275c13B40975 --json storage_layout.json --rpc-url https://bsc-mainnet-rpc.allthatnode.com 
ERROR: in order to use slither-read-storage, you need to install web3
$ pip3 install web3 --user

### Code example to reproduce the issue:

(slither-dev) iMac:slither sovryn73$ slither-read-storage bsc:0xa1faa113cbE53436Df28FF0aEe54275c13B40975 --json storage_layout.json --rpc-url https://bsc-mainnet-rpc.allthatnode.com 
ERROR: in order to use slither-read-storage, you need to install web3
$ pip3 install web3 --user

### Version:

0.9.2

**Comment by 0xalpharush** [comment]
I replied to your issue here https://github.com/crytic/slither/discussions/1747.
If it helps, here's the output for the command you gave: 
```
{
    "_balances": {
        "name": "_balances",
        "type_string": "mapping(address => uint256)",
        "slot": 0,
        "size": 256,
        "offset": 0,
        "value": 0,
        "elems": {}
    },
    "_allowances": {
        "name": "_allowances",
        "type_string": "mapping(address => mapping(address => uint256))",
        "slot": 1,
        "size": 256,
        "offset": 0,
        "value": 0,
        "elems": {}
    },
    "_totalSupply": {
        "name": "_totalSupply",
        "type_string": "uint256",
        "slot": 2,
        "size": 256,
        "offset": 0,
        "value": 1000000000000000000000000000,
        "elems": {}
    },
    "_name": {
        "name": "_name",
        "type_string": "string",
        "slot": 3,
        "size": 256,
        "offset": 0,
        "value": "AlphaToken",
        "elems": {}
    },
    "_symbol": {
        "name": "_symbol",
        "type_string": "string",
        "slot": 4,
        "size": 256,
        "offset": 0,
        "value": "ALPHA",
        "elems": {}
    },
    "_decimals": {
        "name": "_decimals",
        "type_string": "uint8",
        "slot": 5,
        "size": 8,
        "offset": 0,
        "value": 18,
        "elems": {}
    },
    "_owner": {
        "name": "_owner",
        "type_string": "address",
        "slot": 5,
        "size": 160,
        "offset": 8,
        "value": "0x4F992a6d8532eB9AF589E47F5b6Fea30E7e203B4",
        "elems": {}
    }
}
```

**Comment by maxcoto** [comment]
I have this same problem with python 3.9 and 3.10 too.
slither version 0.9.2

```
slither-read-storage 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8
ERROR: in order to use slither-read-storage, you need to install web3
$ pip3 install web3 --user
```

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/1743
