### ISSUE TITLE
`data_dependency.get_dependencies` fails for TransparentUpgradeableProxy `implementation` LocalVariable

### ISSUE THREAD

**Issue by webthethird** [crytic/slither#1819]
### Describe the issue:

`data_dependency.get_dependencies` fails to find the data source for the `implementation` LocalVariable in [TransparentUpgradeableProxy.sol](https://github.com/webthethird/slither/blob/dev-upgradeability-utils/tests/unit/utils/test_data/upgradeability_util/src/TransparentUpgradeableProxy.sol).

`implementation` is declared in the signature of `_delegate(address implementation)` in the base Proxy contract. Calling `get_dependencies(implementation, proxy)` with this LocalVariable, only a TemporaryVariable is returned, representing the return value of `_implementation()` in the expression `_delegate(_implementation())`.  The data dependency tool should recognize that `_implementation()` is overridden in the `UpgradeableProxy` contract, which returns a local variable called `impl`, which in turn depends on the local variable `slot` which equals the state variable `_IMPLEMENTATION_SLOT`.

Perhaps `get_dependencies` is failing because of the unimplemented `_implementation()` function in the base Proxy contract. However, given that the contract I am passing in as the `context` argument is the TransparentUpgradeableProxy, it should ignore the unimplemented function and use the one implemented in UpgradeableProxy instead.

This is causing issues with the `get_implementation_slot` function in my `slither.utils.upgradeability` utility. See #1818 for a pytest test to reproduce the issue.

### Code example to reproduce the issue:

https://github.com/crytic/slither/pull/1818
https://github.com/webthethird/slither/blob/dev-upgradeability-utils/tests/unit/utils/test_data/upgradeability_util/src/TransparentUpgradeableProxy.sol

### Version:

0.9.3

**Comment by 0xalpharush** [comment]
Going to track this in https://github.com/crytic/slither/issues/1719
