### ISSUE TITLE
[Bug-Candidate]: Incorrect type hint in Member, Index, Binary, and other IR operations

### ISSUE THREAD

**Issue by Troublor** [crytic/slither#1830]
### Describe the issue:

In slither version `0.9.3`, it seems the type hint of variable fields in some IR operation class is changed to `SourceMapping`. 
For example, https://github.com/crytic/slither/blob/0ec487460690482c72cacdea6705e2c51bb3981e/slither/slithir/operations/member.py#L53
https://github.com/crytic/slither/blob/0ec487460690482c72cacdea6705e2c51bb3981e/slither/slithir/operations/index.py#L43
https://github.com/crytic/slither/blob/0ec487460690482c72cacdea6705e2c51bb3981e/slither/slithir/operations/binary.py#L137
These are just three examples in three operation class. 
There could be other places with wrong type hint and I didn't enumerate all of them. 

I believe this is a regression issue. 
Before `0.9.3`, the type hint was some class related to `Variable`. 

Upgrading to `0.9.3` breaks all the type check in my program, which is a downstream tool using of slithIR. 

Is this a breaking change? It seems not to me. The type of these variable (e.g., `left_variable`) being `SourceMapping` makes no sense to me. 

### Code example to reproduce the issue:

N/A

### Version:

0.9.3

### Relevant log output:

```shell
N/A
```

**Comment by 0xalpharush** [comment]
I think the release only contained partial updates to the typing and further improvement were merged after the release. You may want to use `dev` to reflect the changes from https://github.com/crytic/slither/pull/1666

**Comment by Troublor** [comment]
> I think the release only contained partial updates to the typing and further improvement were merged after the release. You may want to use `dev` to reflect the changes from #1666

I see. Thx.
So there are some bad unexpected changes to the type hint in the 0.9.3 release, and they have been fixed in the `dev` branch. 
OK, so this is no longer an issue. 
It is really a pain in the ass to have incorrect type hints in the released version, though. 🫠

**Comment by Troublor** [comment]
Should be fixed in https://github.com/crytic/slither/pull/1666
