### ISSUE TITLE
version 0.6.8 Slither.context attribute different from version 0.9.3

### ISSUE THREAD

**Issue by DarrenChangJR** [crytic/slither#1836]
I'm updating a codebase that depended on slither Version: 0.6.8, where
`slither_obj.context`
returns the dictionary
```
{'DATA_DEPENDENCY_INPUT': {<slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde5727400>, <slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde5727240>, <slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde5727a90>, <slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde57278d0>, <slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde5727710>, <slither.solc_parsing.variables.local_variable.LocalVariableSolc object at 0x7efde57275c0>}, 'DATA_DEPENDENCY_INPUT_SSA': {<slither.slithir.variables.local_variable.LocalIRVariable object at 0x7efe689e15c0>, <slither.slithir.variables.local_variable.LocalIRVariable object at 0x7efe689e15f8>}}
```
. But it seems in that in the later versions, (using Version: 0.9.3), the `slither_obj.context` simply contains
`{'MEMBERS': defaultdict(None, {})}`.

I am aware that the LocalVariableSolc (along with many other classes) now have updated names in the later versions.

Note that this context attribute is different from the ones of individual functions, as `slither_obj.contracts[0].functions[0].context` still contains
```
{'DATA_DEPENDENCY_SSA': {}, 'DATA_DEPENDENCY_SSA_UNPROTECTED': {}, 'DATA_DEPENDENCY': {}, 'DATA_DEPENDENCY_UNPROTECTED': {}}
```

Has the use of Slither.context been deprecated? If so, what can I use to substitute it with, particularly for accessing the DATA_DEPENDENCY_INPUT?

Sorry if my questions are unclear or do not meet community requirements, I'm new to open-sourcing, please let me know if my question can be improved.

**Comment by 0xalpharush** [comment]
Hi @DarrenChangJR, your questions are welcome! I believe you can update the section of code [here](https://github.com/DarrenChangJR/sailfish/commit/206a3aa0019ea73c81c47a944a875af879157e48) from `function.slither.context` to `function.compilation_unit.context` to reflect the changes made in https://github.com/crytic/slither/pull/823/files#diff-92fd39fdf5829aabe2d4f6fc4932b2f5096fcff18cd121a8d185f12d36bdf8d7L107-R111. Let me know if that doesn't work please

**Comment by DarrenChangJR** [comment]
That worked great! Thanks for the help and link to the changes.
