### ISSUE TITLE
[False-Positive]: Slither recognizes the contract as a locking ether contract.

### ISSUE THREAD

**Issue by noushkia** [crytic/slither#1838]
### Describe the false alarm that Slither raise and how you know it's inaccurate:

I was checking the Pair.sol contract using slither.
The first Medium threat issue found by Slither was that the contract locked ethers received from payable functions.

I believe this is wrong since the contract has a sell function where it transfers ether and other tokens using safeTransfer calls:
```
        if (baseToken == address(0)) {
            // transfer ether out
            msg.sender.safeTransferETH(outputAmount);
        } else {
            // transfer base tokens out
            ERC20(baseToken).safeTransfer(msg.sender, outputAmount);
        }
```

P.S.: The issue was submitted in 2019 (https://github.com/crytic/slither/issues/163). But I think it isn't resolved yet.

### Frequency

Very Frequently

### Code example to reproduce the issue:

https://github.com/code-423n4/2022-12-caviar/blob/0212f9dc3b6a418803dbfacda0e340e059b8aae2/src/Pair.sol

### Version:

0.9.3

### Relevant log output:

```shell
Contract locking ether found:
	Contract Pair (src/Pair.sol#16-482) has payable functions:
	 - Pair.add(uint256,uint256,uint256) (src/Pair.sol#63-99)
	 - Pair.buy(uint256,uint256) (src/Pair.sol#147-176)
	 - Pair.nftAdd(uint256,uint256[],uint256,bytes32[][]) (src/Pair.sol#275-286)
	 - Pair.nftBuy(uint256[],uint256) (src/Pair.sol#310-316)
	But does not have a function to withdraw the ether
```

**Comment by 0xalpharush** [comment]
Thanks for reporting this! This is a limitation outlined in https://github.com/crytic/slither/issues/1686 that we will address

**Comment by 0xalpharush** [comment]
Tracking in https://github.com/crytic/slither/issues/1686
