### ISSUE TITLE
erc20-interface: remove FP in case of other ERC implementations

### ISSUE THREAD

**Issue by montyly** [crytic/slither#186]
The `erc20-interface` detector will return FP if an ERC closes to ERC20 is implemented.

We should identify what ERCs are affected and add their support.

**Comment by Xenomega** [comment]
For reference: Each of the contracts referenced at https://github.com/trailofbits/smart-contracts-detectors-testing/issues/2 do not properly implement ERC721, or functions typically provided via ERC20 for backward compatibility. ERC721 is supposed to imply ERC165, but often does not as well.

- `DungeonCoreBeta`:
  - ERC721 implementations: `ownerOf`
  - ERC20 implementations: `totalSupply`, `balanceOf` and `transfer`
  - ERC165 implementation: `<none>`

- `HeroGateway`:
  - ERC721 implementations: `ownerOf`, `getApproved`, `setApprovalForAll`, `isApprovedForAll`, `safeTransferFrom` (both overloads)
  - ERC20 implementations: `balanceOf`, `approve`, `transferFrom`
  - ERC165 implementation: `supportsInterface`

- `KittyCore`:
  - ERC721 implementations: `ownerOf`
  - ERC20 implementations: `totalSupply`, `balanceOf`, `approve`, `transfer`, `transferFrom`
  - ERC165 implementation: `supportsInterface`

Despite this inconsistent implementation, we can filter out results by checking if any of the ERC721 functions exist. Although all of these functions share `ownerOf` in common, we cannot be sure that some ERC721 token implements other functions, but not this one.
