### ISSUE TITLE
Slither does not handle non-default Truffle build folders

### ISSUE THREAD

**Issue by Pneumaticat** [crytic/slither#187]
As seen in https://github.com/crytic/slither/blob/0891f9a8a5e5e096084476e4b2bd292c3685f251/slither/slither.py#L61-L64, it hardcodes the default directory for Truffle: `build/contracts`.

However, this location can actually be customized; see https://truffleframework.com/docs/truffle/reference/configuration#contracts_build_directory.

I may try to submit a PR if I can find time this week.

**Comment by montyly** [comment]
That's a good idea, thank you for reporting the limitation!

**Comment by montyly** [comment]
Hi @Pneumaticat , I added the option `--truffle-build-directory` to specify a custom build path.

You can also set the option directly in slither [config file](https://github.com/crytic/slither/wiki/Usage#configuration-file), if you don't want to specify the flag at every run. Example of config:
```
$ cat slither.config.json 
{
    "truffle_build_directory":"custom/build_dir"
}
```

Note that Slither could parse the information directly from `truffle.js`, but I used a solution that does not require JS parsing. 

This feature will be present in the upcomig 0.6.2 release.

**Comment by Pneumaticat** [comment]
Awesome! Thanks ;)
