### ISSUE TITLE
[Bug]: AttributeError: 'float' object has no attribute 'startswith' in integer_conversion.py

### ISSUE THREAD

**Issue by duckki** [crytic/slither#1870]
### Describe the issue:

Slither AST parser crashes with the following error.

```
  File "<slither>/slither/utils/integer_conversion.py", line 10, in convert_string_to_fraction
    if val.startswith(("0x", "0X")):
AttributeError: 'float' object has no attribute 'startswith'
```

### Code example to reproduce the issue:

Etherscan address: 0x77372a4cc66063575b05b44481f059be356964a4

Code:
```solidity
    function getInformations() external view returns (string memory,uint256[(MAX_TOKENS/MAX_EACH_TYPE) + 1] memory,uint256[(MAX_TOKENS/MAX_EACH_TYPE) + 1] memory, uint, uint,uint,uint, bool,bool)
    {
        uint256[(MAX_TOKENS/MAX_EACH_TYPE) + 1] memory tokenIdsMale;
        uint256[(MAX_TOKENS/MAX_EACH_TYPE) + 1] memory tokenIdsFemale;

        for (uint256 i = 1; i <= (MAX_TOKENS/MAX_EACH_TYPE); i++) {
            tokenIdsMale[i] = Supply[i].Male;
            tokenIdsFemale[i] = Supply[i].Female;
        }
        return (CURR_ROUND_NAME, tokenIdsMale,tokenIdsFemale, CURR_ROUND_TIME,CURR_MINT_COST,nftPerAddressLimit, totalSupply(), hasSaleStarted, onlyBeastListed);
    }
```

The `MAX_TOKENS/MAX_EACH_TYPE` expression is constant-propagated as a Literal that has a Python float value `20.0`, which is unexpected by the `convert_string_to_fraction` function.

### Version:

0.9.3

**Comment by 0xalpharush** [comment]
I can't seem to reproduce this on `dev` but I'm not sure that we made changes that would have fixed this... @elopez do you have any idea?

**Comment by elopez** [comment]
@0xalpharush maybe this got fixed in the work done to add types to the code? the integer_conversion code hasn't changed lately, but I see several changes in the folding code:

```
git diff  0.9.3..origin/dev -- slither/visitors/expression/constants_folding.py
```

Other than that, I don't recall any specific PR targeting this.

**Comment by 0xalpharush** [comment]
Closing this for now
