### ISSUE TITLE
slither-check-upgradability: warning if constant are used

### ISSUE THREAD

**Issue by montyly** [crytic/slither#188]
In the case of delegatecall proxy pattern, constant should be avoided, as they can create issues during upgrade.

slither-check-upgradability should warn if constant variables are present.

We should also add a note about it in the `constable-states` detector description

**Comment by EricR** [comment]
After talking with @montyly, this is to be composed of:
- Look for duplicate const identifiers in the proxy and implementations (v1 and v2)
- Check if in going from v1 to v2, a storage variable has changed to a constant
