### ISSUE TITLE
[False-Positive]: `unused-state` should not apply to abstract contracts

### ISSUE THREAD

**Issue by PaulRBerg** [crytic/slither#1885]
### Describe the false alarm that Slither raise and how you know it's inaccurate:

This issue is analogous to #1883 and #1884, but it is about `unused-state`.

The `unused-state` detector should not apply to constants defined in abstract contracts. As an example, let's look at the constants in my base script in PRBProxy:

https://github.com/PaulRBerg/prb-proxy/blob/0021babcc102e773ed2d6f67a937b1e368459cf7/script/shared/Base.s.sol#L6C1-L11

It does not make sense for Slither to complain that `ZERO_SALT` is unused, but it does:

https://github.com/PaulRBerg/prb-proxy/security/code-scanning/50

### Frequency

Very Frequently

### Code example to reproduce the issue:

https://github.com/PaulRBerg/prb-proxy/blob/0021babcc102e773ed2d6f67a937b1e368459cf7/script/shared/Base.s.sol

### Version:

v0.9.3

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/1952
