### ISSUE TITLE
Create slither-interface

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1893]
See https://github.com/crytic/slither/pull/1802#issuecomment-1525717360

**Comment by 0xGusMcCrae** [comment]
I'll take a look at this over the weekend and see if I can get it done

**Comment by montyly** [comment]
That's great @0xGusMcCrae, let me know if you need guidance or help. 

Some notes:
- We can build `slither-interface` following the tool's demo structure: https://github.com/crytic/slither/tree/master/slither/tools/demo
- Most the logic might already be implemented in `slither/utils/code_generation.py`
- We recently made a significant refactor of our testing strategies. Be sure to work from the `dev` branch, and read https://github.com/crytic/slither/blob/dev/CONTRIBUTING.md

**Comment by 0xGusMcCrae** [comment]
I've got the basic functionality down.  I just need to write some tests and I should have a PR ready tomorrow.

For the output, do we want to print the interface in the console and allow users to write to file manually? 

i.e. `slither-interface WETH9 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 >> IWeth9.sol`

Or should it write to file by default? Maybe a flag so there's an option between the two?

**Comment by montyly** [comment]
Awesome. I think a file is probably more appropriate. 

Most of our tools use `crytic-export/name_tool/contract`, maybe we can do `crytic-export/interfaces/ContractA.sol`, `crytic-export/interfaces/ContractB.sol`, ... by default?
