### ISSUE TITLE
Filenames prefixed with hashtag when using environment variables. 

### ISSUE THREAD

**Issue by Murat-U-Saglam** [crytic/slither#1897]
I was just trying to set up some automated local testing utilising the trail of bits/slither:latest docker container. 

When passing environment variables to my docker-compose I get the following error. 

Docker compose
`command: sh -c "slither ${CONTRACT_NAME}.sol"`

Terminal output
```
slither_1  | ERROR:root:Error in TheRun.sol
slither_1  | ERROR:root:Traceback (most recent call last):
slither_1  |   File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/__main__.py", line 586, in main_impl
slither_1  |     raise Exception("Unrecognised file/dir path: '#{filename}'".format(filename=filename))
slither_1  | Exception: Unrecognised file/dir path: '#TheRun.sol'
```

However, when i pass the file name within docker-compose there is no issue and it executes slither correct
`command: sh -c "slither theRun.sol"`

Terminal Output
`slither_1  | INFO:Slither:theRun.sol analyzed (1 contracts), 42 result(s) found`

I am exporting the environment variables as follows:
`export CONTRACT_NAME='TheRun'`

Is there a reason why when passing environment variables to slither it prefixes the search with a hashtag thus not finding the file?

**Comment by elopez** [comment]
Hi, thanks for the report! I see that you are using a very old Slither version (0.6.1). Would you mind re-testing with the latest release and reporting back if it is still an issue? If you need up to date docker images, we now publish them on the GitHub Container Registry: https://github.com/crytic/slither/pkgs/container/slither

**Comment by Murat-U-Saglam** [comment]
Hi,

I've retested with the updated docker container. Outlined below is the docker-compose used.

```
version: "3.9"

services:
  slither:
    image: ghcr.io/crytic/slither:testing-dev
    volumes:
      - .:/slither
    working_dir: /slither
    command: sh -c "slither ${CONTRACT_NAME}.sol"
```
And it still does not resolve the smart contract. 

`slither_1  | ValueError: Unresolved target: TheRun.sol`

When importing the name of the smart contract directly it works as intended.

**Comment by elopez** [comment]
I'm not able to reproduce this locally, see below. Are you doing anything differently on your environment?

```
emilio@mbpro compose % grep -Hr . .
./TheRun.sol:contract C {}
./.env:CONTRACT_NAME=TheRun
./docker-compose.yml:version: "3.9"
./docker-compose.yml:services:
./docker-compose.yml:  slither:
./docker-compose.yml:    image: ghcr.io/crytic/slither:testing-dev
./docker-compose.yml:    volumes:
./docker-compose.yml:      - .:/slither
./docker-compose.yml:    working_dir: /slither
./docker-compose.yml:    command: sh -c "slither ${CONTRACT_NAME}.sol"
emilio@mbpro compose % docker-compose up                     
[+] Running 1/0
 ⠿ Container compose-slither-1  Created                                                                                                                                                                                                                             0.0s
Attaching to compose-slither-1
compose-slither-1  | Compilation warnings/errors on TheRun.sol:
compose-slither-1  | TheRun.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.25;"
compose-slither-1  | contract C {}
compose-slither-1  | ^ (Relevant source part starts here and spans across multiple lines).
compose-slither-1  | 
compose-slither-1  | INFO:Detectors:
compose-slither-1  | solc-0.4.25 is not recommended for deployment
compose-slither-1  | Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
compose-slither-1  | INFO:Slither:TheRun.sol analyzed (1 contracts with 85 detectors), 1 result(s) found
compose-slither-1 exited with code 255
```
