### ISSUE TITLE
[Bug]: Type of tuple result of ABI-decode contains instances of Structure

### ISSUE THREAD

**Issue by kevinclancy** [crytic/slither#1922]
### Describe the issue:

When the `abi.decode` function decodes a struct along with one or more other values, the type of the tuple on the left-hand side contains an instance of `Structure`, but I expect the tuple variables's `type` field to contain only instances of `Types`.

Instead of containing a `Structure` instance, the list should contain a `UserDefinedType` instance whose `type` field is a `Structure` instance.

### Code example to reproduce the issue:

```
pragma solidity =0.8.19;

contract StructTest {
    struct Detail {
        int x;
        int y;
    }

    function test(bytes calldata orderData) external {
        (int z, Detail memory testDetail) = abi.decode(orderData, (int, Detail));
        testDetail.x = 1;
    }

}
```

### Version:

0.9.3

### Relevant log output:

```
INFO:Printers:Contract StructTest
        Function StructTest.test(bytes) (*)
                Expression: (z,testDetail) = abi.decode(orderData,(int256,Detail))
                IRs:
                        TUPLE_0(int256,Detail) = SOLIDITY_CALL abi.decode()(orderData(int256,Detail))
                        z(int256)= UNPACK TUPLE_0 index: 0 
                        testDetail(StructTest.Detail)= UNPACK TUPLE_0 index: 1 
                Expression: testDetail.x = 1
                IRs:
                        REF_1(int256) -> testDetail.x
                        REF_1 (->testDetail) := 1(int256)
```

**Comment by 0xalpharush** [comment]
Probably related to this conversion https://github.com/crytic/slither/blob/0632751cc585d4c91f132d1597a4266d4db0ee3e/slither/slithir/convert.py#L1215-L1227

**Comment by kevinclancy** [comment]
Yes, it looks like singletons are handled correctly and lists of types should be handled using the same logic.
