### ISSUE TITLE
[Bug]: type error in IR generated for type(X).min where X is an enum type

### ISSUE THREAD

**Issue by kevinclancy** [crytic/slither#1930]
### Describe the issue:

When slither generates code for `type(X).min` where `X` is an enum type, the temporary variable has type `uint256` instead of `X`. If we assign some variable of type `X` to `type(X).min`, the lvalue and rvalue have different types.

### Code example to reproduce the issue:

```
contract Test {
    enum E {
        A,
        B
    }

    function test() external {
        E e = type(E).min;
    }
}
```

### Version:

0.9.3

### Relevant log output:

```
INFO:Printers:Contract Test
        Function Test.test() (*)
                Expression: e = type()(E).min
                IRs:
                        TMP_0(type(E)) = SOLIDITY_CALL type()(E)
                        TMP_1(uint256) := 0(uint256)
                        e(Test.E) := TMP_1(uint256)
```

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/2051
