### ISSUE TITLE
[False Negative]: Lack of reentrancy warning for `_safeMint`

### ISSUE THREAD

**Issue by 0xmichalis** [crytic/slither#1941]
### What bug did Slither miss and which detector did you anticipate would catch it?

`_safeMint` gives control back to the caller who can execute arbitrary external calls. Although `mint` itself cannot be re-entered in the example contract provided, other functions of the same contract or other contracts may be vulnerable if they depend on `claimed` (or any other state that is yet to be updated after `_safeMint` is executed). I'd expect Slither to trigger a `reentrancy-no-eth` warning, applying the [`check-effects-interactions pattern`](http://solidity.readthedocs.io/en/v0.4.21/security-considerations.html#re-entrancy) would resolve such potential issues.

### Frequency

Very Frequently

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import '@openzeppelin/contracts/token/ERC721/ERC721.sol';
import '@openzeppelin/contracts/security/ReentrancyGuard.sol';

contract Token is ERC721, ReentrancyGuard {
    uint256 internal _tokenIds;
    mapping(uint256 => bool) public claimedIds;

    constructor() ERC721('Toucan Token', 'TCT') {}

    function mint(
        uint256 id
    ) external virtual nonReentrant returns (uint256) {
       
        uint256 newItemId = _tokenIds;
        unchecked {
            ++newItemId;
        }

       _safeMint(msg.sender, newItemId);

       claimedIds[id] = true;
       _tokenIds = newItemId;

        return newItemId;
    }
}
```

### Version:

0.8.3

**Comment by 0xalpharush** [comment]
I think upgrading to at least 0.9.2 will work this. Using the latest version is usually ideal.
