### ISSUE TITLE
Upgrade slither version easily 

### ISSUE THREAD

**Issue by 0xKarl98** [crytic/slither#1953]
### Describe the desired feature

Currently we only have "how to install" section for slither , but don't have "how to uninstall" as well as "how to upgrade "sections for it .

Consider to add some guides regarding of it .

**Comment by 0xalpharush** [comment]
Good idea! 
Uninstall `pip uninstall slither-analyzer`
Upgrade `pip install slither-analyzer --upgrade`

**Comment by 0xKarl98** [comment]
hi , my current version is of 0.8.3
and i use pip install slither-analyzer --upgrade to install the version of
0.9.3
by pip show slither-analyzer , it has installed but not activated ,
since slither --version outputs 0.8.3
how can i activate the 0.9.3 ?

alpharush ***@***.***> 于2023年6月8日周四 20:35写道：

**Comment by 0xxfu** [comment]
> 

Maybe the environment you installed is inconsistent with the environment you activated.
