### ISSUE TITLE
[Bug]: Slither detects already triaged results

### ISSUE THREAD

**Issue by jubeira** [crytic/slither#1965]
### Describe the issue:

Slither seems to be detecting issues that have already been triaged into the `slither.db.json` from time to time.
This makes it difficult to get consistent results between runs after triaging findings, and also generates false positives when running Slither in CI.

This could be related to the ID of the findings that is stored in the DB file, which seems to vary between runs.

### Code example to reproduce the issue:

Public sample to reproduce the issue with instructions here: https://github.com/balancer/balancer-v2-monorepo/pull/2514.

### Version:

`0.9.3`

### Relevant log output:

```shell
# Following the instructions in the PR mentioned above, this is the output after triaging all the results.
# Running slither two times in a row outputs different results:

juan@M16:~/prj/bal/pkg/solidity-utils$ yarn slither
Nothing to compile
INFO:Detectors:
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a3) / ONE_20 (contracts/math/LogExpMath.sol#198)
	- product = (product * a4) / ONE_20 (contracts/math/LogExpMath.sol#202)
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a3) / ONE_20 (contracts/math/LogExpMath.sol#198)
	- product = (product * a5) / ONE_20 (contracts/math/LogExpMath.sol#206)
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a7) / ONE_20 (contracts/math/LogExpMath.sol#214)
	- product = (product * a8) / ONE_20 (contracts/math/LogExpMath.sol#218)
LogExpMath._ln(int256) (contracts/math/LogExpMath.sol#326-458) performs a multiplication on the result of a division:
	- a = (a * ONE_20) / a3 (contracts/math/LogExpMath.sol#372)
	- a = (a * ONE_20) / a4 (contracts/math/LogExpMath.sol#377)
LogExpMath._ln(int256) (contracts/math/LogExpMath.sol#326-458) performs a multiplication on the result of a division:
	- a = (a * ONE_20) / a5 (contracts/math/LogExpMath.sol#382)
	- a = (a * ONE_20) / a6 (contracts/math/LogExpMath.sol#387)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply
INFO:Slither:. analyzed (72 contracts with 85 detectors), 5 result(s) found


juan@M16:~/prj/bal/pkg/solidity-utils$ yarn slither
Nothing to compile
INFO:Detectors:
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a3) / ONE_20 (contracts/math/LogExpMath.sol#198)
	- product = (product * a5) / ONE_20 (contracts/math/LogExpMath.sol#206)
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a4) / ONE_20 (contracts/math/LogExpMath.sol#202)
	- product = (product * a6) / ONE_20 (contracts/math/LogExpMath.sol#210)
LogExpMath.exp(int256) (contracts/math/LogExpMath.sol#146-281) performs a multiplication on the result of a division:
	- product = (product * a7) / ONE_20 (contracts/math/LogExpMath.sol#214)
	- product = (product * a8) / ONE_20 (contracts/math/LogExpMath.sol#218)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply
INFO:Slither:. analyzed (72 contracts with 85 detectors), 3 result(s) found
juan@M16:~/prj/bal/pkg/solidity-utils$
```

**Comment by amrshaban2005** [comment]
I have the same issue, I hide all results by run triage mode and all saved in slither.db.json, however when I run slither again and again, each time gives me the issues and every run give me different result

**Comment by 0xalpharush** [comment]
@amrshaban2005 Is it also with the divide before multiply detector or a different one?

**Comment by amrshaban2005** [comment]
@0xalpharush Could you kindly provide me with any updates, please?

**Comment by amrshaban2005** [comment]
> @amrshaban2005 hi, i can't reproduce this issue with other detectors. Please add some more details or better a code to reproduce it. Thank you.

hi, thank you for follow up, our code base is complicated so can't write a simple code to reproducer it , 
what I do is the following 
- run `slither . --triage-mode` and hide all issues found 
![image](https://github.com/crytic/slither/assets/45541807/06d1f136-f113-4b33-8caa-d1a97621a09d)

- then run ` slither .` which should getting zero issues however it returns 4 issues which means some issues still show although I hide all
![image](https://github.com/crytic/slither/assets/45541807/8094b977-538a-4671-b5ee-8a70fc082538)

please note that every time run `slither .` it getting me different result

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/2114
