### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by tunabaka** [crytic/slither#2038]
### Describe the issue:

Slither cannot scan mumbai address

### Code example to reproduce the issue:

![image](https://github.com/crytic/slither/assets/98317179/25fdcf0c-c269-4397-add4-3232974cf87f)

### Version:

0.9.6

**Comment by 0xalpharush** [comment]
This looks like an HTTP error on the explorer's side. Maybe using an API key would get around this?
