### ISSUE TITLE
How to read versions of packages are being used?

### ISSUE THREAD

**Issue by 0xxfu** [crytic/slither#2040]
### Describe the desired feature

[OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/security/advisories?page=1) has a lot of bugs in outdated version, i want to detect which outdated versions are being used in project.

**Comment by 0xalpharush** [comment]
We've discussed creating this tool but it doesn't currently exist https://github.com/crytic/slither/issues/1598. You can hash the source code and see if the hash matches a version in OpenZeppelin and then see if that version has an advisory doing something like https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/utils/standard_libraries.py#L70-L72
But the advisory info is not exposed in Slither as of now

**Comment by 0xxfu** [comment]
slither-audit looks like a good idea.

Is it possible to expose "package.json" in slither?
Developers can directly detect outdated version numbers, which is relatively simple and straightforward.
