### ISSUE TITLE
auto detect `solc`

### ISSUE THREAD

**Issue by llllvvuu** [crytic/slither#2054]
### Describe the desired feature

See `foundry.toml`: `auto_detect_solc = true`

**Comment by 0xalpharush** [comment]
Could you elaborate? For a foundry project or any compilation framework, you can run `slither .` and do not need to configure the solc version

For use without a compilation framework, this is probably relevant to https://github.com/crytic/crytic-compile/issues/210 and requires some sort of version resolution algorithm for pragmas in the input source code.

**Comment by llllvvuu** [comment]
> For a foundry project or any compilation framework, you can run `slither .` and do not need to configure the solc version

When I tried single-file slither (`slither src/Contract.sol`) in a Foundry project, I was required to configure the `solc` version. This is relevant for text editors.

**Comment by 0xalpharush** [comment]
Going to track this in https://github.com/crytic/crytic-compile/issues/210
