### ISSUE TITLE
Bug in function-id printer

### ISSUE THREAD

**Issue by sobolev-igor** [crytic/slither#210]
Hi there! There is an issue connected to `function-id` printer that I faced:

when you create a dynamic array with `public` visibility modifier compiler automatically generates a getter-function with `uint256` input parameter. However, Slither thinks that the getter has no input parameters. Thus, the wrong function signature is printed in the output.

Here is a small example.

```
pragma solidity 0.5.7;

contract Example {
    uint256[] public example;
}
```

Slither outputs the following table: 

```
+-----------+------------+
|    Name   |     ID     |
+-----------+------------+
| example() | 0x54353f2f |
+-----------+------------+
```

However, the real `example()` function's signature is `0x477e4a02` in the example.

**Comment by montyly** [comment]
Thank you @sobolev-igor for reporting the issue. We are going to fix the printer

**Comment by montyly** [comment]
Hi @sobolev-igor, the issue is fixed in `master`, it will be included in the next pypi release
