### ISSUE TITLE
Improve slither performance

### ISSUE THREAD

**Issue by aviggiano** [crytic/slither#2101]
### Describe the desired feature

Hello

Are there any plans to improve Slither's performance?

I am using Echidna on a big project, and I think slither is one of the main bottlenecks in my iterative process of compiling --> changing --> testing

```
$ echidna EchidnaTester.sol --test-mode assertion --contract EchidnaTester --config config.yaml 
[2023-08-31 14:33:53.84] Compiling EchidnaTester.sol... Done! (3.685049s)
Analyzing contract: EchidnaTester.sol:EchidnaTester
[2023-08-31 14:33:58.63] Running slither on EchidnaTester.sol... Done! (59.362562s)
```

Is this expected, or may I be running into any kind of issue?

**Comment by smonicas** [comment]
Hello, can you try this [PR](https://github.com/crytic/slither/pull/2064) and see if it improves. Additionally you could also try it with thisa commit [Cache contract functions declared](https://github.com/crytic/slither/pull/2065/commits/aa32bde61c4b2bdfcd7c76a4ca35cf81d9e70478). Thank you.

**Comment by aviggiano** [comment]
@smonicas thanks for the quick reply

It worked!

```
[2023-08-31 15:10:19.64] Compiling EchidnaTester.sol... Done! (5.228761s)
Analyzing contract: EchidnaTester.sol:EchidnaTester
[2023-08-31 15:10:25.96] Running slither on EchidnaTester.sol... Done! (6.352373s)
```

I guess I'll close this issue
