### ISSUE TITLE
Slither does not handle multiple contracts with the same name across compilation units

### ISSUE THREAD

**Issue by hacker-DOM** [crytic/slither#2107]
Consider the codebase https://github.com/hacker-DOM/reference-resolving/tree/ecd8bf0e91a3636104b5ffc805537eaac2eeb8d7

These are the results for inheritance-graph and call-graph, both of which are wrong

![image](https://github.com/crytic/slither/assets/18601956/83ad0f67-0172-410f-84c8-b8c14a67e234)

![image](https://github.com/crytic/slither/assets/18601956/fd47b0b8-ea37-420d-a241-ac039e1d8f94)

**Comment by montyly** [comment]
Indeed the printers merge contracts with the same name, which they should not. We will update the printer.

**Comment by 0xalpharush** [comment]
We need to make these id's unique across compilation unit
https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/printers/call/call_graph.py#L20-L25
https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/printers/inheritance/inheritance_graph.py#L103-L106
