### ISSUE TITLE
[Bug-Candidate]: crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?

### ISSUE THREAD

**Issue by Barzival** [crytic/slither#2113]
### Describe the issue:

hardhat_like_parsing
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?

### Code example to reproduce the issue:

`Contract A {}`

### Version:

0.9.6

### Relevant log output:

```shell
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?
out/build-info is not a directory.
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/slither_analyzer-0.9.6-py3.11.egg/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slither_analyzer-0.9.6-py3.11.egg/slither/__main__.py", line 91, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crytic_compile-0.3.4-py3.11.egg/crytic_compile/crytic_compile.py", line 647, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by elopez** [comment]
Hi, thanks for the report! Can you provide more information about what you're trying to run slither against? Is it a hardhat or a foundry project? Can you provide the full output of running `slither-doctor` on your project? e.g. `slither-doctor .`

**Comment by Barzival** [comment]
hardhat project

**Comment by 0xalpharush** [comment]
Assuming you can run `hardhat build` successfully, it's possible that there's a custom [artifact directory ](https://hardhat.org/hardhat-runner/docs/config#available-config-options)defined in the hardhat config and you need to run slither with `--hardhat-artifacts-directory`? Would you share your config file and the output of running `slither-doctor .`

**Comment by kamikazebr** [comment]
> Assuming you can run `hardhat build` successfully, it's possible that there's a custom [artifact directory ](https://hardhat.org/hardhat-runner/docs/config#available-config-options)defined in the hardhat config and you need to run slither with `--hardhat-artifacts-directory`. Would you share your config file and the output of running `slither-doctor .`?

For Foundry is `--foundry-out-directory`.
