### ISSUE TITLE
Slither can't find same folder imports without ./

### ISSUE THREAD

**Issue by izcoser** [crytic/slither#2137]
Hello.
I'm having trouble analyzing projects depending on their import style.
For example, imagine a project at example/src/, with files:

example/src/A.sol
example/src/B.sol

src/A.sol has:
`import "B.sol";`

When I am at the example/ folder and run slither src/A.sol, Slither fails to find B.sol.
Slither only succeeds if:
1. I am inside the example/src/ folder or;
2. I replace `import "B.sol"` with `import "./B.sol"`;

I would really not like to mess with the imports because I'm using Slither as an API, and cd'ing to the target contract's folder will likely break other things in my setup. So what would be the best approach in this case? Is this solvable with remaps?

**Comment by 0xalpharush** [comment]
I would recommend using a framework such as hardhat or foundry as slither does not currently resolve imports itself. Alternatively, you can use solc's standard json input via crytic-compile and pass the `CryticCompile` object to slither 
An example of this:
https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/tests/unit/core/test_using_for.py#L16-L20
