### ISSUE TITLE
[False Negative]: extenal-function detector does not detect on new solidity versions

### ISSUE THREAD

**Issue by Yhtiyar** [crytic/slither#2144]
### What bug did Slither miss and which detector did you anticipate would catch it?

As for now, `external-function` detector only works on old solidity versions (`VULNERABLE_SOLC_VERSIONS` variable in detector class). 
```solidity
function doSmth() public {
///...
}

function doSmth() external {
///...
}
```
Even though these two functions will be identical in bytecode representations, it would be better for code readability if the `public` functions that are not called in the contract were declared as `external`. It is just easier to construct the control flow in your head if you directly know that the function is intended to be called only from outside.

### Frequency

Very Frequently

### Code example to reproduce the issue:

``` solidity
pragma solidity ^0.8.13;

contract MinimalTest {
    uint256 private _number;

    function setNumber(uint256 n) public {
       _number = n;
    }
```

### Version:

0.9.6

**Comment by 0xalpharush** [comment]
This `external-function` detector is related to optimizations that are not applicable to recent versions of solidity (ref https://github.com/crytic/slither/wiki/Detector-Documentation#public-function-that-could-be-declared-external). We could probably add a separate detector, but I'm not sure if it's worth the churn for users

**Comment by Yhtiyar** [comment]
Yeah, probably the new detector will not be so useful for ordinary users.
We will probably just add [this detector](https://github.com/pessimistic-io/slitherin/pull/72) to our detectors. 
Thanks for the response! Will close the issue
