### ISSUE TITLE
Donating Funds to Slither

### ISSUE THREAD

**Issue by Lfada** [crytic/slither#2149]
### Describe the desired feature

Hi Slither maintainers. I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

We've been using https://github.com/crytic/slither as part of [Drips](http://drips.network/). It's in fact one of our most critical dependencies!

We really appreciate the work you all do and we want to make sure that you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [Drips](https://www.drips.network/) (an initiative that is coming out of our organization for funding FOSS).

Who can I talk to about it?

**Comment by montyly** [comment]
Hey sorry for the delay on this. 

This looks awesome, thanks. I will reach out to you @Lfada

**Comment by Lfada** [comment]
Amazing! tw works: @lukfada :)

**Comment by Lfada** [comment]
Hi @montyly haven't heard from anyone. Tried to message you over TW/X but no response. 

Let me know when and how you would prefer to connect :)

**Comment by WaizKhan7** [comment]
try their Slack channel
https://www.trailofbits.com/contact/

**Comment by montyly** [comment]
Sorry for the delay, I was off for a few days. I followed up by email ;)
