### ISSUE TITLE
[Question] How read user's arguments from detector?

### ISSUE THREAD

**Issue by SovaSlava** [crytic/slither#2161]
Hello.
I've write detector and need, that user could specify contract name, which will be analized.
But slither dont allow users specify contract name, so I'd like to read maybe --arg, or --args from command line from detector. How it is possible to do?

**Comment by 0xalpharush** [comment]
This is not currently possible but we plan on adding a flag to filter this as discussed https://github.com/crytic/slither/issues/759. I'm going to close this but feel free to comment on the issue if you don't think it covers what you'd like
