### ISSUE TITLE
[Bug]: there's "\n" missing from DETECTOR_INFO.

### ISSUE THREAD

**Issue by partender810** [crytic/slither#2169]
### Describe the issue:

DETECTOR_INFO contains information about the detected vulnerability, but it is difficult to read due to missing "\n" in some parts.

### Code example to reproduce the issue:

# Nothing was found in the outer scope
                    info: DETECTOR_INFO = [
                        "Modifier ",
                        mod,
                        " does not always execute _; or revert",
                    ]

this code in "slither/slither/detectors/functions/modifier.py" line 88-93.

### Version:

slither WalletLibrary.sol

(https://github.com/crytic/not-so-smart-contracts/blob/master/unprotected_function/WalletLibrary_source_code/WalletLibrary.sol)

### Relevant log output:

```shell
Modifier WalletLibrary.onlyowner() (WalletLibrary.sol#84-87) does not always execute _; or revertModifier WalletLibrary.onlymanyowners(bytes32) (WalletLibrary.sol#91-94) does not always execute _; or revertReference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-modifier

Pragma version^0.4.9 (WalletLibrary.sol#12) allows old versions
solc-0.4.22 is known to contain severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
```

**Comment by Sohamkayal4103** [comment]
Hi. Can I work on this?
