### ISSUE TITLE
Investigate Dominator deadcode problem fix 

### ISSUE THREAD

**Issue by montyly** [crytic/slither#2171]
I had to revert https://github.com/crytic/slither/pull/1984 in https://github.com/crytic/slither/pull/2170, for the vyper test to pass. @0xalpharush : can you take a look at it?

I wanted to move fast to make the release today, so I did not investigate what was hapenning

**Comment by 0xalpharush** [comment]
We need to mirror the calls to update_reachability and set_reachable in the cfg parsing for Vyper also. The original PR only implemented it for solc
