### ISSUE TITLE
Processing specified contract with slither

### ISSUE THREAD

**Issue by vineetaparodkar** [crytic/slither#2184]
Is it possible to process a particular contract from source file rather then processing all the available contracts in solidity file?(as there might be multiple contracts in a file)

**Comment by 0xalpharush** [comment]
This is not currently possible but we plan on adding a flag to filter this as discussed [here](https://github.com/crytic/slither/issues/759). I'm going to close this but feel free to comment on the issue if you don't think it covers what you'd like
