### ISSUE TITLE
Add Support For Top level EventDefinition

### ISSUE THREAD

**Issue by FaybianB** [crytic/slither#2226]
### Describe the desired feature

As of Solidity 0.8.22, events are allowed to be declared at the file level. However, attempting to run Slither on a file with events declared at the file level results in an `slither.exceptions.SlitherException: Top level EventDefinition not supported`

The tool should be updated to properly parse and support top-level event definitions.

**Comment by smonicas** [comment]
There is an open issue about this #2205 and an open PR #2219 which should already work, you can try it and leave comments if you encounter problems. I close this issue in favor of tracking it in the original one.
