### ISSUE TITLE
slithIR wiki page links are broken

### ISSUE THREAD

**Issue by igorline** [crytic/slither#2228]
### Describe the issue:

I've found three links broken on slithIR wiki page. 
As there is no way to open PR to wiki, I forked wiki and fixed links in my branch: https://github.com/igorline/slither_wiki/commit/3fb3c212881405f6f675cee61cf1d426809d1834

here's the patch
https://gist.github.com/igorline/1d1e4201e3cef1efdaa5f4e9b82d9a38

### Code example to reproduce the issue:

https://github.com/crytic/slither/wiki/SlithIR#condition

### Version:

0.10.0

**Comment by elopez** [comment]
Thank you for reporting this @igorline! I just updated the wiki page and fixed the links.
