### ISSUE TITLE
[Bug-Candidate]: Wrong library/high level call.

### ISSUE THREAD

**Issue by shushaaniik** [crytic/slither#2231]
### Describe the issue:

When a contract is inherited from the base one, where we have a `using ... for ...` statement, the high level call for the node in inherited contract will have a call with contract name `uint256`, which will be the only information about it.
That's what happens in **Version 1**, but in **Version 2** it collects the precise information.

Also when running with higher version of solidity (e.g. `0.8.7`) even for **Version 1**, it gives precise info.

#### Version 1
```solidity
library SafeMath {
    function add(uint256 a,uint256 b) internal pure returns (uint256) {
        return a + b;
    }
}


contract C {
    using SafeMath for uint256;
    mapping(address => uint256) nonces;

    function executeMetaTransaction(
        address userAddress,bytes memory functionSignature,bytes32 sigR,bytes32 sigS,uint8 sigV
    ) public payable {
        nonces[userAddress] = nonces[userAddress].add(1);
    }
}


contract Main is C {}
```

#### Version 2
```solidity
library SafeMath {
    function add(uint256 a,uint256 b) internal pure returns (uint256) {
        return a + b;
    }
}


contract C {
    using SafeMath for uint256;
    mapping(address => uint256) nonces;

    function executeMetaTransaction(
        address userAddress,bytes memory functionSignature,bytes32 sigR,bytes32 sigS,uint8 sigV
    ) public payable {
        nonces[userAddress] = nonces[userAddress].add(1);
    }
}

contract Main is C {
    using SafeMath for uint256;
}
```

### Version:

`0.4.21`
`0.8.7`

**Comment by 0xalpharush** [comment]
Do you have an example of a script that produces the wrong result so we can replicate the issue? It is not clear what is wrong
