### ISSUE TITLE
[Question] Why unused return only applicable to HighLevelCall?

### ISSUE THREAD

**Issue by yxliang01** [crytic/slither#224]
In my opinion, the rule `unused-return` should also be applicable to low level calls, I am wondering why it's now only limited to detect for high level calls? Since there's an explicit `if` to skip low level calls, there might be some undocumented intention?

Thanks

CC related : @montyly @benstew

**Comment by montyly** [comment]
Hi @yxliang01, it's a good question, thank you for bringing this up!

After some thinking, I think we should:
1 - Add `InternalCall` and `InternalDynamicCall` to the unused return detector
2 - Create a separate detector for unused returns of low-level calls
3 - Create a separate detector for the lack of check in case of `send` usage

The reason for splitting this into multiple detectors is that it can make sense to NOT check the return value of a low-level call, or a `send`, to prevent the contract to be blocked. Typically, if a contract needs to send ethers to an untrusted destination, using `send` without checking its return value might be better than using `transfer`. 

If we have multiple detectors, the user can decide to disable the detectors related to low-level calls/send, while keeping the high-level/internal calls check.

**Comment by yxliang01** [comment]
@montyly Hmm your reasoning makes sense. :) Happy to see that in near future! As such, maybe you can also process https://github.com/crytic/slither/pull/225 ?

**Comment by montyly** [comment]
Thank you for your suggestions @yxliang01! 
I merged the changes in `dev`. The new detectors will be available in the upcoming 0.6.4 release (in a few days)
