### ISSUE TITLE
[Question] A representation of "not used" returned variables

### ISSUE THREAD

**Issue by talfao** [crytic/slither#2242]
Dear community,

I have one question for you, which I hope you can help me figure out. I have the following solidity line.
```Solidity
(, uint a, uint b, , ,) = contract.functionCall();
```
Is it possible to get a representation in Slither of "not existing variable", but the solidity claims that something should be returned to that place?

I mean the variable between commas, so does slither know that it should be like this?
```Solidity
(<some_node>, uint a, uint b,<some_node> ,<some_node> ,<some_node>) = contract.functionCall();
```

*Note: When I iterate through function.nodes or function.variables_written, nothing from `uint a` and `uint b` is returned.*

**Comment by 0xalpharush** [comment]
The call will be represented as a `HighLevelCall` in slither's intermediate representation and the function attribute can be used to access the [return type]( 
https://crytic.github.io/slither/slither/core/declarations/function.html#Function.returns) doing something like:

https://github.com/crytic/slither/blob/e3dcf1ecd3e9de60da046de471c5663ab637993a/slither/detectors/operations/unchecked_transfer.py#L51-L52

**Comment by talfao** [comment]
Thanks, after investigating a detector, i found an approach.
