### ISSUE TITLE
ModuleNotFoundError: No module named '_pysha3' 

### ISSUE THREAD

**Issue by ilguardianodelblocco** [crytic/slither#2243]
### Describe the issue:

I use python 3.7.

When I try to run Slither I have an issue about the package pysha3.
After some tests, I simply uninstall and reinstall the module pysha3 and everything works well.
I have written this because there is not anything on web.
Regards

```
pip uninstall pysha3
pip install pysha3
```

### Code example to reproduce the issue:

pip install slither-analyzer

### Version:

0.8.3

**Comment by elopez** [comment]
Hi @ilguardianodelblocco ! Thanks for providing this guidance for anyone running Python 3.7 or earlier.

I'll close this issue as this should no longer be an issue; the last few Slither releases (0.9.2 or higher; latest is 0.10 at the time of writing) do not depend on `pysha3` any more, although they do require Python 3.8 or newer to be installed and run.
