### ISSUE TITLE
Small issue in documenting "variable-scope" detector

### ISSUE THREAD

**Issue by mojtaba-eshghie** [crytic/slither#2245]
In the following part of the documentation, in the comment, z is said to be used before declaration. Whereas the `x` is used pre-declaration.  
[Link to the part of documentation concerning this issue](https://github.com/crytic/slither/wiki/Detector-Documentation#description-47)

```Solidity
contract C {
    function f(uint z) public returns (uint) {
        uint y = x + 9 + z; // 'z' is used pre-declaration
        uint x = 7;

        if (z % 2 == 0) {
            uint max = 5;
            // ...
        }

        // 'max' was intended to be 5, but it was mistakenly declared in a scope and not assigned (so it is zero).
        for (uint i = 0; i < max; i++) {
            x += 1;
        }

        return x;
    }
}
```

**Comment by 0xalpharush** [comment]
Thanks! Would you like to submit a PR? https://github.com/crytic/slither/blob/e3dcf1ecd3e9de60da046de471c5663ab637993a/slither/detectors/variables/predeclaration_usage_local.py#L39C1-L39C1

**Comment by ATREAY** [comment]
Hey @0xalpharush, is it okay if I work on this issue if it's still available?

**Comment by 0xalpharush** [comment]
@ATREAY Go for it!
