### ISSUE TITLE
[Bug]: `import as` unsupported

### ISSUE THREAD

**Issue by matmilbury** [crytic/slither#2274]
### Describe the issue:

Slither can’t create an IR when a smart contract with renamed import (`import { X as Y } from 'xyz.sol';`).

Importing without the rename 'fixes' the issue.

### Code example to reproduce the issue:

```sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.23;

contract Bar {
    constructor() { }
}
```

```sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.23;

import { Bar as Bar2 } from "./Bar.sol";

contract Foo {
    constructor() {
        new Bar2();
    }
}
```

### Version:

0.10.0

**Comment by 0xalpharush** [comment]
Thanks for your interest in Slither. This is a known issue that will take a big lift to properly support https://github.com/crytic/slither/issues/1452
