### ISSUE TITLE
[Bug]: None when requested immediate inheritance

### ISSUE THREAD

**Issue by Tiko7454** [crytic/slither#2304]
### Describe the issue:

When I request inheritance for contract A it gives a list consisting of B, but when I request for immediate inheritance, it gives a list with one element, which is None

### Code example to reproduce the issue:

```solidity
// b.sol

contract B{}
```

```solidity
// a.sol

import {B as Base} from "b.sol";

contract A is Base {}
```

### Version:

0.10.0

### Relevant log output:

```shell
>>> slither = Slither("a.sol")
>>> A = slither.contracts[0]
>>> A.name
'A'
>>> A.inheritance
[<slither.core.declarations.contract.Contract object at 0x7f36dea24b10>]
>>> A.inheritance[0].name
'B'
>>> A.immediate_inheritance
[None]
```

**Comment by 0xalpharush** [comment]
We probably need to resolve the alias as is done here: 
https://github.com/crytic/slither/blob/e3dcf1ecd3e9de60da046de471c5663ab637993a/slither/solc_parsing/slither_compilation_unit_solc.py#L437-L440
For base contracts, too:
https://github.com/crytic/slither/blob/e3dcf1ecd3e9de60da046de471c5663ab637993a/slither/solc_parsing/slither_compilation_unit_solc.py#L456-L464

**Comment by Tiko7454** [comment]
I fixed the bug the way you said and opened a pr #2306

**Comment by 0xalpharush** [comment]
Did it fix the issue?

**Comment by Tiko7454** [comment]
Yes
