### ISSUE TITLE
Starter foundry project fails

### ISSUE THREAD

**Issue by JoranHonig** [crytic/slither#2335]
### Describe the issue:

Running slither with the starter foundry project fails:

commands:
1. `forge init`
2. `slither .`

result:
```
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?
out/build-info is not a directory.
```

### Code example to reproduce the issue:

forge init

### Version:

0.10.0

**Comment by 0xalpharush** [comment]
I just tried it and it works. Can you run `foundryup` and share the full log?

**Comment by JoranHonig** [comment]
my bad, used an old foundry version
