### ISSUE TITLE
Allow users to filter files under test

### ISSUE THREAD

**Issue by JoranHonig** [crytic/slither#2336]
### Describe the desired feature

Running slither on the `forge init` base project takes ages because slither attempts to analyze all dependencies. Even when they're not included by any file in the src/ directory.

Ideally it'd just analyze the files that are actually in the src/ directory.

It'd be great if there was some configuration parameter that would allow someone to achieve this.

**Comment by 0xalpharush** [comment]
I'm not sure what you're requesting as we already filter tests and script by defalt
```
(slither-original) ~/virtual/slither-dev/init master time slither .
'forge clean' running (wd: /Users/simonemonica/virtual/slither-dev/init)
'forge config --json' running
'forge build --build-info --skip */test/** */script/** --force' running (wd: /Users/simonemonica/virtual/slither-dev/init)
INFO:Detectors:
Pragma version^0.8.13 (src/Counter.sol#2) allows old versions
solc-0.8.23 is not recommended for deployment
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
INFO:Slither:. analyzed (1 contracts with 93 detectors), 2 result(s) found
slither .  0.84s user 0.17s system 95% cpu 1.057 total
```

**Comment by JoranHonig** [comment]
This is also not an issue anymore for the same reason as https://github.com/crytic/slither/issues/2335

Apologies!
