### ISSUE TITLE
support for cancun: transient storage opcodes, blobhash

### ISSUE THREAD

**Issue by d1onys1us** [crytic/slither#2345]
### Describe the desired feature

these features are missing and failing so i can't run slither on my codebase. is it possible to ignore this without modifying my codebase? or any ETA on when support may arrive? thx!

**Comment by 0xalpharush** [comment]
We just made a [release](https://github.com/crytic/slither/releases/tag/0.10.1) that should support this. If you have an issue after upgrading, please let us know

**Comment by d1onys1us** [comment]
> We just made a [release](https://github.com/crytic/slither/releases/tag/0.10.1) that should support this. If you have an issue after upgrading, please let us know

this works for me, so i'll close the issue
