### ISSUE TITLE
Detector 'Too Many Digits'  is confusing, change name to 'Quantifier amount is ambiguous' 

### ISSUE THREAD

**Issue by sambacha** [crytic/slither#2352]
### Describe the desired feature

# Detector 'Too Many Digits'  is confusing, change name to 'Quantifier amount is ambiguous' 

> [!NOTE] 
>  {@see <https://github.com/crytic/slither/wiki/Detector-Documentation#too-many-digits> }

The Slither Detector Guide gives us the following:

```solidity
contract MyContract{
    uint 1_ether = 10000000000000000000; 
}
```

> While `1_ether` looks like 1 ether, it is 10 ether. As a result, it's likely to be used incorrectly.

The name 'Too many Digits' would give you the impression that it is referring to the `10000000000000000000` and not the name `1_ether`. 

## Proposal: Quantifier amount is ambiguous

This should be renamed to something less ambiguous, such as:

> The quantifier amount does not fit with the countable noun (ether in our example).

The suggestion should read:

**Consider changing the quantifier or the noun.**

$value: amount → number$

## Digit Spacing

Also, the name for this detector to me implies something to do with digit spacing. I would also consider the following rule:

> The digits of numerical values having more than four digits on either side of the decimal marker are separated into groups of three using the underscore character _ from both the left and right of the decimal marker.

**Comment by elopez** [comment]
Hi @sambacha, thanks for the suggestions.

For the first one, the detector currently spots [constants with more than 5 consecutive zeros](https://github.com/crytic/slither/blob/f7238c4fdf969d7ca402ae0d9019293fd2663270/slither/detectors/statements/too_many_digits.py#L68-L83). Would you like to see a new detector that tries to find misleading variable names instead?

> The name 'Too many Digits' would give you the impression that it is referring to the 10000000000000000000 and not the name 1_ether.

That is indeed the case; it refers to the large number constant. This other example with a different variable name triggers as well:

```solidity
contract MyContract{
    uint solidity_is_fun = 10000000000000000000; 
}
```

**Comment by sambacha** [comment]
> Hi @sambacha, thanks for the suggestions.
> 
> 
> 
> For the first one, the detector currently spots [constants with more than 5 consecutive zeros](https://github.com/crytic/slither/blob/f7238c4fdf969d7ca402ae0d9019293fd2663270/slither/detectors/statements/too_many_digits.py#L68-L83). Would you like to see a new detector that tries to find misleading variable names instead?
> 
> 
> 
> > The name 'Too many Digits' would give you the impression that it is referring to the 10000000000000000000 and not the name 1_ether.
> 
> 
> 
> That is indeed the case; it refers to the large number constant. This other example with a different variable name triggers as well:
> 
> 
> 
> ```solidity
> 
> contract MyContract{
> 
>     uint solidity_is_fun = 10000000000000000000; 
> 
> }
> 
> ```

I think actually just changing the example in the Wiki would be the best thing, as that is what confused me.

**Comment by 0xalpharush** [comment]
Would you like to make a PR?

**Comment by sambacha** [comment]
> Would you like to make a PR?

Seems like you beat me to it!


Quick question: can we add a registry of the different detectors that are available for slither? Is that available somewhere?

**Comment by 0xalpharush** [comment]
There is a list in the readme and the wiki. I'd like to have some site in the future but does that suffice?
