### ISSUE TITLE
Failed to generate IR

### ISSUE THREAD

**Issue by AaronLee22** [crytic/slither#2354]
--ignore-compile used, if something goes wrong, consider removing the ignore compile flag
ERROR:ContractSolcParsing:Impossible to generate IR for LibSort._toInts (scripts/libraries/LibSort.sol#469-474):
 'str' object has no attribute 'type'
ERROR:SlitherSolcParsing:
Failed to generate IR for LivenessGuard_TestInit._initializeSafeTools. Please open an issue https://github.com/crytic/slither/issues.
LivenessGuard_TestInit._initializeSafeTools (test/safe-tools/SafeTestTools.sol#509-513):
 	singleton = new GnosisSafe()
	proxyFactory = new GnosisSafeProxyFactory()
	handler = new CompatibilityFallbackHandler()
Traceback (most recent call last):
  File "/opt/slither/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 735, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 841, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 146, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 166, in _init_parsing_and_analyses
    raise e
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 162, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 539, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 765, in _convert_to_slithir
    raise e
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 750, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/slither/lib/python3.9/site-packages/slither/core/declarations/function.py", line [177](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8152488144/job/22282043433#step:12:178)2, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/slither/lib/python3.9/site-packages/slither/core/cfg/node.py", line 716, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node, is_solidity)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line [203](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8152488144/job/22282043433#step:12:204)3, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 529, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 875, in propagate_types
    assert contract
AssertionError

This error continues to occur despite having applied filter_path for both LibSort.sol and SafeTestTools.sol.

{
  "detectors_to_exclude": "arbitrary-send-eth,incorrect-equality,naming-convention,solc-version",
  "exclude_dependencies": true,
  "exclude_informational": true,
  "exclude_low": true,
  "exclude_optimization": true,
  "fail_on": "none",
  "filter_paths": "(src/vendor|src/cannon/MIPS.sol|src/EAS/EAS.sol|test/safe-tools/SafeTestTools.sol|scripts/libraries/LibSort.sol)",
  "foundry_out_directory": "artifacts"
}

**Comment by AaronLee22** [comment]
It says solc-select-1.0.4. 
without the --ignore-compile it works as expected but some how my repository has a complex building mechanism and want to use it in mono repo environment. 

    - name: Run Slither
      uses: crytic/slither-action@v0.3.1
      with:
        target: packages/tokamak/contracts-bedrock
        slither-config: packages/tokamak/contracts-bedrock/slither.config.json
        fail-on: config
        slither-version: dev-triage-db
        slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
        ignore-compile: true

The install dependencies and building contracts worked fine.

**Comment by 0xalpharush** [comment]
If it works without `--ignore-compile`, could you explain what you're trying to accomplish by using `--ignore-compile`?There's an example of running a build command as a step in the github action [here](https://github.com/marketplace/actions/slither-action#example-workflow-dapp)

**Comment by elopez** [comment]
if you want to use ignore-compile and build manually, you can add the `--skip` argument to your `forge build` invocation to achieve the same Slither does internally:

`forge build --build-info --skip '*/test/**' '*/script/**'`

That way test & script won't get built and Slither will then not process that code.

**Comment by AaronLee22** [comment]
reason i want to use --ignore-compile.
It is not suitable for a monorepo scenario where the dependency's pnpm-lock file exists at the top level of the repository, but the target directory I want to analyze is not located at the top level of the repository.

**Comment by AaronLee22** [comment]
if you want to use ignore-compile and build manually, you can add the --skip argument to your forge build invocation to achieve the same Slither does internally:

forge build --build-info --skip '*/test/**' '*/script/**'

That way test & script won't get built and Slither will then not process that code.

>>let me try this way too

**Comment by AaronLee22** [comment]
> If it works without `--ignore-compile`, could you explain what you're trying to accomplish by using `--ignore-compile`?There's an example of running a build command as a step in the github action [here](https://github.com/marketplace/actions/slither-action#example-workflow-dapp)

This is exactly what I tried and the error above occurs

**Comment by AaronLee22** [comment]
> if you want to use ignore-compile and build manually, you can add the `--skip` argument to your `forge build` invocation to achieve the same Slither does internally:
> 
> `forge build --build-info --skip '*/test/**' '*/script/**'`
> 
> That way test & script won't get built and Slither will then not process that code.

I tried forge build --build-info --skip '*/test/**' '*/script/**' as below 
    - name: Build the contracts
      run: |
        pnpm run build
        forge build --build-info --skip 'packages/tokamak/contracts-bedrock/scripts' 'packages/contracts-bedrock/test'
still same error occurs as above.

Have I done something wrong?

**Comment by AaronLee22** [comment]
> It says solc-select-1.0.4. without the --ignore-compile it works as expected but some how my repository has a complex building mechanism and want to use it in mono repo environment.
> 
> ```
> - name: Run Slither
>   uses: crytic/slither-action@v0.3.1
>   with:
>     target: packages/tokamak/contracts-bedrock
>     slither-config: packages/tokamak/contracts-bedrock/slither.config.json
>     fail-on: config
>     slither-version: dev-triage-db
>     slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
>     ignore-compile: true
> ```
> 
> The install dependencies and building contracts worked fine.

slither version is 0.10.0

**Comment by elopez** [comment]
> > if you want to use ignore-compile and build manually, you can add the `--skip` argument to your `forge build` invocation to achieve the same Slither does internally:
> > `forge build --build-info --skip '*/test/**' '*/script/**'`
> > That way test & script won't get built and Slither will then not process that code.
> 
> I tried forge build --build-info --skip '_/test/**' '_/script/**' as below - name: Build the contracts run: | pnpm run build forge build --build-info --skip 'packages/tokamak/contracts-bedrock/scripts' 'packages/contracts-bedrock/test' still same error occurs as above.
> 
> Have I done something wrong?

please try again, removing `pnpm run build` and keeping the asterisks on the forge invocation. You're likely running forge from within `packages/tokamak/contracts-bedrock` so the expanded paths you tried with won't match, and any previous forge runs launched from pnpm may generate artifacts that trigger the issue.

**Comment by AaronLee22** [comment]
> > > if you want to use ignore-compile and build manually, you can add the `--skip` argument to your `forge build` invocation to achieve the same Slither does internally:
> > > `forge build --build-info --skip '*/test/**' '*/script/**'`
> > > That way test & script won't get built and Slither will then not process that code.
> > 
> > 
> > I tried forge build --build-info --skip '_/test/**' '_/script/**' as below - name: Build the contracts run: | pnpm run build forge build --build-info --skip 'packages/tokamak/contracts-bedrock/scripts' 'packages/contracts-bedrock/test' still same error occurs as above.
> > Have I done something wrong?
> 
> please try again, removing `pnpm run build` and keeping the asterisks on the forge invocation. You're likely running forge from within `packages/tokamak/contracts-bedrock` so the expanded paths you tried with won't match, and any previous forge runs launched from pnpm may generate artifacts that trigger the issue.

I appreciate your help! 

    - name: Build the contracts
      run: |
        cd packages/tokamak/contracts-bedrock
        forge build --build-info --skip '/test/**' '/scripts/**'

I attempted to follow your instructions as provided, yet the error persists as indicated below. Could you please elucidate why this error arises specifically in the presence of the "--ignore-compile" option, whereas it does not manifest in its absence?

--ignore-compile used, if something goes wrong, consider removing the ignore compile flag
ERROR:ContractSolcParsing:Impossible to generate IR for LibSort._toInts (scripts/libraries/LibSort.sol#469-474):
 'str' object has no attribute 'type'
ERROR:SlitherSolcParsing:
Failed to generate IR for LivenessGuard_TestInit._initializeSafeTools. Please open an issue https://github.com/crytic/slither/issues.
LivenessGuard_TestInit._initializeSafeTools (test/safe-tools/SafeTestTools.sol#509-513):
 	singleton = new GnosisSafe()
	proxyFactory = new GnosisSafeProxyFactory()
	handler = new CompatibilityFallbackHandler()
Traceback (most recent call last):
  File "/opt/slither/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 735, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 841, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 146, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 166, in _init_parsing_and_analyses
    raise e
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 162, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 539, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 765, in _convert_to_slithir
    raise e
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 750, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/slither/lib/python3.9/site-packages/slither/core/declarations/function.py", line [177](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:14:178)2, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/slither/lib/python3.9/site-packages/slither/core/cfg/node.py", line 716, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node, is_solidity)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line [203](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:14:204)3, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 529, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/opt/slither/lib/python3.9/site-packages/slither/slithir/convert.py", line 875, in propagate_types
    assert contract
AssertionError

**Comment by AaronLee22** [comment]
this is the log for Build the contracts

Run cd packages/tokamak/contracts-bedrock
  cd packages/tokamak/contracts-bedrock
  forge build --build-info --skip '/test/**' '/scripts/**'
  shell: /usr/bin/bash -e {0}
installing solc version "0.8.19"
Successfully installed solc 0.8.19
installing solc version "0.8.[2](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:2)[3](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:3)"
Successfully installed solc 0.8.23
installing solc version "0.8.15"
Successfully installed solc 0.8.15
installing solc version "0.5.17"
Successfully installed solc 0.5.17
Compiling 1 files with 0.5.17
Compiling 3[4](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:4) files with 0.8.19
Compiling 300 files with 0.8.1[5](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:6)
Compiling 114 files with 0.8.23
Solc 0.5.17 finished in 47.42ms
Solc 0.8.19 finished in 4.29s
Solc 0.8.23 finished in [6](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:7).91s
Solc 0.[8](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:9).15 finished in 111.4[9](https://github.com/tokamak-network/tokamak-titan-canyon/actions/runs/8181376368/job/22371051271#step:11:10)s
Compiler run successful!

**Comment by elopez** [comment]
> ```
> - name: Build the contracts
>   run: |
>     cd packages/tokamak/contracts-bedrock
>     forge build --build-info --skip '/test/**' '/scripts/**'
> ```
> 
> I attempted to follow your instructions as provided, yet the error persists as indicated below. Could you please elucidate why this error arises specifically in the presence of the "--ignore-compile" option, whereas it does not manifest in its absence?
> 

Hi! It looks like you're still missing the asterisks at the beginning, please have another look at my message here: https://github.com/crytic/slither/issues/2354#issuecomment-1979937142

**Comment by AaronLee22** [comment]
> > ```
> > - name: Build the contracts
> >   run: |
> >     cd packages/tokamak/contracts-bedrock
> >     forge build --build-info --skip '/test/**' '/scripts/**'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I attempted to follow your instructions as provided, yet the error persists as indicated below. Could you please elucidate why this error arises specifically in the presence of the "--ignore-compile" option, whereas it does not manifest in its absence?
> 
> Hi! It looks like you're still missing the asterisks at the beginning, please have another look at my message here: [#2354 (comment)](https://github.com/crytic/slither/issues/2354#issuecomment-1979937142)

Wow it works now!! By the way can you tell me the reason why the [Failed to generate IR] error occurs? I don't really want to except any of the contracts.

Thanks again

**Comment by elopez** [comment]
I don't know what's causing the underlying issue with IR generation here. If your repository is public and you can share a link with us, that might help triage this bug further.

**Comment by AaronLee22** [comment]
Here are the smart contract links that's having this issue. 

https://github.com/tokamak-network/tokamak-titan-canyon/blob/main/packages/tokamak/contracts-bedrock/scripts/libraries/LibSort.sol

https://github.com/tokamak-network/tokamak-titan-canyon/blob/main/packages/tokamak/contracts-bedrock/test/safe-tools/SafeTestTools.sol

Thank you for helping me solve this issue!

**Comment by 0xalpharush** [comment]
I am pretty sure that the `assert contract` failure is caused by the [use of alias in the import ](https://github.com/tokamak-network/tokamak-titan-canyon/blob/2cc27962f70568475a93306030c27312950d814b/packages/tokamak/contracts-bedrock/test/safe-tools/SafeTestTools.sol#L7) 

The need to support this is tracked in https://github.com/crytic/slither/issues/1452

**Comment by 0xalpharush** [comment]
@aviggiano Would you open a new issue with the full stack trace and show the output of adding `--disallow-partial` please? To be clear, `ignore-compile` will prevent slither for running the build command and use whatever artifacts on disk, meaning they could be incomplete (bc of some filtering or partial compilation) or include `scripts` or `tests` which is where the bug may be present (which we skip by default)
