### ISSUE TITLE
Typical logging output should be included in JSON

### ISSUE THREAD

**Issue by yxliang01** [crytic/slither#247]
It's great that now Slither natively supports outputting JSON format output to STDOUT. However, all the logs are disabled in this mode. I think that it's better to all logs go to STDERR in this mode, so that the STDOUT still only has a clean JSON output and logs are still being printed to terminal without interfering with the STDOUT JSON output.

Thanks

**Comment by Xenomega** [comment]
Hello @yxliang01. This is an interesting suggestion. To help evaluate all possible solutions, what is your use case? 

My thoughts are that there shouldn't be a need to mix JSON and log output: 
- I'd prefer not to mix/switch output descriptors if we can, as that may create ambiguity between stdout and the `error` field of the JSON output. Beyond that, the output wouldn't appear to be uniform, mixing logs and JSON.
- If you aim to print to a readable console, I assume you likely are not interested in readings logs and then copying out the JSON output out by hand, or this seems unintuitive instead of just outputting to file (which will output logs as expected). 
- If the aim is instead for external tooling to be able to obtain JSON + output logs in a single run, it may be better to include the logs within a field in the JSON. 
  - We probably want this data in the JSON anyways.
  - It's less ambiguous to understand the output, and doesn't change existing conventions.

Though it is possible I'm missing some use case you have for this. Would the last major bullet points satisfy your needs?

**Comment by yxliang01** [comment]
It's mainly the third use case that is relevant to me that the Slither logs are collected and stored as logs of other systems. In my case, the invoking system doesn't really need to parse the logs from Slither, it's just simple forwarding. While for most of the time, the logs from Slither can be reconstructed from the JSON output, having such conversion mechanism is not as good as reusing the existing one in Slither. One point to aware is that the compilation warning messages are not in the JSON output currently, so that information can't be retrieved without having Slither printing it(It's doesn't look like printed via `logging` module though).

**Comment by Xenomega** [comment]
Ah, okay, great to hear. I agree, it's important the original log output be included in the JSON output for external tooling. I'll update the title of your issue, and we'll be tracking it accordingly. Thank you for your contribution!

**Comment by yxliang01** [comment]
Thanks for that @Xenomega . But, actually my point was two-fold,
1. Include all logging output information in the JSON output
2. Retain the human-readable version of the logging output (didn't address by your comment)

**Comment by Xenomega** [comment]
@yxliang01 Just to clarify: the logging output information I would aim to include in JSON would be a single string field of the same human-readable output you would see in a traditional slither run. We would simply capture typical output and put it into a JSON field. External tools would then access the field and could print it themselves, in the same human-readable format slither would typically output.

However, if I understand correctly, you're instead interested in obtaining the JSON over stdout, but do not want to access the logging output string via JSON + save it yourself? Instead you'd like to redirect/forward stderr directly to a file to avoid adding logic to your program to save it? If that's the case, and my proposed solution is not ideal, I will look into this for you. My apologies for any misunderstanding.

**Comment by yxliang01** [comment]
@Xenomega I think your first proposal (all human-readable log go into a JSON field) looks promising. It's a good solution for my use case. But, broadly speaking, current JSON output is quite big since it includes all the background information regarding the vulnerabilities found, so unsure whether you want to further make it bigger.

**Comment by Xenomega** [comment]
@yxliang01 Recent updates to JSON output allow multiple types of results to be included under a `results` field in JSON. Detector JSON output is under `results`->`detectors` for instance. We can add another flag to include logging output in `results`->`detector_output` for example, so it is not always bloating the JSON output. The idea behind these recent changes is that we can specify multiple output options, and return a single JSON result with all requested information embedded in it.

I think I'd go in that direction^, but I'll do a deeper evaluation for what is best when I begin to dig into the issue. Thank you for clarifying your use case and opening up this issue, it's greatly appreciated.

**Comment by yxliang01** [comment]
Thanks, in that case, I think that direction is great! Happy to see it happen sometime later :)

**Comment by montyly** [comment]
I think the issue is now fixed with https://github.com/crytic/slither/pull/266 ?

I am keeping the issue open until we update the document: https://github.com/crytic/slither/wiki/JSON-output

**Comment by yxliang01** [comment]
@montyly From the description, looks like #266 indeed resolves this issue, although I haven't got a chance to check it. But, in any case I believe this issue can be closed after adding the documentation. Thanks @montyly and @Xenomega

**Comment by montyly** [comment]
This wiki was updated, so I am closing this issue
