### ISSUE TITLE
Bug in variable-order printer

### ISSUE THREAD

**Issue by sobolev-igor** [crytic/slither#250]
Hi there!

I was testing `variable-order` printer and found the following. Consider there are base contract and derived one and they both have variables with the same name. Thus, the derived contract has two state variables, but Slither does not indicate it. Example contract:
```
pragma solidity 0.4.25;

contract BaseContract {
    address internal owner;

    constructor() public {
        owner = msg.sender;
    }
    
    function ownerBase() public view returns (address) {
        return owner;
    }
    
}

contract DerivedContract is BaseContract {
    address public owner;

    function owners() public view returns (address, address) {
        return (owner, super.ownerBase());
    }

}
```

Slither output:
```
$ slither DerivedContract.sol --print variable-order
INFO:Printers:
DerivedContract:
+-------+---------+
|  Name |   Type  |
+-------+---------+
| owner | address |
+-------+---------+

INFO:Slither:DerivedContract.sol analyzed (2 contracts)
```

**Comment by montyly** [comment]
Hi @sobolev-igor, it's a good catch! thank you for reporting the issue, we are going to investigate how to fix it.

**Comment by montyly** [comment]
Hi @sobolev-igor, it should be fixed in `master`. Additionally, the printer prints now the canonical name of the variable, to avoid confusion.

Let us know if you have other issues.

**Comment by sobolev-igor** [comment]
Thanks for the quick response!
