### ISSUE TITLE
Extra buggy solc versions defined

### ISSUE THREAD

**Issue by joevanloon** [crytic/slither#2505]
3 solc versions are included as "buggy versions":
https://github.com/crytic/slither/blob/9a5b4f5cff9db6475c5badff18f9882180d5f344/slither/utils/buggy_versions.py#L1585-L1587

However, they have no reasoning attached because there are no lingering bugs with these versions: https://docs.soliditylang.org/en/latest/bugs.html

The "incorrect solc" detector erroneously flags these entries, because it is only checking for existence in the map:
https://github.com/crytic/slither/blob/9a5b4f5cff9db6475c5badff18f9882180d5f344/slither/detectors/attributes/incorrect_solc.py#L74C30-L74C45

These should either be removed, or the detector should filter the checked version list to just the entries that contain a non-empty list of bugs.

**Comment by 0xalpharush** [comment]
This was fixed here https://github.com/crytic/slither/pull/2499. I will cut a release today
