### ISSUE TITLE
[Bug-Candidate]: Incomplete documentation for config files

### ISSUE THREAD

**Issue by cb-elileers** [crytic/slither#2512]
### Describe the issue:

The Slither wiki docs on configuration files is incomplete: https://github.com/crytic/slither/wiki/Usage#configuration-file

Full list of accepted flags (from source): https://github.com/crytic/slither/blob/master/slither/utils/command_line.py#L41

Noticed it when I needed to add skip_assembly from another issue solution.

### Code example to reproduce the issue:

https://github.com/crytic/slither/wiki/Usage#configuration-file
https://github.com/crytic/slither/blob/master/slither/utils/command_line.py#L41

### Version:

N/A

**Comment by 0xalpharush** [comment]
Thanks for pointing this out! I updated the wiki. We will migrate away from Github wiki soon so that people can submit PR's and it can be updated in conjunction with code.
