### ISSUE TITLE
[Bug-Candidate]:  Infunctional with the Base mainet

### ISSUE THREAD

**Issue by reverse-banana** [crytic/slither#2516]
### Describe the issue:

The tools isn't working with the base mainet

### Code example to reproduce the issue:

slither 0x58b2F2Bb66073e04363fEea744409951D641F2D6 --base-apikey Q4Y5IN9AEMI3JNSP4V3472QIPKS2ZHKVIX7

Output: 
Invalid etherscan API Key 
ERROR:Slither:Unable to compile all targets.

### Version:

0.10.3

**Comment by elopez** [comment]
Hi, thanks for the report. I see you used an address without a prefix, which defaults to mainnet ethereum. You need to specify a prefix if you would like to target something that is not on mainnet ethereum, e.g. to target the contract on Base:

```
slither base:0x58b2F2Bb66073e04363fEea744409951D641F2D6 --base-apikey YOUR_KEY
```

**Comment by reverse-banana** [comment]
@elopez  thank you, my bad, have a great day!
