### ISSUE TITLE
Detector external-function reports functions whose parameters are written-to in function body.

### ISSUE THREAD

**Issue by rajeevgopalakrishna** [crytic/slither#255]
If a public-visibility function's parameters are written-to in function body then such a function's visibility cannot be converted to external because external function's parameters are allocated in calldata region which is non-modifiable (see https://solidity.readthedocs.io/en/develop/types.html#data-location).

The `external-function` detector lacks this check.

**Comment by montyly** [comment]
Fixed with #257
