### ISSUE TITLE
All detector results should have at least one element

### ISSUE THREAD

**Issue by Xenomega** [crytic/slither#258]
All detectors should output results with at least one source mapping item in its `elements`.

Formally:
- Assert that a result has at least one item in `elements`.
- Add a new element type for `other`, or `generic`. (From this point on, I will call these element types 'generic')
- Provide a JSON function to create a generic element type:
  - `add_generic_to_json(filename, start, end, json)`: Adds a generic element type to the JSON with source mapping to the given position in a file.
- Make the `rtlo` detector return a generic source mapping, even if its just to start = 0, end = 0.

**Comment by montyly** [comment]
Fixed with https://github.com/crytic/slither/pull/263
