### ISSUE TITLE
False alert in naming-convention detector on undeclared parameter name.

### ISSUE THREAD

**Issue by rajeevgopalakrishna** [crytic/slither#259]
The Cryptokitties core contract `0x06012c8cf97bead5deae237070f9587f8e7a266d_KittyCore.sol` misses the string type's parameter name in the below function:
```
function getMetadata(uint256 _tokenId, string) public view returns (bytes32[4] buffer, uint256 count)
```
The `naming-convention` detector reports a false alarm about converting the empty string parameter name to mixedCase.

Looks like a bug in the contract but Slither could filter out this `naming-convention` alert.

**Comment by montyly** [comment]
Fixed with #260
