### ISSUE TITLE
Automatically set correct compiler version when instantiating Slither

### ISSUE THREAD

**Issue by Yustynn** [crytic/slither#2595]
### Describe the desired feature

I'd like the version to be auto-detected (e.g. from the `solidity` pragma) and set. Maybe I'm doing it wrong, but currently I had to write non-slither code to do this for me.

Use case: I'm doing analysis on many contracts of different compiler versions.

Is this feature desirable? Idm making a PR if yes, would appreciate any guidance on implementation if you have preferences

**Comment by elopez** [comment]
Hi! crytic-compile already offers this functionality of "guessing" the solc version. You need to list the allowed and installed versions in the `solc_solcs_select` / `--solc-solcs-select` option when running Slither or crytic-compile.

https://github.com/crytic/crytic-compile/blob/20df04f37af723eaa7fa56dc2c80169776f3bc4d/crytic_compile/platform/solc.py#L713-L733

Additionally, if you're pulling code from Etherscan, we'll fetch the version number that was used for verification there so there's no need to be guessing.

**Comment by Yustynn** [comment]
Ah that's great, thanks :)

**Comment by webgit63** [comment]
Hi 
I am really lost in all this.
I been trying for a year to find 
out if any of this is real.
I keep getting transactions sent 
From Ethplorer ….
Anyone here that can help,
I would truly appreciate it 

Wayne Brown

**Comment by hastalamuerte** [comment]
Hello, still dont understand how it can be implemented in slither . For example  i have a lot of sol files and want to check em all, slither will not auto guess a solc version.
Help plz, @Yustynn , maybe you find a way to autoset a solc with slither . I saw yours https://github.com/Yustynn/ethereum-smart-contract-analysis/blob/main/solc_select_api.py but its kind of another one. 
I install solc-select all .

**Comment by hastalamuerte** [comment]
> If you have multiple **independent** solidity files (i.e. multiple projects/deployments) that you need to scan, you can run slither on each of them independently, and use `--solc-solcs-select` to list all possible solc versions that Slither should try to build with. Each of those compiler versions will be tried until one is found that can build the code. But remember you cannot compile code meant for two different compile versions in one single incantation.

Yep , exactly that way . I was dig into Crytic and its more for build with audit options. 
Now i trying to use --solc-solcs-select with *all* argument . but ..
```
(slither-env) root@DESKTOP-OHFBCPV:/home/zeta# slither /mnt/c/Users/Admin/Desktop/MyToken.sol --solc-solcs-select all
'solc --version' running
Traceback (most recent call last):
  File "/home/zeta/slither-env/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/slither/__main__.py", line 776, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/zeta/slither-env/lib/python3.12/site-packages/slither/__main__.py", line 882, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/slither/__main__.py", line 96, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 722, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 211, in init
    self._compile(**kwargs)
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 633, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/platform/solc.py", line 268, in _get_targets_json
    return _run_solcs_env(
           ^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/crytic_compile/platform/solc.py", line 757, in _run_solcs_env
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation, none of the solc versions provided worked:
all:
Solidity version not found:
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/home/zeta/slither-env/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/solc_select/__main__.py", line 87, in solc
    res = current_version()
          ^^^^^^^^^^^^^^^^^
  File "/home/zeta/slither-env/lib/python3.12/site-packages/solc_select/solc_select.py", line 72, in current_version
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError:
Version 'all' not installed (set by SOLC_VERSION).
Run solc-select install all.
Or use one of the following versions: ['0.4.0', '0.4.1', '0.4.10', '0.4.11', '0.4.12', '0.4.13', '0.4.14', '0.4.15', '0.4.16', '0.4.17', '0.4.18', '0.4.19', '0.4.2', '0.4.20', '0.4.21', '0.4.22', '0.4.23', '0.4.24', '0.4.25', '0.4.26', '0.4.3', '0.4.4', '0.4.5', '0.4.6', '0.4.7', '0.4.8', '0.4.9', '0.5.0', '0.5.1', '0.5.10', '0.5.11', '0.5.12', '0.5.13', '0.5.14', '0.5.15', '0.5.16', '0.5.17', '0.5.2', '0.5.3', '0.5.4', '0.5.5', '0.5.6', '0.5.7', '0.5.8', '0.5.9', '0.6.0', '0.6.1', '0.6.10', '0.6.11', '0.6.12', '0.6.2', '0.6.3', '0.6.4', '0.6.5', '0.6.6', '0.6.7', '0.6.8', '0.6.9', '0.7.0', '0.7.1', '0.7.2', '0.7.3', '0.7.4', '0.7.5', '0.7.6', '0.8.0', '0.8.1', '0.8.10', '0.8.11', '0.8.12', '0.8.13', '0.8.14', '0.8.15', '0.8.16', '0.8.17', '0.8.18', '0.8.19', '0.8.2', '0.8.20', '0.8.21', '0.8.22', '0.8.23', '0.8.24', '0.8.25', '0.8.26', '0.8.27', '0.8.28', '0.8.29', '0.8.3', '0.8.4', '0.8.5', '0.8.6', '0.8.7', '0.8.8', '0.8.9']
```
Even if i allready run a **solc-select install all** 


Maybe there is a way to add some kind of pre parser wich will check a set/use right version of SOLC by just pasing a pragma line in contract. `pragma solidity ^*.*.*; ` Cause it might be faster than check all versions till found right, one by one

**Comment by elopez** [comment]
`all` is not a valid version. You need to specify versions that you want to potentially use, separated by commas. e.g. `--solc-solcs-select 0.4.0,0.4.1,0.4.10` (add as many as you have/need, you can check `solc-select versions` to see available ones)
