### ISSUE TITLE
can slither provide bytecode support?

### ISSUE THREAD

**Issue by ChuangLiu727** [crytic/slither#262]
thank you

**Comment by montyly** [comment]
Hi @ChuangLiu727,

Sure we can! Could you describe your need? 

For info, you can already access it through the [`crytic_compile`](https://github.com/crytic/crytic-compile) API (which is undocumented for now):
```solidity
// test.sol
contract MyContract{

}
```

```python
from slither import Slither

slither = Slither('test.sol')

my_contract = slither.get_contract_from_name('MyContract')

my_contract_init_bytecode = slither.crytic_compile.bytecode_init(my_contract.name)
my_contract_runtime_bytecode = slither.crytic_compile.bytecode_runtime(my_contract.name)

print(f'{my_contract}: \n- init bytecode: {my_contract_init_bytecode}\n- runtime bytecode: {my_contract_runtime_bytecode}')
```

But we could add a directly a property to the contract, like `my_contract.bytecode_runtime`.

**Comment by ChuangLiu727** [comment]
Thanks, I appreciate your help

i mean can i use slither as follow?
`slither somecontract's bytecode --json -`

**Comment by montyly** [comment]
Hi @ChuangLiu727,

Sorry, I misunderstood your question, Slither can provide the bytecode of a contract, but it does not analyze it for now. 

We plan to partially support evm assembly, but it won't be available in the short term.

**Comment by ChuangLiu727** [comment]
Thank you for your answers
