### ISSUE TITLE
Suppress detector findings with pragma-like statements/comments

### ISSUE THREAD

**Issue by Xenomega** [crytic/slither#272]
In future versions of Slither, it would be nice to suppress detector results by severity/check-type/file by using specially formatted comments or pragma-like statements which indicate to slither that certain results should be ignored.

When filtering, we would focus on the first element in the finding's `elements` json field (as that is the focal point/cause of the issue). If the mapping is between a certain region, we can ignore it. We can also optionally specify global ignores across the whole file, instead of in a specified start/stop range.

Reference:
http://www.blackwasp.co.uk/SuppressWarnings.aspx

**Comment by elenadimitrova** [comment]
I support this and even going down to the ability of ignoring specific results. This is a common problem across security analysis tools, for `mythril` we solved it with local ignores in contract files, ref https://github.com/ConsenSys/truffle-security/issues/212. Although it'll be preferable to abstract the ignores away from the contracts and into their own config file, one per tool.

**Comment by montyly** [comment]
I agree it would be nice to have this feature.

The main issue stopping us to implement it, is that Slither uses the AST output from solc, so it does not have the comment information. We are going to explore how to do it, but it will take some time before we implement a robust solution. 

In the meantime, Slither has two options that are more or less similar:
- A [triage mode](https://github.com/crytic/slither/wiki/Usage#triage-mode): You can save the results in the database, so Slither won't report the triaged bugs on the next runs. The main limitation is that for now the duplicate classification is not sophisticated, and any change in the source code (ex: a new character) might lead Slither to see previous results as new
- A [path filtering mode](https://github.com/crytic/slither/wiki/Usage#path-filtering). It does not allow narrow configuration, the main usage is to discard result from libraries.

**Comment by elenadimitrova** [comment]
The problem with triage mode is using this in CI which is where tooling like this is normally run.
Path filtering mode works to the level of isolating the entire file, but this isn't a good idea for core contracts.

Perhaps as an interim solution we can commit the triage db and let CI use that.

**Comment by elenadimitrova** [comment]
@montyly I am just trying triage mode and it seems that it doesn't honour the detectors you've chosen to run and instead asks you for _every_ message. Our contracts raise 3277 items in the logs when run without any ignores so this is really prohibitive to use in its current state. Is there a way to triage only issues from detectors of choice?

**Comment by montyly** [comment]
Sure, can you share your command line?

I tested the following on https://github.com/JoinColony/colonyNetwork:

```
colonyNetwork$ slither . --truffle-ignore-compile --exclude-low --exclude-informational --exclude-medium --exclude uninitialized-state --triage-mode
INFO:Detectors:
0: Reentrancy in ColonyFunding.processPayout (ColonyFunding.sol#434-460):
	External calls:
	- fee = calculateNetworkFeeForPayout(payout) (ColonyFunding.sol#438)
	- metaColonyAddress = colonyNetworkContract.getMetaColony() (ColonyFunding.sol#446)
	- payoutToken.transfer(user,remainder) (ColonyFunding.sol#453)
	- payoutToken.transfer(colonyNetworkAddress,fee) (ColonyFunding.sol#454)
	External calls sending eth:
	- user.transfer(remainder) (ColonyFunding.sol#443)
	- metaColonyAddress.transfer(fee) (ColonyFunding.sol#447)
	State variables written after the call(s):
	- fundingPots (ColonyFunding.sol#457)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities
Results to hide during next runs: "0,1,..." or "All" (enter to not hide results): 
INFO:Detectors:
0: ReputationMiningCycle.confirmNewHash (ReputationMiningCycle.sol#204-218) allows anyone to destruct the contract
1: DutchAuction.destruct (ColonyNetworkAuction.sol#254-268) allows anyone to destruct the contract
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#suicidal
Results to hide during next runs: "0,1,..." or "All" (enter to not hide results): All
INFO:Slither:. analyzed (64 contracts), 1 result(s) found
```

The file `slither.db.json` was generated, and a next run of slither, without the `triage-mode` will hide the two first results:
```
$ slither . --truffle-ignore-compile --exclude-low --exclude-informational --exclude-medium --exclude uninitialized-state 
INFO:Detectors:
Reentrancy in ColonyFunding.processPayout (ColonyFunding.sol#434-460):
	External calls:
	- fee = calculateNetworkFeeForPayout(payout) (ColonyFunding.sol#438)
	- metaColonyAddress = colonyNetworkContract.getMetaColony() (ColonyFunding.sol#446)
	- payoutToken.transfer(user,remainder) (ColonyFunding.sol#453)
	- payoutToken.transfer(colonyNetworkAddress,fee) (ColonyFunding.sol#454)
	External calls sending eth:
	- user.transfer(remainder) (ColonyFunding.sol#443)
	- metaColonyAddress.transfer(fee) (ColonyFunding.sol#447)
	State variables written after the call(s):
	- fundingPots (ColonyFunding.sol#457)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities
INFO:Slither:. analyzed (64 contracts), 1 result(s) found
```

**Comment by Xenomega** [comment]
My thoughts for implementing this would've been to find a specific type of expression/marker in a comment (almost like regex, but not with regex exactly, because you need to count open/closed boundaries).

Once you have the boundaries for the open/close statements, you could then just ignore any findings whose first element (the most significant element) is mapped into that range. This would bypass the need for AST entirely.

**Comment by josh-richardson** [comment]
I've built out a rather naive implementation of this [here](https://github.com/josh-richardson/slither/pull/1). It may be that I've taken the wrong approach and there's a more slither-ish way of doing things, I'm a bit of a newcomer to the project. Comments & suggestions welcome - if it's well received I'll open a PR. Thanks!

**Comment by montyly** [comment]
This is awesome @josh-richardson, thanks for working on it. I was hoping that we would end up having the comments in the AST (https://github.com/ethereum/solidity/issues/1771), but I am not sure if this will (or when) will be available.

Please create a PR so we can integrate your work

**Comment by DanielVF** [comment]
The PR https://github.com/crytic/slither/pull/724 by @josh-richardson has been merged into dev.

Thanks so much folks! Inline comments for this will help us a lot since it creates easy visibility during the PR process about changes to ignores, and being inline helps understanding during code reviews.

**Comment by montyly** [comment]
Added with slither 0.7: https://github.com/crytic/slither/releases/tag/0.7.0
