### ISSUE TITLE
Improper work of naming-convention detector

### ISSUE THREAD

**Issue by sobolev-igor** [crytic/slither#287]
`naming-convention` detector acts incorrectly in case the function parameters have no name: 
```
contract ERC677 {
    function transferAndCall(address, uint, bytes) external returns (bool);
}
```
```
Parameter '' of ERC677.transferAndCall (contracts/ERC677.sol#2) is not in mixedCase
```

Moreover, it finds function arguments, which names are starting with '_'. You may consider ignoring this case as it is a common practice.

**Comment by montyly** [comment]
Hi @sobolev-igor.

Thank you for reporting the issue. We are going to fix it as soon as possible.

**Comment by sebastiantf** [comment]
I am seeing the following error by Slither action. But having leading underscores in parameters is common, and also part of the [EIP-20](https://eips.ethereum.org/EIPS/eip-20) doc

<img width="935" alt="Screenshot 2023-04-15 at 6 51 05 PM" src="https://user-images.githubusercontent.com/36922376/232226514-0b21fd44-14d1-4f17-80a5-f9c722c92213.png">
