### ISSUE TITLE
Config file not accepted

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/slither#289]
I tried both naming the file `slither.conf.json` which should be picked up automatically according to the documentation, and also explicitly passing in `--config-file slither.conf.json` to slither. Neither gave a result.

```
{
  "detectors_to_exclude": "unused-state,naming-convention,solc-version,external-function,pragma,constable-states",
  "solc_args": "--allow-path .",
  "solc_disable_warnings": true
}
```

**Comment by montyly** [comment]
Hi @elenadimitrova,

Thank you for reporting the issue! It is indeed a bug in our config file parsing. We are working on a fix in #290.

Let us know if you have any other troubles.
As a side note, `--allow-path` should be `--allow-paths`.

**Comment by montyly** [comment]
Additionally, while fixing #290 I have fixed another typo in the wiki; the default config filename is `slither.config.json`.

**Comment by elenadimitrova** [comment]
np will use command line options for now until you release the fix. Thanks for the support.

**Comment by elenadimitrova** [comment]
It doesn't seem like the triage db is picked up when config file only is being used. Am I missing an option there?
```
{
  "detectors_to_exclude": "unused-state,naming-convention,solc-version,external-function,pragma,constable-states,uninitialized-state-variables,uninitialized-local-variables,reentrancy-no-eth",
  "solc_args": "--allow-paths .",
  "solc_disable_warnings": true,
  "exclude-low": true,
  "exclude-informational": true
}
```

running `slither contracts/`

**Comment by elenadimitrova** [comment]
Just tested this here https://github.com/argentlabs/argent-contracts/pull/178/commits/11956de96554e3c5aec2333d930b6a616cd97f9a and confirming it is fixed
