### ISSUE TITLE
Broken filter-paths option

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/slither#292]
Getting back a `AttributeError: 'list' object has no attribute 'split'` error when using the `--filter-paths` option. Full results off my run below:

```
$ slither contracts/ --solc-disable-warnings --exclude-low --exclude-informational --filter-paths dappsys
INFO:Detectors:
ReputationMiningCycleStorage.colonyNetworkAddress (contracts/ReputationMiningCycleStorage.sol#31) is never initialized. It is used in:
	- checkChildReputation (contracts/ReputationMiningCycleRespond.sol#318-340)
	- checkKey (contracts/ReputationMiningCycleRespond.sol#351-361)
	- getExpectedSkillIdAndAddress (contracts/ReputationMiningCycleRespond.sol#389-417)
	- getRelativeUpdateNumber (contracts/ReputationMiningCycleRespond.sol#604-616)
	- getChildAndParentNUpdatesForLogEntry (contracts/ReputationMiningCycleRespond.sol#618-630)
ReputationMiningCycleStorage.reputationUpdateLog (contracts/ReputationMiningCycleStorage.sol#35) is never initialized. It is used in:
	- checkUserOriginReputation (contracts/ReputationMiningCycleRespond.sol#296-316)
	- checkChildReputation (contracts/ReputationMiningCycleRespond.sol#318-340)
	- checkKeyLogEntry (contracts/ReputationMiningCycleRespond.sol#370-387)
	- proveValue (contracts/ReputationMiningCycleRespond.sol#524-600)
	- getChildAndParentNUpdatesForLogEntry (contracts/ReputationMiningCycleRespond.sol#618-630)
ReputationMiningCycleStorage.reputationHashSubmissions (contracts/ReputationMiningCycleStorage.sol#38) is never initialized. It is used in:
	- checkAdjacentReputation (contracts/ReputationMiningCycleRespond.sol#183-244)
	- confirmChallengeCompleted (contracts/ReputationMiningCycleRespond.sol#342-349)
	- proveBeforeReputationValue (contracts/ReputationMiningCycleRespond.sol#419-459)
	- proveAfterReputationValue (contracts/ReputationMiningCycleRespond.sol#461-489)
	- checkPreviousReputationInState (contracts/ReputationMiningCycleRespond.sol#632-655)
	- checkUserOriginReputationInState (contracts/ReputationMiningCycleRespond.sol#666-723)
	- checkChildReputationInState (contracts/ReputationMiningCycleRespond.sol#725-780)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-state-variables
INFO:Detectors:
ReputationMiningCycleRespond.buildReputationKey (contracts/ReputationMiningCycleRespond.sol#793-801) is declared view but contains assembly code
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#constant-functions-changing-the-state
INFO:Detectors:
Reentrancy in ReputationMiningCycleRespond.respondToChallenge (contracts/ReputationMiningCycleRespond.sol#103-177):
	External calls:
	- checkKey(u,b32) (contracts/ReputationMiningCycleRespond.sol#136)
	- performReputationCalculation(u) (contracts/ReputationMiningCycleRespond.sol#146)
	- checkChildReputation(u,b32,agreeStateSiblings,childReputationSiblings) (contracts/ReputationMiningCycleRespond.sol#153)
	State variables written after the call(s):
	- disputeRounds (contracts/ReputationMiningCycleRespond.sol#169)
	- disputeRounds (contracts/ReputationMiningCycleRespond.sol#171)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1
INFO:Detectors:
branchNode in Data.insertAtEdge (contracts/PatriciaTree/Data.sol#105) is a local variable never initialiazed
edgeHashes in PatriciaTreeProofs.getImpliedRootFunctionality (contracts/PatriciaTree/PatriciaTreeProofs.sol#44) is a local variable never initialiazed
e in PatriciaTreeProofs.getImpliedRootFunctionality (contracts/PatriciaTree/PatriciaTreeProofs.sol#42) is a local variable never initialiazed
nChildUpdates in ReputationMiningCycleRespond.getChildAndParentNUpdatesForLogEntry (contracts/ReputationMiningCycleRespond.sol#622) is a local variable never initialiazed
e in Data.insert (contracts/PatriciaTree/Data.sol#70) is a local variable never initialiazed
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables
ERROR:root:Error in contracts/
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 582, in main_impl
    (results_tmp, number_contracts_tmp) = process(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 48, in process
    args.filter_paths = parse_filter_paths(args)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 253, in parse_filter_paths
    return args.filter_paths.split(',')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by montyly** [comment]
Hi @elenadimitrova,

Thank you for reporting this other issue. The issue only occurs when analyzing raw directory and is now fixed in https://github.com/crytic/slither/pull/290.

In the meantime, you can have Slither 0.6.4 working with `--filter-paths` if you give as a target the "main directory" of your truffle project (`.` instead of `contracts/`) .

For info, as you are analyzing a raw directory, Slither analyses each file separately, and you will have numerous duplicates. If you analyze the "main directory", Slither will rely on the truffle output and will not report dupplicate.

**Comment by elenadimitrova** [comment]
I have a problem with using the main directory even after ignoring the path below it throws on it

`slither . --filter-paths dappsys,openzeppelin-solidity`
returns:

```
ERROR:root:Error:
ERROR:root:Invalid compilation:
Unknown file: /home/nventuro/dev/openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues`
```

**Comment by montyly** [comment]
Could you share the full steps to reproduce the issue?
I tried with
```
$ git clone https://github.com/JoinColony/colonyNetwork
$ cd colonyNetwork/

**Comment by montyly** [comment]
Could you share the full steps to reproduce the issue?
I tried the following with success:
```
$ git clone https://github.com/JoinColony/colonyNetwork
$ cd colonyNetwork/
$ npm install
$ git submodule update --init
$ slither . --filter-paths dappsys,openzeppelin-solidity
```
Thanks!

**Comment by elenadimitrova** [comment]
Can you add `yarn run provision:token:contracts" after the `git submodule update --init` run?

**Comment by montyly** [comment]
Thanks! I have another issue:
```
ERROR:root:Error:
ERROR:root:Invalid compilation: 
Unknown file: /Users/Elena/colonyToken/contracts/Token.sol
```

The problem is that Slither needs to access to the original files, and as you are using pre-compiled files, they have incorrect absolute paths. For example in: https://github.com/JoinColony/colonyToken/blob/8e5139586018fbaa53e9cf971e040b3ae2a4bb92/build/contracts/TokenAuthority.json#L2336. 
As a result, Slither will fail from any configuration that is not you original one (ex: from a CI). The second case is coming from: https://github.com/JoinColony/colonyNetwork/blob/07ca1744484b8734c1695644a88ee4e9de22b4b6/scripts/provision-token-contracts.sh#L12

I see three options:
- Hotpatch the incorrect absolute paths in the JSONs. It should work, but it might be difficult to maintain
- Change the compilation. `colonyToken` would need to be recompiled after imported. For `ERC20Mintable`, I am not sure, would it work to import it directly as a Solidity file? (I am not sure of the purpose of the original copy)
- Allow Slither to work with unknown files. The main issue here is that it will not be possible to provide correct source mapping by doing so

What do you think?

**Comment by elenadimitrova** [comment]
My preferred option was going to be to ignore these imported contracts which I was trying to achieve with a combination of `contracts` path passed in slither explicitly and/or `--filter-paths` option.

**Comment by montyly** [comment]
For info, I have tried with a  `--paths-remapping` flag, that helps Slither finding what is the correct filename, but there is still another issue.

The object IDs generated by truffle does not match and are not referencing the same objects on all the contracts. My best guess is by doing

**Comment by montyly** [comment]
For info, I have tried with a --paths-remapping flag, that helps Slither finding what is the correct filename, but there is still another issue.

The object IDs in the AST generated by truffle does not match and are not referencing the same objects on all the contracts. My best guess is that by doing:
```
"provision:token:contracts": "truffle compile && truffle compile --contracts_directory 'lib/dappsys/[!note][!stop][!proxy][!thing][!token]*.sol' && bash ./scripts/provision-token-contracts.sh
```

Truffle does two separate compilations, where the elements of the second ones are not properly linked to the first one. Most likely it's not going to be possible to fix that without a significant amount of work.
 
It's going to be the same issue for all the json files that are copied manually.

Would running Slither on the individual directory (before running `yarn run provision:token:contracts`) be a possible solution for you?
