### ISSUE TITLE
ecrecover related bugs are not detected

### ISSUE THREAD

**Issue by HarryR** [crytic/slither#296]
## Description

It doesn't detect `ecrecover` failing upon invalid input

## How to Reproduce

See the following piece of code:

https://gist.github.com/HarryR/cce52596ffebdff2744c5d790888015a

This was caused by a compiler bug in Solidity < 0.4.14, where the output memory area for the `ecrecover` call wasn't cleared, which means in the case of an invalid signature the memory may contain user-controllable input.

If the contract address is passed in as the last 20 bytes of the 32-byte `stuff2hash` input, then the if condition will be true and the contract will send all funds to the caller.

This was recently highlighted as a problem with the 0x contracts, see: https://samczsun.com/the-0x-vulnerability-explained/

## Expected behavior

this bug should be detected

**Comment by montyly** [comment]
Hi @HarryR 

Thank you for reporting this. 

I think the best way to handle the compiler-related bugs is to update our [incorrect solc version detector](https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity), to warm better about the use of old and buggy compiler version. We will look to add more information about this issue

**Comment by HarryR** [comment]
So Slither is unable to detect compiler bugs or vulnerabilities in hand-rolled assembly?

Doesn't that severely limit the real-world usefulness of this tool?

**Comment by montyly** [comment]
Sorry if I was mistaken.
 
We can detect directly these kinds of bugs, but I think it is more efficient to look at the solidity version used, and report any version that is [known to be buggy](https://solidity.readthedocs.io/en/v0.5.10/bugs.html).

solc has a significant list of bugs, I don't see any benefit of having an individual detector for each bug versus directly reporting the buggy versions.

**Comment by HarryR** [comment]
I'm reporting specifically to projects which perform some kind of symbolic analysis rather than doing source-level static analysis, and looking for better solutions, trying to see what could be improved or finding tools which can detect the kind of bug that 0x ran into.

It would be really awesome if Slither could support inline EVM assembly, it supports taint analysis, complex conditions etc. when determining reachability of code (to trigger detectors, like `suicidal` or `arbitrary-send`), but it doesn't have a model of the memory layout at runtime which would've been necessary to detect the 0x bug.

Given that there are lots of compiler bugs, if Slither were able to map the emitted EVM output to Solidity source / IR, then it would be able to detect some types of compiler bugs or logic errors in hand-rolled assembly etc.

**Comment by montyly** [comment]
I am closing this issue; the short term solution is to rely on the solc version used
