### ISSUE TITLE
`Too many digits` detector marks `1 ether` as a too large number

### ISSUE THREAD

**Issue by eMarchenko** [crytic/slither#297]
```Solidity
MyContract.foo (...) uses literals with too many digits:
        - require(bool)(weiAmount >= 1000000000000000000)
```
but my code is 
```Solidity
require(weiAmount >= 1 ether);
```
which is very convenient.

I guess same problem should be with `weeks` multiplier.
And maybe with `1e18` values as well.

I'd prefer if the detector could exclude similar cases.

**Comment by montyly** [comment]
Hi @eMarchenko 

Thank you for reporting the issue. Indeed this should not be reported as an issue and was not previously.
We will investigate how to fix it.
