### ISSUE TITLE
How many smart contract problems can Silther detect now?

### ISSUE THREAD

**Issue by xf97** [crytic/slither#336]
Hello, I'm sorry to disturb you. I noticed that slither had documentation about which types of smart contracts were detected, but I also noticed that this document was updated a long time ago. So I want to ask, how many smart contract issues can Slither detect at the moment? We look forward to your reply.

**Comment by dguido** [comment]
The current list for Slither's open source distribution is available in the [readme](https://github.com/crytic/slither#detectors) or via `--list-detectors`: 37 issues.

The private add-on that we maintain for Slither includes an additional 30 issues.

**Comment by xf97** [comment]
Thank you for your reply. You have solved my doubts. I wish you a happy life.

在 2019-09-15 11:34:27，"Dan Guido" <notifications@github.com> 写道：


Closed #336.
