### ISSUE TITLE
Slither doesn't support all of >=4.0 versions.

### ISSUE THREAD

**Issue by hjlee9182** [crytic/slither#343]
![캡처](https://user-images.githubusercontent.com/46337218/66265306-3756b300-e84f-11e9-8e47-c65cb571a088.PNG)
(this is code from https://swcregistry.io/docs/SWC-102)

![캡처](https://user-images.githubusercontent.com/46337218/66265302-1ee69880-e84f-11e9-9a6f-84dcaffd5792.PNG)

When I use slither with >=5.0 versions was succesfull.
But when used 4.~ version is make a fail.
What  is problem?

**Comment by Xenomega** [comment]
Slither supports these versions of Solidity. The issue is that you do not have that version installed on your machine. The last excerpt of the error message you posted states "current compiler is 0.5.11[...]". You should uninstall solc 0.5.11 and install 0.4.13 in order to compile this contract.

**Comment by montyly** [comment]
Hi @hjlee9182.

I would recommend using https://github.com/crytic/solc-select to easily switch between solc version.

Alternatively, you can use the `--solc solc_path` flag if you have multiple solc binaries installed.
