### ISSUE TITLE
Add support for @0x/sol-compiler

### ISSUE THREAD

**Issue by HenryNguyen5** [crytic/slither#363]
The json @0x/sol-compiler outputs is slightly different than what solc output. It would be nice to support this as an alternative to truffle for platform independent solidity compilers, since it also has nice things like watch-mode.

Included below is a sample of JSON output for @0x/sol-compiler.
https://gist.github.com/HenryNguyen5/617f0d051f254ce89ed1ddb50907ce12

**Comment by montyly** [comment]
Hi @HenryNguyen5,

Thank you for reporting this limitation. I am tracking the issue in [`crytic-compile#50`](https://github.com/crytic/crytic-compile/issues/50), which is our compiler-parsing library.

**Comment by HenryNguyen5** [comment]
Thanks @montyly
