### ISSUE TITLE
slither-flat: Add --remove-assert

### ISSUE THREAD

**Issue by montyly** [crytic/slither#366]
`--remove-assert` will remove all the Solidity `assert` calls.

The goal is to allow developers to use `assert` to prove assertions with third-party tools (ex: Echidna), while not adding overhead with the production code

It is to be used only if the developer correctly used `assert()`, otherwise it will create bugs. Enabling the flag must produce a warning.

**Comment by EricR** [comment]
Since this directly relates to compilation, any thoughts on building this into crytic-compile instead?

**Comment by montyly** [comment]
The flattening was implemented in Slither for multiple reasons, including:
- Parsing the solc AST is a complex task. Slither supports already the parsing, including for both legacy and compact format. It supports solc from 0.4 to the latest and all the minor changes that were made in the AST format across time
- Slither has more information and allows for more complex patchings. For example, when removing the `assert`, we could emit a warning if the content of the assert triggers a side effect, like changing a state variable. This is straightforward to do thanks to SlithIR
- `crytic-compile` only goal should be to be a proxy between the different compilation platform and code analyzers. It should not have anything smart in it, otherwise, I think it would be a break in the abstraction layer

**Comment by EricR** [comment]
Thanks @montyly, that rationale all makes sense to me.

**Comment by EricR** [comment]
Unfortunately, this isn't as straight forward as it first seemed. After "patches" are applied in slither/tools/flattening/flattening.py's `_get_source_code` method, source mappings are all wrong.

Long term, I think it may be better to rework how `_get_source_code` makes modifications. As is, the only way I can think to accomplish this is to either parse the modified source again to update the mappings, which seems silly, or to keep track of all of the modifications and their resulting offsets made to `content`, which seems complex and error-prone.

**Comment by EricR** [comment]
Unfortunately, this isn't as straight forward as it first seemed. After "patches" are applied in slither/tools/flattening/flattening.py's `_get_source_code` method, Slither's source mappings are inaccurate.

Long term, I think it may be better to rework how `_get_source_code` makes modifications. As is, the only way I can think to accomplish this is to do one of the following:

* Parse the modified source again to update the mappings, which seems silly
* Keep track of all of the modifications and their resulting changes, which seems error-prone as more replacement tasks are added/modified
* Avoid source mappings all together and just use regex (yuck)

**Comment by montyly** [comment]
I think if we order the patches from the latest offset to the first one we should be fine. It's what `to_patch.sort(key=lambda x:x[0], reverse=True)` does.

`to_patch` could contain a namedtuple `(index, type)`. `type` could be 
- `public_to_external`
- `calldata_to_memory`
- `line_removal`

Just in case, we could check that there is no overlap between the `line_removal` and the others

**Comment by montyly** [comment]
Done with #386
