### ISSUE TITLE
data type size inconsistency

### ISSUE THREAD

**Issue by AnonymousMonkey2021** [crytic/slither#392]
https://github.com/crytic/slither/blob/master/slither/core/solidity_types/elementary_type.py

The size attribute is explained as "size in bits". 
However, the size for byte array, e.g. "bytes32" returns the size in byte. => 32
People may encounter issues when using the size attribute to pad their data due to confusion. 
Either the comment should be updated, or the size for byte* should be converted to bits.

**Comment by montyly** [comment]
Hi @JackHFeng.

Thank you for reporting this, the documentation is indeed wrong. We will fix it soon.

**Comment by 0xalpharush** [comment]
#968 fixes this
