### ISSUE TITLE
Spelling mistake in detector output

### ISSUE THREAD

**Issue by nicholashc** [crytic/slither#398]
The `uninitialized-local` and `uninitialized-storage` detectors each have a minor spelling mistake in their output. The word *initiali~a~zed* is misspelled.

**Current output**

```(tests/uninitialized_local_variable.sol#4) is a local variable never initialiazed```
```(tests/uninitialized_storage_pointer.sol#10) is a storage variable never initialiazed```

**Expected output**

```(tests/uninitialized_local_variable.sol#4) is a local variable never initialized```
```(tests/uninitialized_storage_pointer.sol#10) is a storage variable never initialized```

**Comment by montyly** [comment]
Hi @nicholashc.

Good catch, thank you for reporting this, I will fix it soon.

**Comment by montyly** [comment]
This was fixed with https://github.com/crytic/slither/pull/414 and is present in 0.6.10
