### ISSUE TITLE
Add support for 0.6 features

### ISSUE THREAD

**Issue by montyly** [crytic/slither#405]
https://solidity.readthedocs.io/en/v0.6.3/060-breaking-changes.html#solidity-v0-6-0-breaking-changes

Among others:
- Functions override (`virtual` , `override`)
- `abstract` contract
- `receive` / fallback function
- `payable` type conversion
- try/catch statement

**Comment by elenadimitrova** [comment]
Just got a false positive for the following try/catch statement we added:
```
        uint256 decimals;
        try IERC20Extended(_token).decimals() returns (uint _decimals) {
            decimals = _decimals;
        } 
        catch (bytes memory /*lowLevelData*/) {
        }
```
Error:
```
TokenPriceProvider.getEtherValue(uint256,address) (modules/common/TokenPriceProvider.sol#33-46) ignores return value by IERC20Extended(_token).decimals() (modules/common/TokenPriceProvider.sol#36-41)
```

**Comment by montyly** [comment]
Hi @elenadimitrova . Thanks for reporting this. I am tracking it in #511, and will fix it as soon as possible.
