### ISSUE TITLE
Please Support New Value Syntax

### ISSUE THREAD

**Issue by ferittuncer** [crytic/slither#419]
https://github.com/ethereum/solidity/issues/8147

**Comment by montyly** [comment]
Hi @ferittuncer, thank you for reporting this.

The minimal example:

```solidity
contract C {
    function g() external payable {}
    function f() public payable {
        this.g{value: 42, gas: 23}();
    }
}
```

This syntax was added with [0.6.2](https://github.com/ethereum/solidity/releases/tag/v0.6.2). 

I will look to add its support

**Comment by montyly** [comment]
Hi @ferittuncer, we have added its support in #424. It is now in `master`, and will be available on the next pypi release
