### ISSUE TITLE
Incorrect handling of continue statement in Slither CFG

### ISSUE THREAD

**Issue by aaronyoo** [crytic/slither#435]
Consider the following function snippet (a contrived example, but it continue is a relatively common pattern I think):
```solidity
function f(uint input) public {
    for (uint i = 0; i < input; i++) {
        if (i == 0) {
            continue;
        }
        a = a + 1;
    }
}
```

Slither produces the following CFG:
![image](https://user-images.githubusercontent.com/11811606/78927043-069c4400-7a53-11ea-9bdf-1c2ed8a005e3.png)
I am pretty sure this is wrong because of the edge from `CONTINUE --> BEGIN_LOOP`. I think it should be `CONTINUE --> EXPRESSION i++`.  Otherwise, this graph implies that taking continue would lead to an infinite loop, which it does not. I think the problem is that we are jumping to the beginning of the loop and not the increment.

Furthermore I have found that the following different program gives the exact same CFG:
```solidity
 function f(uint input) public {
    for (uint i = 0; i < input;) {
        if (i == 0) {
            continue;
        }
        a = a + 1;
        i++;
    }
}
```

In this case, Slither is correct because taking the continue would imply an infinite loop (because the increment would be skipped).

---

I have looked around at Slither's internal representation but there appears to be nothing that indicates whether the statement is part of the loop header or not. This means that the problem is that Slither cannot distinguish between the above two programs because it does not know whether the i++ is part of the loop header or not. I looked at the solc-ast for this program briefly but I couldn't find anything that would solve this.

**Comment by duckki** [comment]
As I read the code, in most cases, a loop jumps back to the immediate son of the STARTLOOP node. It should be a sole son, which is either a loop condition or do-while body.
The exception is for-loops without conditions, in which case the loop jumps back to the STARTLOOP node itself.

I think there are two possible solutions:
1) When there is no condition in a for-loop, add an no-op EXPRESSION node as a son of STARTLOOP node before the for-loop body.
2) Record the for-loop-no-condition flag in the STARTLOOP node somehow.

Either way, `_fix_continue_node` should be able to patch the back-edge correctly.
