### ISSUE TITLE
zsh: permission denied: slither

### ISSUE THREAD

**Issue by anhdungle93** [crytic/slither#470]
Machine: MacOS Catalina
I managed to install slither-analyzer with pip3 
```sh
(base) anhdungle@Anhs-MacBook-Pro ~ % pip3 show slither-analyzer
Name: slither-analyzer
Version: 0.6.12
Summary: Slither is a Solidity static analysis framework written in Python 3.
Home-page: https://github.com/crytic/slither
Author: Trail of Bits
Author-email: None
License: AGPL-3.0
Location: /Users/anhdungle/Library/Python/3.7/lib/python/site-packages
Requires: pysha3, prettytable, crytic-compile
Required-by:
```

but when I try to run slither then I get 
```
zsh: permission denied: slither
```

so I tried to go to the folder location as in the information about the package and change the user access rights from `root:wheel` to `anhdungle:staff` with the command
```sh
sudo chown -R anhdungle:staff site-packages
```
but the error still persists. Thank you in advance.

**Comment by kkagill** [comment]
I'm going through the same issue, did you solve this?
