### ISSUE TITLE
Exporting types from variables sometimes produces incorrect results

### ISSUE THREAD

**Issue by samczsun** [crytic/slither#482]
(This issue is based on `dev-0.7`, not master)

An array of mappings is not handled, resulting in an incorrect signature
| Type | Expected | Actual |
| --- | --- | --- |
|`mapping(uint => address)[] public arrayOfMappings` | `arrayOfMappings(uint256,uint256)` | `arrayOfMappings(uint256)` |

An enum (since Solidity 0.6.3) as a map key is not handled, resulting in an incorrect signature (note that the width of the key is the smallest `uint[n]` type that can fit all of the enum values.
| Type | Expected | Actual |
| --- | --- | ---|
|`mapping(State => uint) public stateMap`|`stateMap(uint[n])`|`stateMap(Contract.State)`|

A contract type (since Solidity 0.6.3) as a map key is not handled, result in an incorrect signature
| Type | Expected | Actual |
| --- | --- | ---|
|`mapping(Contract => uint) public contractMap`|`contractMap(address)`|`contractMap(Contract)`|

A multi-dimensional array will export the wrong return type
| Type | Expected | Actual |
| --- | --- | --- |
|`uint[][] public multiDimensionalArray`|`uint256`|`uint256[]`|

A struct will export the wrong return type. Note that complex types such as mappings and arrays are omitted.
<table>
<thead>
<tr>
<th>Type</th> <th>Expected</th> <th>Actual</th>
</tr>
</thead>
<tbody>
<tr>
<td>

```
struct Simple {
    uint a;
    uint b;
    mapping(uint => uint) c;
    uint[] d;
    function(uint) external returns (uint) e;
}

Simple public simple;
```

</td>
<td><code>(uint256,uint256,function)</code></td>
<td><code>(Contract.Simple)</code></td>
</tr>
</tbody>
</table>

When ABIEncoderV2 is enabled, returned structs may contain nested structs.
<table>
<thead>
<tr>
<th>Type</th> <th>Expected</th> <th>Actual</th>
</tr>
</thead>
<tbody>
<tr>
<td>

```
struct Inner {
    uint a;
    uint b;
}

struct Outer {
    Inner inner;
    uint c;
}

Outer public outer;
```

</td>
<td><code>((uint256,uint256),uint256)</code></td>
<td><code>(Contract.Outer)</code></td>
</tr>
</tbody>
</table>

**Comment by 0xalpharush** [comment]
Fixed by https://github.com/crytic/slither/pull/1323
