### ISSUE TITLE
Differentiating results between local and CI runs

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/slither#486]
Using `slither@0.6.12` we have [successfully ignored a number of detector-raised warnings](https://github.com/argentlabs/argent-contracts/pull/93) for the [argent-contracts repo](https://github.com/argentlabs/argent-contracts) however the following informational messages are being raised in Circle CI:

```
INFO:Detectors:
setName(bytes32,string) should be declared external:
	- ArgentENSResolver.setName(bytes32,string) (infrastructure/ens/ArgentENSResolver.sol#59-62)
	- ENSResolver.setName(bytes32,string) (infrastructure/ens/ENSResolver.sol#28)
addr(bytes32) should be declared external:
	- ArgentENSResolver.addr(bytes32) (infrastructure/ens/ArgentENSResolver.sol#69-71)
	- ENSResolver.addr(bytes32) (infrastructure/ens/ENSResolver.sol#25)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#public-function-that-could-be-declared-as-external
INFO:Slither:. analyzed (69 contracts with 28 detectors), 2 result(s) found
```

while not when run locally:
```
> argent-contracts@1.0.0 security:slither /Users/Elena/Source/argent-contracts
> rm -rf build && slither . --filter-paths lib --solc-disable-warnings --exclude-low --exclude-informational --exclude=naming-convention,unused-state-variables,solc-version,assembly-usage,low-level-calls
....
INFO:Slither:. analyzed (69 contracts with 28 detectors), 0 result(s) found
```

**Comment by elenadimitrova** [comment]
Providing a more fresh example from our [last night's build]( https://app.circleci.com/pipelines/github/argentlabs/argent-contracts/1503/workflows/66d1b82a-097d-4f42-b84d-9af647ae1d21/jobs/1830):

The following command `npm run security:slither:infrastructure_0.5` produces in CI:
```
INFO:Detectors:
setName(bytes32,string) should be declared external:
	- ArgentENSResolver.setName(bytes32,string) (infrastructure_0.5/ens/ArgentENSResolver.sol#59-62)
	- ENSResolver.setName(bytes32,string) (infrastructure_0.5/ens/ENSResolver.sol#28)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#public-function-that-could-be-declared-external
INFO:Slither:. analyzed (31 contracts with 28 detectors), 1 result(s) found
```

while locally we get no errors:

```
INFO:Slither:. analyzed (31 contracts with 28 detectors), 0 result(s) found
```

**Comment by elenadimitrova** [comment]
On top of this we get the same build [pass one day](https://app.circleci.com/pipelines/github/argentlabs/argent-contracts/1508/workflows/51073458-992d-442c-b23c-73c9eadbcf0a) and [fail the next](https://app.circleci.com/pipelines/github/argentlabs/argent-contracts/1515/workflows/46284e2a-da35-477b-8d92-f2044ebd7171/jobs/1841) 🤷‍♀️

**Comment by montyly** [comment]
Thanks @elenadimitrova. We are going to investigate why this happens
