### ISSUE TITLE
Support top-level structs and enums

### ISSUE THREAD

**Issue by dileepfrog** [crytic/slither#487]
The full set of allowed top-level constructs is given by the sourceUnit key here:
https://solidity.readthedocs.io/en/v0.6.8/grammar.html#language-grammar

Slither seems to only support the subset here:
https://github.com/crytic/slither/blob/master/slither/solc_parsing/slitherSolc.py#L105

**Comment by montyly** [comment]
Hi @dileepfrog, thanks for reporting this.

We will add its support asap

**Comment by montyly** [comment]
Hi @dileepfrog, top-level structs and enums are now supported in master. This support will be present in the upcoming release

**Comment by dileepfrog** [comment]
Thanks guys!!
