### ISSUE TITLE
Support to flatten into a single contract

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#495]
Related to this issue: https://github.com/crytic/slither/issues/493 and conversation with @montyly.

I'm starting to use `slither` as a replacement for `soljitsu` and `truffle-flatten`. There's 3 ways of flattening that I've seen:

1) Flatten into multiple files with dependencies in files (`slither-flat`)

Pros: no imports
Cons: contracts duplicated across files

In `soljitsu` and `truffle-flatten`, two other modes are supported:

2) Flatten into a single file

Pros: no duplication of contracts and no imports

3) Flatten into multiple files with local imports

Pros: no duplication
Cons: imports still used

Would be super helpful for my use case to at least get 2) because `dYdX` currently comes out to 100k lines of code with current `slither-flat` approach.

**Comment by montyly** [comment]
Hi @Pet3ris .
`slither-flat` was improved in #496 - it now supports all the strategies mentioned above. I updated the wiki with the new options: https://github.com/crytic/slither/wiki/Contract-Flattening

Let us know if you have any other need with `slither-flat`

**Comment by Pet3ris** [comment]
Thanks @montyly - I've already used this successfully and it works. The details are right too (e.g., pragmas are merged together, which `truffle-analyzer` doesn't do)!
