### ISSUE TITLE
Set Solidity version for emitted contracts in `slither-flat`

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#531]
Problem: Right now it seems like `slither-flat` has the ability to align Solidity versions across contract files. In some cases, it may make sense to automatically push the contract version to the latest major version, for example, from `0.5.8` to `0.5.16`.

Proposal would be to introduce a flag for `slither-flat` that can help set the pragma to be used for the contracts, e.g.,

```
slither-flat --pragma="^0.5.16" ... # I'm sure there's a nicer syntax :)
```

**Comment by montyly** [comment]
Hi @Pet3ris. We added the flag `--pragma-solidity` in (#537), it is available in master. 

Thank you for reporting this suggestion.
