### ISSUE TITLE
Incorrect support of abi.decode if the destination type is not a direct type

### ISSUE THREAD

**Issue by montyly** [crytic/slither#566]
```solidity
pragma experimental ABIEncoderV2;

contract Lib{
   struct St{
        uint v;
   }
}   

contract C{
      function f(bytes memory data) public {
            Lib.St memory s = abi.decode(data, (Lib.St));
      }   
}  
```

As we do late type conversion, and `Lib.St` is a ReferenceVariable, we don't have enough information to infer the return type of `abi.decode`

Potential solutions:
- Take the type of lvalue early on - this might not be simple as the IR relies on the late type conversion
- Use the improvement in the reference variable made on `dev-0.7` and convert the reference variable to a type directly

**Comment by 0xalpharush** [comment]
```
Contract C
	Function C.f(bytes) (*)
		Expression: s = abi.decode(data,(Lib.St))
		IRs:
			REF_1(None) -> Lib.St
			TMP_0(None) = SOLIDITY_CALL abi.decode()(data,REF_1)
			s(Lib.St) := TMP_0(None)
```
Closing as this seems fine
