### ISSUE TITLE
Reasoning for "Trusted" versions of Solidity

### ISSUE THREAD

**Issue by junderw** [crytic/slither#570]
Re: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity

I am wondering why `0.4.25 or 0.5.11` are chosen as trusted versions.

Would 0.4.26 or 0.5.17 be acceptable? (current highest patches of those minor versions)

Why are none of the 0.6.x versions included as a "trusted" version?

What are the criteria for adding / bumping the version of "trusted"? Is it based on a simple metric like time since release? Or were those two specific versions manually audited by your team members?

Sorry for all the questions. I have a project which is fairly portable between `>=0.5.0 <=0.7.0` and am wondering which version to target... I would like to use `immutable` from `>=0.6.5`, but not at the expense of some possible security issue. And after using this tool I wondered what the criteria was for "trusted versions" of the compiler.

Thanks.

**Comment by montyly** [comment]
Hi @junderw 

Thank you for these questions. We are in the process of updating our recommendations for this detector.
Our criterias include:
- The [known solidity bugs](https://solidity.readthedocs.io/en/v0.7.0/bugs.html)
- The release date of the version. With the history of bugs in the compiler, we do not recommend using any latest version for deployment, specially if changes were made in the optimizer or the language semantic

Unfortunately, we do not manually review every version of solc, as this would require too much effort on our side. However we do fuzz from time to time the compiler (see our [blogpost](https://blog.trailofbits.com/2020/06/05/breaking-the-solidity-compiler-with-a-fuzzer/) about our experience).

Note that the recommendation here is for code deployment. We do recommend to use the latest available (and compatible) to benefit from the latest warnings generated by solc. You can see more details in our guideline to [write secure contract](https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/guidelines.md#solidity) (note that the version in the guideline is also slightly out-to-date and will be updated soon)

**Comment by junderw** [comment]
Thanks for the link.

Yes, it looks like that recommendation for 0.5.x was written right after 0.6.1 was released. (0.6.0 had a bad bug that 0.6.1 fixed, not very confidence inspiring...)

Since then it's been a little over half a year, and in April 0.6.5 came out with `immutable` which is quite a big security gain if we assume the implementation of the feature itself in the compiler is not buggy.

If possible, I would try to get at least 0.6.5 on the "trusted" list just so people can use `immutable`.

Thanks for the reply.

**Comment by montyly** [comment]
Yes I agree that we need to update the recommendations to include 0.6. We will take into consideration the usage of `immutable` for our update.

**Comment by montyly** [comment]
Hi @junderw ,

We updated [our recommendations](https://github.com/crytic/slither/wiki/Detector-Documentation#recommendation-39) in https://github.com/crytic/slither/pull/577.

If you want to use the 0.6 branch, we recommend to use of of these following versions:
```
- 0.6.8,
- 0.6.10 - 0.6.11.
```

We will release a new version of slither that includes these new recommendations soon.

**Comment by junderw** [comment]
Awesome! Thanks so much!

Out of curiosity, why was 0.6.12 not included in the list? (0.6.11 is totally fine for us though)

**Comment by montyly** [comment]
We avoid recommending the latest version of a branch, especially if it was released not a long time ago. Additionally, 0.6.12 had changes in the optimizer, which increases the likelihood of having a bug.
