### ISSUE TITLE
saddle.js support for slither-flat

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#571]
Looks like `slither-flat` doesn't yet support saddle.js and therefore there doesn't seem to be an easy way to flatten the current `compound-protocol` contracts?

https://github.com/compound-finance/compound-protocol
https://github.com/compound-finance/saddle

**Workaround**

Can currently add a `truffle-config.js` file like so:

```javascript
module.exports = {
    networks: {
      development: {
        host: "127.0.0.1",
        port: 8545,
        network_id: "*" // Match any network id
      }
    }
  };
```

Which allows `slither-flat` to treat it as a truffle project.

**Comment by montyly** [comment]
Hi @Pet3ris ,

Thank you for reporting this. I wasn't aware of saddle. I opened an issue in `crytic-compile` to track its support: [crytic-compile#95](https://github.com/crytic/crytic-compile/issues/95):  (its the compilation library used by Slither)

In the meantime, you can also use the `--truffle-overwrite-config` flag, that will create a temporary `truffle-config.js` file:
```
slither-flat . --compile-force-framework Truffle --truffle-overwrite-config
```

Additionally, you can use `--truffle-overwrite-version X`, if you need to use a specific solc version (`--truffle-overwrite-version 0.5.16`)

**Comment by Pet3ris** [comment]
That's awesome @montyly - thanks.

**Comment by montyly** [comment]
I am closing this issue as it is tracked in crytic-compile#95
