### ISSUE TITLE
Add Contributor Guidelines 

### ISSUE THREAD

**Issue by benstew** [crytic/slither#59]
## Overview
To support an influx of external contributions (incentivized from Gitcoin and more organic OSS approaches), I propose adding contributor guidelines to this repo to communicate how people should contribute. This will save time for repo owners as well as contributors and help verify that PRs are well-formed and opened issues are useful.

I see two straightforward approaches that could support contributor guidelines:

1. Create a separate `CONTRIBUTING` file in the root directory
     - advantage: Obvious in the file tree. I've had success doing this for Aragon [here](https://github.com/aragon/dao-kits/blob/master/CONTRIBUTING.md)
     - disadvantage: New file. Fragments documentation across wiki and elsewhere
2. Create a new wiki Contributor Guidelines wiki entry and link to it from the `README`
     - advantage: Supports existing use of wiki for this repo. Could move to a more robust developer portal easily.
     - disadvantage: Less popular approach. Can't integrate cool things like PR templates directly.

Open to all feedback and thoughts.

### Contact Info (Slack, Email, etc)

**Comment by dguido** [comment]
We were discussing this ourselves a day or so ago. We want to make a best practices guide for what a good detector looks like and all the parts it should have. I think that's an obvious first step.

**Comment by benstew** [comment]
Thanks @dguido. Figured it was on the radar. There's definitely a lot of value in a best practices guide for detectors. I see that as one of the quickest/easiest ways to contribute. That could easily be part of the guidelines and live in the [wiki](https://github.com/trailofbits/slither/wiki). Pretty new to the codebase but let me know if you need any help with that.

Also, I still think documenting the pull request/approval process and a code of conduct (standards, responsibilities, enforcement) help to create a welcoming project. But if you think we should prioritize the best practices guide, happy to come back to this later.

**Comment by cryptomental** [comment]
Hi, I think that adding CONTRIBUTING file would not do any harm. 
I also like an idea of adding GitHub templates, as an example see e.g. here https://github.com/gitcoinco/web/tree/master/.github

**Comment by ThatsNotVeryCashMoneyOfYou** [comment]
Hi, I was wondering if there was a slack channel or other form of communication besides github issues that y'all use to communicate/talk? I'm interested in this project and have never worked on anything open source before so I'm not sure where the appropriate place to ask questions is.

**Comment by dguido** [comment]
Yep, https://github.com/trailofbits/slither#getting-help
