### ISSUE TITLE
Invalid detection of race condition at contract's initialization

### ISSUE THREAD

**Issue by pdyraga** [crytic/slither#597]
Please consider the following code:

```
// OpenZeppelin code
contract ReentrancyGuard {
    uint256 private _guardCounter;

    constructor () internal {
        _guardCounter = 1;
    }

    modifier nonReentrant() {
        _guardCounter += 1;
        uint256 localCounter = _guardCounter;
        _;
        require(localCounter == _guardCounter, "ReentrancyGuard: reentrant call");
    }
}
```

```
contract MyContract is ReentrancyGuard {
    constructor(address _someRef) public {...}

    function myFunc() public payable nonReentrant {...}
}
```

Slither reports that:
> MyContract.myFunc() is vulnerable to race condition and initiates:
	- ReentrancyGuard._guardCounter (openzeppelin-solidity/contracts/utils/ReentrancyGuard.sol#17)

With the Recommendation of:
> Recommendation
>
> Call the initialization function in the contract's constructor.
>
> Upgradable contracts using the delegatecall proxy pattern need an initialization function. Ensure that your deployment script is robust to a race condition during the contract upgrade.

I think the detection is not correct as it's what's actually happening here. `_guardCounter` is initialized in the constructor of the parent class, and not in some `init()` function.

**Comment by montyly** [comment]
Hi @pdyraga ,

This was fixed with the latest release of crytic (https://twitter.com/CryticCI/status/1308102748043268096).
