### ISSUE TITLE
Ways to write a script with the current API that simply returns the vulnerabilities present in a smart contracts

### ISSUE THREAD

**Issue by Mikerah** [crytic/slither#609]
I am working on a project in which I have a few thousand smart contracts that I want to analyze more deeply. I would like to write a python script using Slither that would return a list of the vulnerabilities present in this smart contracts. For each of these smart contracts, I have both the bytecode and the original source code. Further, they all use different versions of Solidity depending on when they were first deployed to main net Ethereum.

I took a look through the current docs and wiki and saw that there are printers available but these all take in a .sol file directly or an AST for that file. Is there a way to simply pass in a string, and then get a list of the vulnerabilities present in the string version of the contract?

**Comment by yxliang01** [comment]
You might want to consider using `StringIO` to use the in-memory string as if they are files.

**Comment by montyly** [comment]
Hi @Mikerah, thank you for your interest in Slither.

If you are trying to analyze code that is on chain, the simplest way is to provide the address to Slither (assuming the source code is in etherscan). For example:
```
slither 0xdac17f958d2ee523a2206206994597c13d831ec7
```

If you have [`solc-select`](https://github.com/crytic/solc-select) installed, Slither will automatically switch to the correct solc version.

There is no current way to give a string to Slither - but as Slither relies on the external compilation, it will need to create a temporary file to pass it to `solc` anyway, which will be the same as doing to externally.

**Comment by Mikerah** [comment]
@montyly Thank you for your reply. It answers my questions.
