### ISSUE TITLE
BUG: slither (0.6.13) will produce an exception when printing the contract control flow graph

### ISSUE THREAD

**Issue by xf97** [crytic/slither#644]
The bug can be reproduced stably.
slither version: 0.6.13
System: ubuntu 18.04
Solidity version: 0.5.13, 0.6.0
python version: 3.6

**Comment by xf97** [comment]
bug type: OSError: [Errno 36] File name too long.
eg., 
contract SourceCode:
pragma solidity 0.6.0;

contract baseContract1{
	mapping(address=>uint256) public balance;

	
	function getMoney() external payable virtual{
	}
}

contract baseContract2{
	address owner;
	constructor() public{
		owner = msg.sender;
	}

	modifier onlyOwner(){
		require(msg.sender == owner);
		_;
	}
}

contract baseContract3 is baseContract1{
	function withdraw1() external{
		require(balance[msg.sender] > 0);
		msg.sender.transfer(balance[msg.sender]);
		balance[msg.sender] = 0;
	}

	function withdraw2() external{
		require(balance[msg.sender] > 0);
		msg.sender.send(balance[msg.sender]);
		balance[msg.sender] = 0;
	}

	function withdraw3() external{
		require(balance[msg.sender] > 0);
		msg.sender.call.value(balance[msg.sender])("");
		balance[msg.sender] = 0;
	}

	function noWithdraw() external{
		require(balance[msg.sender] > 0);
		msg.sender.call("");
		balance[msg.sender] = 0;
	}
}

contract myContract is  baseContract3{
	constructor() public payable{
		msg.sender.transfer(address(this).balance);
	}
	function withdraw1(uint256 _amount) external{
		require(balance[msg.sender] > _amount);
		//reentrancy
		msg.sender.call.value(_amount)("");
		balance[msg.sender] -= _amount;
	}

	function getMoney() override payable external{
		balance[msg.sender] += msg.value;
		balance[msg.sender] += 10;
	}

	fallback() external{
		balance[msg.sender] -= 10;
		revert();
	}
}

bug info:
OSError: [Errno 36] File name too long: 'baseContract1-getMoney().dot-baseContract2-constructor().dot-baseContract2-onlyOwner().dot-baseContract3-getMoney().dot-baseContract3-withdraw1().dot-baseContract3-withdraw2().dot-baseContract3-withdraw3().dot-baseContract3-noWithdraw().dot-myContract-withdraw1().dot'

**Comment by montyly** [comment]
Hi @xf97 

Thank you for reporting this issue. We fixed it in https://github.com/crytic/slither/pull/633, and we merged the fix in master. It will be available in the next Slither release.

**Comment by xf97** [comment]
Thank you. I look forward to the next release soon.
