### ISSUE TITLE
The printer function should be able to output the result as a file

### ISSUE THREAD

**Issue by xf97** [crytic/slither#663]
The printer function should be able to output the result as a file, not just output in the terminal, which can facilitate other programs to get the output of Slither.

**Comment by snd** [comment]
You could try running `slither --print {your-chosen-printer} --json {output-file}`.
It will print a JSON representation of the printer output to `{output-file}`.
The JSON schema could be improved but is already much easier to consume than the output to stdout/stderr.

**Comment by xf97** [comment]
thanks, I get it.
