### ISSUE TITLE
slither: command not found ➡️ python3 -m slither .

### ISSUE THREAD

**Issue by stefek99** [crytic/slither#717]
It works: `python3 -m slither .`

It does not:

```$ pip3 install slither-analyzer
Collecting slither-analyzer
  Downloading https://files.pythonhosted.org/packages/3c/3a/596930677963070c7dd4a441a66b3d3a31fae9186623c673648bcd6a0a85/slither-analyzer-0.6.14.tar.gz (262kB)
    100% |████████████████████████████████| 266kB 610kB/s 
Collecting crytic-compile>=0.1.10 (from slither-analyzer)
  Downloading https://files.pythonhosted.org/packages/a6/26/01b5fc67128a8f7112d1ed0b567b2b2e089893f1d00df8c9378b2ae3adf5/crytic_compile-0.1.10-py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 864kB/s 
Collecting prettytable>=0.7.2 (from slither-analyzer)
  Downloading https://files.pythonhosted.org/packages/94/d5/52e48f3bcf66f838d411ad85c3ac9550c2451d082623e2d4d4df7411ed5c/prettytable-2.0.0-py3-none-any.whl
Collecting pysha3>=1.0.2 (from slither-analyzer)
  Downloading https://files.pythonhosted.org/packages/32/2a/b93e0c6d90c7c45e2fab35d7ef349e8c5bd7387a048e961b041fd9521556/pysha3-1.0.2-cp36-cp36m-manylinux1_x86_64.whl (127kB)
    100% |████████████████████████████████| 133kB 884kB/s 
Collecting setuptools (from prettytable>=0.7.2->slither-analyzer)
  Downloading https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl (785kB)
    100% |████████████████████████████████| 788kB 864kB/s 
Collecting wcwidth (from prettytable>=0.7.2->slither-analyzer)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Building wheels for collected packages: slither-analyzer
  Running setup.py bdist_wheel for slither-analyzer ... done
  Stored in directory: /home/ms/.cache/pip/wheels/65/d2/1a/d14d685f7fbc28179eb1784c8e490e7cdc4141ee3d7947154a
Successfully built slither-analyzer
Installing collected packages: pysha3, crytic-compile, setuptools, wcwidth, prettytable, slither-analyzer
Successfully installed crytic-compile-0.1.10 prettytable-2.0.0 pysha3-1.0.2 setuptools-50.3.2 slither-analyzer-0.6.14 wcwidth-0.2.5



$ slither .
slither: command not found
```

### `solc` not required:

> Slither requires Python 3.6+ and solc, the Solidity compiler.

I didn't install `solc`. Slither did the job anyway. `npx truffle ...` that automagically got the `solc`

**Comment by StErMi** [comment]
I have the same problem, fresh new m1 mac

just installed slither and I get `zsh: command not found: slither`

**Comment by elopez** [comment]
Hi @StErMi, if you are using the system-provided Python, you need to add the location where pip installs the scripts to your shell PATH. pip will print a yellow warning letting you know, something like the following:


> ...
>  WARNING: The scripts ... are installed in '/Users/user/Library/Python/3.8/bin' which is not on PATH.
>  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

This is something related to your Python setup and will also impact you if you use other Python tools, not just Slither.

As a workaround until you fix that, you may launch slither with `python3 -m slither ...`

**Comment by StErMi** [comment]
> Hi @StErMi, if you are using the system-provided Python, you need to add the location where pip installs the scripts to your shell PATH. pip will print a yellow warning letting you know, something like the following:
> 
> > ...
> > WARNING: The scripts ... are installed in '/Users/user/Library/Python/3.8/bin' which is not on PATH.
> > Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> This is something related to your Python setup and will also impact you if you use other Python tools, not just Slither.
> 
> As a workaround until you fix that, you may launch slither with `python3 -m slither ...`

solved thanks!
