### ISSUE TITLE
Add support for multiple compilation units

### ISSUE THREAD

**Issue by montyly** [crytic/slither#731]
Currently, Slither can only analyze one compilation unit. This is annoying for codebases that go through multiple compilations (ex: different solidity versions), as they need separate slither's run

We can create a compilation unit object, that will hold all the top-level objects (pragma, import, contracts, ..) and remove this limitations.

This should also allow Slither to work on codebases with contracts name reused with some platforms (ex: it won't work for Truffle, but it could in brownie)

**Comment by wighawag** [comment]
Would be great to have that. 
I tested slither with hardhat and slither only pick one compilation unit.
If there was an option to choose which one to analyse would be good enough for me
for now I simply remove the buildInfo files except the one I want to get the analyze on
