### ISSUE TITLE
Subdemonination conversion impossible

### ISSUE THREAD

**Issue by aaronovz1** [crytic/slither#748]
It looks like `gwei` is not supported by slither but is a valid subdemonination of Solidity.

**Comment by montyly** [comment]
Hi @aaronovz1, thanks for reporting this. We will add the missing subdemonination

**Comment by montyly** [comment]
Hi @aaronovz1.

We added the support in `master`, it will be available in the upcoming [0.7.1](https://github.com/crytic/slither/issues/789) release
