### ISSUE TITLE
predictable printer numbering

### ISSUE THREAD

**Issue by snd** [crytic/slither#749]
I'll make a PR with the suggested solution below if I get positive feedback.

## problem

to get the list of all printers slither currently calls `dir(all_printers)`.
the output of `dir` is ordered alphabetically by the name of the printer class.
`--list-printers` then numbers that list.
adding a new printer results in those numbers changing almost entirely.

for this reason the output of `--list-printers` is out of sync with the wiki https://github.com/crytic/slither/wiki/Printer-documentation:
```
slither --list-printers
+-----+-------------------+--------------------------------------------------------------------------+
| Num |      Printer      |                               What it Does                               |
+-----+-------------------+--------------------------------------------------------------------------+
|  1  |     call-graph    |           Export the call-graph of the contracts to a dot file           |
|  2  |        cfg        |                     Export the CFG of each functions                     |
|  3  | constructor-calls |                     Print the constructors executed                      |
|  4  |  contract-summary |                     Print a summary of the contracts                     |
|  5  |  data-dependency  |               Print the data dependencies of the variables               |
|  6  |      echidna      |                    Export Echidna guiding information                    |
|  7  |        evm        |             Print the evm instructions of nodes in functions             |
|  8  |    function-id    |             Print the keccack256 signature of the functions              |
|  9  |  function-summary |                     Print a summary of the functions                     |
|  10 |   human-summary   |             Print a human-readable summary of the contracts              |
|  11 |    inheritance    |            Print the inheritance relations between contracts             |
|  12 | inheritance-graph |       Export the inheritance graph of each contract to a dot file        |
|  13 |     modifiers     |               Print the modifiers called by each function                |
|  14 |      require      |           Print the require and assert calls of each function            |
|  15 |      slithir      |            Print the slithIR representation of the functions             |
|  16 |    slithir-ssa    |            Print the slithIR representation of the functions             |
|  17 |   variable-order  |              Print the storage order of the state variables              |
|  18 |   vars-and-auth   | Print the state variables written and the authorization of the functions |
+-----+-------------------+--------------------------------------------------------------------------+
```

adding a new printer means having to update the whole ordering in the wiki instead of just appending the printer.

## suggested solution

- remove `slither/printers/all_printers.py`
- make `slither/printers/__init__.py` import and reexport all printers
- make `slither/printers/__init__.py` export `ALL_PRINTERS` which is a list of printers in desired order
- when adding a new printer simply import it in `slither/printers/__init__.py` and append it to `ALL_PRINTERS`

**Comment by montyly** [comment]
I think we should keep the alphabetic order, otherwise, it might become difficult to follow. Note that the wiki table is generated by `slither --markdown ""` (I updated the wiki).

What we could do is to:
- Add the printer documentation to the python class (similar to what we have for the detectors). This will ensure we keep an up to date documentation for each printer and will let us update the wiki page entirely in one step (it's how we do it for detectors).
- Consider adding classification to the printers (for example `Function Explorer`, `Summary`, `SlithIR`, ...), and adding these categories to printer table (with an order by classification, and then name)

**Comment by snd** [comment]
Adding the printer documentation to the python class is a great idea! It keeps implementation and documentation together and makes it more likely they'll be updated together. It also would enable querying printer documentation on the command line a la `slither --printer-doc function-id`.
