### ISSUE TITLE
Rename --filter-path to --exclude-files

### ISSUE THREAD

**Issue by montyly** [crytic/slither#761]
This will be more consistent with the other flags, like `--exclude-dependencies`.

We should also 
- Move the help to the detectors sections, so it's easier to find
- Create `--exclude-contracts`, that will do the same, but at the contract level

**Comment by hacker-DOM** [comment]
also add `--include-files` to easily include only certain files (otherwise it's cumbersome to exclude everything but something)

**Comment by montyly** [comment]
Discussion moved to https://github.com/crytic/slither/issues/759
