### ISSUE TITLE
AttributeError: 'StructureTopLevel' object has no attribute 'contract'

### ISSUE THREAD

**Issue by montyly** [crytic/slither#773]
On 0x0cf55d57d241161e0ec68e72cbb175dbfe84173a

Here there should be a different case for top-level elements and non-top-level:

https://github.com/crytic/slither/blob/c0c581b3ba830b6ce8dc3f4be82592a7a42e9752/slither/core/solidity_types/user_defined_type.py#L65-L66

**Comment by rayeaster** [comment]
@montyly so if we have some `struct` defined out of any `contract` or `interface` then slither would throw this `AttributeError`?

**Comment by Clearwood** [comment]
I am running into the same problem on this repo: https://github.com/sushiswap/bentobox

**Comment by montyly** [comment]
Hi @rayeaster and @Clearwood, we fixed the issue in #786. 

I tested the fix on bentobox and it works. The fix will be available in the upcoming release
