### ISSUE TITLE
[Tracking] Improve ternary support

### ISSUE THREAD

**Issue by montyly** [crytic/slither#775]
There are a couple of ternary conversions that we are missing
- https://github.com/crytic/slither/issues/634
- https://github.com/crytic/slither/issues/142
- ~Ternary in calls parameters `{value:...}`~
- ..

We need to add support for all the ternary, and add thorough tests on this part of the code

**Comment by eMarchenko** [comment]
I had an issue with 
```ts
(uint min, uint max) = a < b ? (a, b) : (b, a)
```

**Comment by elenadimitrova** [comment]
I have an issue with this as well in solc 0.8 reporting error
`Exception: Ternary operator are not convertible to SlithIR if _tokenA < _tokenB then (_tokenA,_tokenB) else (_tokenB,_tokenA)`

**Comment by pubokia** [comment]
+1

Code:
_char[0] = _strAddress[i < _padding + 2 ? i : 42 + i - _length];

Will trigger:
Exception: Ternary operator are not convertible to SlithIR if i < _padding + 2 then i else 42 + i - _length

**Comment by frontier159** [comment]
This is still an issue - anyone know the latest?

**Comment by 0xalpharush** [comment]
I'm going to close this as https://github.com/crytic/slither/issues/634 is the only issue I'm aware of atm and we can address other issues as they come

**Comment by duyhuynhdev** [comment]
I had an issue with
`Ternary operator are not convertible to SlithIR if maxTxLimit > 0 then false else true`
can we skip this ?

**Comment by 0xalpharush** [comment]
If you're using the most recent release of slither ( `slither --version` should show 0.10.0) and hitting this error, would you open a new issue and share the full stack trace as well as the code please (you can only share snippets of where ternaries are used if it can't be made public)? A link on github works great if it's too large to copy and paste.
