### ISSUE TITLE
ERROR:ContractSolcParsing:Missing inheritance

### ISSUE THREAD

**Issue by abialy** [crytic/slither#777]
Any idea where does it come from?  -> solc: version: "0.5.17"

ERROR:ContractSolcParsing:Missing inheritance <slither.solc_parsing.declarations.contract.ContractSolc object at 0x7f1c6b8c49b0>
ERROR:ContractSolcParsing:Missing params 'name()'
ERROR:ContractSolcParsing:Missing params 'name()'
ERROR:ContractSolcParsing:Missing params 'name()'
ERROR:ContractSolcParsing:Missing params 'transfer(address,uint256)'
ERROR:ContractSolcParsing:Missing params 'transfer(address,uint256)'
ERROR:ContractSolcParsing:Missing params 'transfer(address,uint256)'

**Comment by montyly** [comment]
Hi @abialy 

Usually, this means that your codebase has multiple contracts with the same name, which leads to a bug preventing most of the compilation framework (truffle, hardhat, ...) to produce the compilation artifacts.

`truffle` does now warm if this happens, see https://github.com/trufflesuite/truffle/issues/387

Can you run `truffle compile` on your project, and check the warnings?

**Comment by abialy** [comment]
You are right. Thanks a lot. I was wondering why.
