### ISSUE TITLE
Add tool to read on-chain storage

### ISSUE THREAD

**Issue by montyly** [crytic/slither#793]
We can rely on the internal storage information and [`web3.get_storage_at`](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_storage_at) to return the value of a contract onchain

Example of API

- `slither-read-storage [codebase] 0x414141 canonical_variable_name`
- `slither-read-storage 0x414141 canonical_variable_name` (if the source code is on etherscan)

Potential flags:
- RPC-related to connect to local node, infrura or other
- --list-all to dump all the contract variables and their values (aside mapping and maybe array?)
- `--offset` / `--index` for mapping array

**Comment by Elyx0** [comment]
Came from https://0xalpharush.github.io/slithering-through-the-dark-forest/ excited to see it!

**Comment by jeffchen006** [comment]
Redirect interested people to https://github.com/crytic/slither/tree/master/slither/tools/read_storage
