### ISSUE TITLE
Are these false positives? variable should be constant and contract does not implement functions

### ISSUE THREAD

**Issue by krasi-georgiev** [crytic/slither#794]
The first fail is for this one
https://github.com/tellor-io/migrator/blob/69a67a1fc94067134dda0d935e5942e1e300931e/contracts/Main.sol#L13

The CI fail
https://github.com/tellor-io/migrator/runs/1979284937?check_suite_focus=true#step:9:26
how can this variable be a constant if the value is taken from the constructor?

The second fail is even more mysterious.
https://github.com/tellor-io/migrator/runs/1979284937?check_suite_focus=true#step:9:17

Where do these functions need to be implemented?

**Comment by montyly** [comment]
Hi @krasi-georgiev. Thanks for reporting this. 

The first one is a false positive (we need to treat `immutable` as constant). 

The second one looks like a bug on our side, we will investigate why it happens. In the meantime, you can add
```
//slither-disable-next-line DETECTOR_NAME
```

Before the finding to disable the report(s)
