### ISSUE TITLE
Hardhat integration - missing files (?)

### ISSUE THREAD

**Issue by antonyip** [crytic/slither#803]
Hello there,

I'm trying to integrate slither into a hardhat project -> https://github.com/hyperledger-labs/blockchain-carbon-accounting/pull/94

Running "Slither ." runs npx hardhat compile and only scans 1 solitary file. (contracts/Governance/Governor.sol)

I would like for all the *.sol files to be scanned in the contract folder..

Any help would be appreciated.

**Comment by montyly** [comment]
Hi @antonyip,

Thank you for reporting this. We are aware of this current limitation with hardhat (https://github.com/crytic/crytic-compile/issues/164) and we are working to add the support for multiple compilation units to slither.

**Comment by montyly** [comment]
Note: this will be fixed with https://github.com/crytic/slither/pull/823
