### ISSUE TITLE
Upgrade from solidity 0.7 to 0.8 caues a lot of `unimplemented-functions` errors

### ISSUE THREAD

**Issue by krasi-georgiev** [crytic/slither#814]
Here is the PR that just upgrades the solidity version 
https://github.com/tellor-io/chorus/pull/16

In the CI checks at the bottom of the PR can see the actual errors.

https://github.com/tellor-io/chorus/pull/16/checks?check_run_id=2217960747

**Comment by montyly** [comment]
Hi @krasi-georgiev, thank you for reporting this.

I think I fixed it with #815, however, we do still have partial support for Solidity 0.8 at the moment, so more issues might be present.

We will release 0.7.1 today, and it will include the fix

**Comment by krasi-georgiev** [comment]
Thanks I will upgrade and will report back

**Comment by krasi-georgiev** [comment]
aah that is not merged yet. Any way to build a release from the PR so I can test it and report back any other issues?

**Comment by krasi-georgiev** [comment]
@montyly I see that you merged the PR, but for some reason I don't see any change in the CI

The CI installs slither from master so I expected that re-running it will show some different output.

https://github.com/tellor-io/chorus/pull/17/checks?check_run_id=2220599528

**Comment by krasi-georgiev** [comment]
Here is how the CI installs and runs it

https://github.com/krasi-georgiev/chorus/blob/git-workflow/.github/workflows/checks.yml#L50-L51

https://github.com/krasi-georgiev/chorus/blob/git-workflow/Makefile#L7-L9

**Comment by krasi-georgiev** [comment]
fixed now with the latest upgrade, thanks!
