### ISSUE TITLE
Add functionality for Binance Smart Chain smart contracts

### ISSUE THREAD

**Issue by walkman941walkman941walkman941** [crytic/slither#824]
Hello

Please can you add for slither functionality for Binance Smart Chain, such as 

Etherscan options:
  --etherscan-only-source-code
                        Only compile if the source code is available.
  --etherscan-only-bytecode
                        Only looks for bytecode.
  --etherscan-apikey ETHERSCAN_API_KEY
                        Etherscan API key.

But for Binance Smart Chain, where I enter my api key from BSC and can download and analyze smart contracts locally on my PC with slither

It is very critical functionality for my work - please can you add it ?

Thank you very much for your tool

**Comment by montyly** [comment]
Hi @walkman941walkman941walkman941, as mentioned, we are working on the support. You can follow the progress here: https://github.com/crytic/crytic-compile/issues/168

**Comment by 0xalpharush** [comment]
This is included in the latest release 0.8.2. You can install it `pip install slither-analyzer --upgrade`
