### ISSUE TITLE
slither idling for an undetermined time. 

### ISSUE THREAD

**Issue by ccolorado** [crytic/slither#843]
Hi, I have been experiencing slither just hanging for close to an hour ( haven't waited for longer) 
I get no output to figure out what is going on other than the following truffle message.  
I haven't figured out a way to further troubleshoot this. 

```
$ slither . 
'npx truffle@5.1.49 compile --all' running (use --truffle-version truffle@x.x.x to use specific version)
```

Versions:
```
$ slither  --version
0.7.0

$ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.4+commit.c7e474f2.Linux.g++

$ python --version
Python 3.9.4
```

**Comment by rupansh** [comment]
Facing same issue

**Comment by zachwax101** [comment]
Facing same issue

**Comment by 0xalpharush** [comment]
It may be related to one of these two issues, so I'd start there. If the issue persists, it'd be helpful to share the codebase so we can debug and fix.

**Comment by zachwax101** [comment]
@0xalpharush 

https://github.com/zachwax101/something

**Comment by 0xalpharush** [comment]
What version of slither are you using? This works on 0.8.3. Note, truffle needs to be installed for before running slither.
