### ISSUE TITLE
Hidden results with triage mode doesn't work as expected.

### ISSUE THREAD

**Issue by mauricio1802** [crytic/slither#885]
I wanted to hide some specific results, but I didn't want to add project unrelated commets to the code, so I tried `--triage-mode` option. It hides the result when I run `slither .`, but if I use `--print human-summary` or `--json file.json` options those results are still counted. Is that ok? I would expect that any analysis run ignored the results in `slither.db.json`.

If I use the `//slither-disable-next-line DETECTOR_NAME` way it works as expected.

**Comment by montyly** [comment]
Hi @mauricio1802 

Thank you for reporting this. Indeed currently the triage only works when the detectors are run directly, and not through the printers.

We will improve this

**Comment by 0xalpharush** [comment]
closed by [fix triage prompt not displaying #1435](https://github.com/crytic/slither/pull/1435)
