### ISSUE TITLE
false positive for reentrancy in a constructor

### ISSUE THREAD

**Issue by thedavidmeister** [crytic/slither#887]
is it possible to call a constructor reentrantly?

if not we should not include reentrant behaviour in a constructor in the slither output

**Comment by montyly** [comment]
Hi @thedavidmeister.

This is an interesting question. I think you're right, as the code is not yet deployed you cannot re-enter the contract.

The worst case I can think of is if the constructor has some logic on `this.balance` (or similar), but this would not be currently detected by slither, and is probably more a corner case than an issue that can really happen. 

I have to think about this one for a bit, but most likely we can remove reentrancies in the constructor.

**Comment by thedavidmeister** [comment]
@montyly i made a repo to show that contracts cannot call functions on another contract during its construction

https://github.com/thedavidmeister/sol-reentrant-constructor

the address is visible as `msg.sender` of the contruct under construction, but function calls fail with `Error: Transaction reverted: function call to a non-contract account`

**Comment by duckki** [comment]
Constructor shouldn't re-enter in any case, otherwise it would amount to double initialization. I believe this is a false positive.
