### ISSUE TITLE
wiki vocabulary errors

### ISSUE THREAD

**Issue by yinhetest** [crytic/slither#892]
There are two vocabulary and grammatical errors in the wiki.
In the description of [here](https://github.com/crytic/slither/wiki/Detector-Documentation#weak-prng),'modulo' should be'module'.
In the title of [here](https://github.com/crytic/slither/wiki/Detector-Documentation#assert-state-shange),'shange' should be'change'.
Ask another question, in which branch can I submit new Detectors to make my contribution.

**Comment by montyly** [comment]
Hi @yinhetest. Good catch thanks. I fixed one typo in #916 (the other one is correct, "modulo" refers here to the modulo operation)

Regarding adding new detectors, you can work from `dev` (see our [CONTRIBUTING.md]()https://github.com/crytic/slither/blob/master/CONTRIBUTING.md)
