### ISSUE TITLE
Add hardhat crytic-compile options to Configuration File section of Wiki

### ISSUE THREAD

**Issue by ericrallen** [crytic/slither#894]
The [configuration file documentation](https://github.com/crytic/slither/wiki/Usage#configuration-file) does not include the compiler options for hardhat, so it's unclear how to use `slither .` with hardhat when using a subdirectory for build output.

I found the relevant options by finding an Issue that pointed me to the [relevant options in crytic-compile](https://github.com/crytic/crytic-compile/blob/d99e5a7dc8b80b812ef953a766457dd9eb4cbde1/crytic_compile/cryticparser/defaults.py#L44).

```
  "hardhat_cache_directory": "cache",
  "hardhat_artifacts_directory": "artifacts"
 ```

There are possibly other options that should be documented as well.

**Comment by montyly** [comment]
Hi @ericrallen .

Thank you for reporting this; indeed the wiki was missing a lot of flags. I added a link to the crytic-compile file in the wiki
