### ISSUE TITLE
Hardhat disallows global installation `npx hardhat compiile --force`

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#901]
It seems that Hardhat now disallows compilation from a global installation (https://hardhat.org/errors/#HH12).

This is what I'm getting when running `npx hardhat compile --force` on a local Hardhat project:

```
Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.
```

It seems that `slither` is using this as a default setting. Any ideas for a workaround other `--hardhat-ignore-compile`?

**Comment by ggrieco-tob** [comment]
I'm always using a local installation to run slither, usually like this:

```
$ npm i
$ PATH=$PATH:./node_modules/.bin slither .
```

**Comment by Pet3ris** [comment]
Does this mean `slither` is globally installed or in your active python environment? I was running this from a mono repo with a `protocol` folder (hardhat) and a python folder for the `slither-analyzer` dependency managed by `poetry`.

**Comment by Pet3ris** [comment]
I just tried installing it in the local virtual environment and running like so:

```
slither .
```

However, I'm still getting the following output:

```sh
'npx hardhat compile --force' running
```

**Comment by montyly** [comment]
Hi @Pet3ris, you are right, and it seems that hardhat does not work anymore with global installation, so npx is not useful anymore, thanks for pointing this out. 

I am moving the discussion to https://github.com/crytic/crytic-compile/issues/208. A quick workaround is to use `--npx-disable`
