### ISSUE TITLE
Etherscan command not switching Solidity versions

### ISSUE THREAD

**Issue by thetrebelcc** [crytic/slither#904]
Hi all I am attempting to use the etherscan command as such 

`slither 0xdac17f958d2ee523a2206206994597c13d831ec7
`
However, this leads to errors and slither states the correct version of solidity is not installed. I am able to scan contracts as` .sol `file with no issues and can switch Solidity versions with` solc-select` but when I attempt to do this with etherscan no matter what version of Solidity I have globally it says Solidity version not found.

**Comment by montyly** [comment]
Hi @thetrebelcc. This works for me. Can you run
```
$ slither --version
$ crytic-compile --version
$ solc-select install
```

?
