### ISSUE TITLE
Custom errors in solidity v0.8.4 cause slither exceptions

### ISSUE THREAD

**Issue by AlbertSu123** [crytic/slither#919]
When using [custom errors in solidity](https://blog.soliditylang.org/2021/04/21/custom-errors/), slither doesn't know how to handle this and throws this error:
`slither.exceptions.SlitherException: Top level ErrorDefinition not supported`

## Context

Custom errors were recently introduced to solidity v0.8.4 as a way to cheaply throw errors with a custom message. However, slither doesn't support custom errors, leading to an issue when running `slither .` on this hardhat project that uses custom errors

## Process

1. User creates a hardhat project with a solidity contract that uses [custom errors](https://blog.soliditylang.org/2021/04/21/custom-errors/)
2. User installs slither. I used `pip3 install slither-analyzer` inside a virtualenv created via [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)
3. User runs slither on the hardhat project with custom errors. I cd'ed into the project and ran `slither .`

## Expected result

Slither should run properly with correct outputs and analysis.

## Current result

`    
raise SlitherException(f"Top level {top_level_data[self.get_key()]} not supported")
slither.exceptions.SlitherException: Top level ErrorDefinition not supported
Error:
Top level ErrorDefinition not supported
Please report an issue to https://github.com/crytic/slither/issues
`

## Possible Fix

It seems like support for these custom errors are not added, so they would need to be added in!

**Comment by MerlinEgalite** [comment]
I have the same issue with solidity v0.8.7.
Did you figure it out a fix?
Thank you in advance for your answer!

**Comment by MerlinEgalite** [comment]
Hi! 👋  any update on this issue?

**Comment by montyly** [comment]
Hi @AlbertSu123 / @MerlinEgalite. Thanks for reporting this. We will add their support for the next release (end of September/October)

**Comment by julianmrodri** [comment]
Thanks also really needing this feature and buidling everything in 0.8.4 with custom errors. this would make it fully compatible with `0.8.4`?

**Comment by montyly** [comment]
@julianmrodri there are a couple of other features that we still need to add support for (e.g. https://github.com/crytic/slither/issues/927), but we are aiming to add all the missing features for the next release

**Comment by parseb** [comment]
> Hi @AlbertSu123 / @MerlinEgalite. Thanks for reporting this. We will add their support for the next release (end of September/October)

**Wen** full 0.8.4 custom error support **ser?**

**Comment by artdgn** [comment]
+1

**Comment by leomassazza** [comment]
+1

**Comment by montyly** [comment]
Hi, we added the support for custom error in (https://github.com/crytic/slither/pull/947), it will be available with the upcoming release (https://github.com/crytic/slither/issues/979)

**Comment by dsmitchell** [comment]
Thanks @montyly any eta on the release?

**Comment by RusseII** [comment]
> Thanks @montyly any eta on the release? EDIT: Seems like the Docker image for Slither is still on 0.8.1?

https://github.com/trailofbits/eth-security-toolbox/issues/27 @dsmitchell
