### ISSUE TITLE
Immutables are not completely understood/supported

### ISSUE THREAD

**Issue by axic** [crytic/slither#927]
Slither reports the following:
```
MyContract.myImmutable (contracts/MyContract.sol#10) should be constant
```

However it is a constant:
```
    uint256 public immutable myImmutable;
```

Immutables are set-once (in the constructor) variables, so in practice act as constants.

**Comment by axic** [comment]
@montyly was this fixed by #946?

**Comment by montyly** [comment]
Hi @axic. I just merged the fix in master, it will be available in the next release

**Comment by axic** [comment]
Thanks!
