### ISSUE TITLE
slither-check-upgradeability: allow to filter checks

### ISSUE THREAD

**Issue by montyly** [crytic/slither#936]
Add flags to `slither-check-upgradeability` to disable some detectors per name, or per detectors impact, or to enable only some of the detectors (per name/impact)

**Comment by PostMan56** [comment]
Could this be similarly done like how the flags --detect and --exclude are in slither/__main__.py?

**Comment by webthethird** [comment]
I'll likely take this one on, since I'll probably need it for my project

**Comment by webthethird** [comment]
This is done! See #1532 @montyly
