### ISSUE TITLE
Detecting reentrancy in loops

### ISSUE THREAD

**Issue by htadashi** [crytic/slither#940]
First of all, I'd like to thanks Slither maintainers, as this tool is certainly one of the most important ones for Ethereum developers :)

I am writing this issue to ask if it is possible to detect reentrancies that are "hidden" in a loop. For example, [this bug on Hashmasks contract](https://thehashmasks.medium.com/hashmask-art-sale-bug-report-13ccd66b55d7) was not detected by Slither (the [code](https://etherscan.io/address/0xc2c747e0f7004f9e8817db2ca4997657a7746928#code) was modified for clarity):

```solidity
function mintNFT(uint256 numberOfNfts) public payable {
    require(totalSupply() < MAX_NFT_SUPPLY, "Sale has already ended");
    \\ ...
    
    for (uint i = 0; i < numberOfNfts; i++) {
        uint mintIndex = totalSupply();
         \\...
        _safeMint(msg.sender, mintIndex);
    }
   \\..
}
``` 

At first, the "check-effects-interactions" pattern seems to be respected. However, it is possible to re-enter the function `mintNFT` and bypass the `MAX_NFT_SUPPLY` requirement when the loop continues being executed after reentrancy (a detailed write-up can be found [here](https://thehashmasks.medium.com/hashmask-art-sale-bug-report-13ccd66b55d7)).

**Comment by arpu** [comment]
how can i avoid this problem? any suggestions?

**Comment by htadashi** [comment]
@arpu Is there a way to create a detector to check if a state variable is appearing in the `require` and also being modified in the for-loop by another contract? Not sure if this would generate too many false positives, though.

By the way, I am just a user of Slither and I am not experienced in building detectors, so feel free to discard my issue if you think it is too far-fetched :)
