### ISSUE TITLE
slither error while compiling multiple files.

### ISSUE THREAD

**Issue by blockchain5992** [crytic/slither#942]
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: project:/node_modules/@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol .I am getting this error when i directly import contracts from openzepplin without giving absolute path.But when I give exact path to that imported openzepplin contract it is working and giving me required slither report.

**Comment by johnzhu0907** [comment]
Have you solved this issue? Please show your way. I have encountered this problem too. Running `npm install openzeppelin` does not work.

**Comment by blockchain5992** [comment]
Yes it is solved I have used solc remaps.
slither . --solc-remaps @openzeppelin/contracts= (your absolute path from system) --print human-summary

**Comment by vaioco** [comment]
just in case to use it via APIs

```
slither = Slither(sys.argv[1], solc_remaps="openzeppelin-solidity/=PATH")
```
