### ISSUE TITLE
Slither error in compiling - CryticCompiler

### ISSUE THREAD

**Issue by mstad** [crytic/slither#943]
$ Slither --version 0.6.12

$ crytic-compile --version 0.2.0

When I try to compile contracts *.sol, I receive the following.
```
ERROR:root:Error in arbitrary_location_write_simple.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 606, in main_impl
    printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 68, in process_all
    compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 55, in process_single
    **vars(args))
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/slither.py", line 65, in __init__
    for path, ast in crytic_compile.asts.items():
AttributeError: 'CryticCompile' object has no attribute 'asts'

```

Something happened (I do not know what)... previoulsy I was able to compile contracts.

**Comment by remedcu** [comment]
I have the same trouble.

My slither version is `0.7.1` and crytic-compile is at `0.2.0`

Any help is appreciated.

**Comment by remedcu** [comment]
> $ Slither --version 0.6.12
> 
> $ crytic-compile --version 0.2.0
> 
> When I try to compile contracts *.sol, I receive the following.
> 
> ```
> ERROR:root:Error in arbitrary_location_write_simple.sol
> ERROR:root:Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 606, in main_impl
>     printer_classes)
>   File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 68, in process_all
>     compilation, args, detector_classes, printer_classes)
>   File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/__main__.py", line 55, in process_single
>     **vars(args))
>   File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.12-py3.6.egg/slither/slither.py", line 65, in __init__
>     for path, ast in crytic_compile.asts.items():
> AttributeError: 'CryticCompile' object has no attribute 'asts'
> ```
> 
> Something happened (I do not know what)... previoulsy I was able to compile contracts.

I updated the slither and crytic-compile to the latest, removed the build/abi folders, and then trying `slither .` worked.
