### ISSUE TITLE
github code scanning app integration

### ISSUE THREAD

**Issue by artdgn** [crytic/slither#948]
It was mentioned in [latest 0.8.1 release](https://github.com/crytic/slither/releases/tag/0.8.1) that integration is supported, but the `action` will be released soon. 

1. What's the best way to get an update on when it will be available? 

2. Alternatively, is there some guide or docs that would help setting it up in the meanwhile?

**Comment by htadashi** [comment]
@artdgn I am not a maintainer of Slither, but I had the same question. I made [this action](https://github.com/indexpool/indexpool-contracts/blob/main/.github/workflows/codeql-analysis.yml) to integrate Slither's SARIF output with Github code scanner. It was based on the code of [this repository](https://github.com/contractshark/pipeline-slither) (its owner also did [one for Echidna](https://github.com/contractshark/echidna), in case interests you).

**Comment by htadashi** [comment]
Hey @artdgn, @montyly released an official [Github action](https://github.com/marketplace/actions/slither-action) today :)
