### ISSUE TITLE
How to detect smart contract with many other files imported

### ISSUE THREAD

**Issue by sleepriverfish** [crytic/slither#950]
I get some error message 'File not found ' when i try to detect smart contract with many other files imported ，is there any other way?

**Comment by montyly** [comment]
Hi @sleepriverfish. Did you install the dependencies? Can you share the repo where this happens?

**Comment by sleepriverfish** [comment]
i try to run 'slither UniswapV2Pair.sol --solc /home/xxxx/solc/solc0.5.16' to detect UniswapV2Pair smart contract, but get error message 'File not found',  the impored files are in another folder. Please refer below screen shot for detail. 
![image](https://user-images.githubusercontent.com/6247627/135111285-1d826655-fd3a-4bbb-b2ad-9f353a949c72.png)
![image](https://user-images.githubusercontent.com/6247627/135111326-340aa49d-675a-4184-b0ec-388c142548f3.png)

**Comment by sleepriverfish** [comment]
Hi @montyly  I run slither against https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol  one receives this error 'File not found'.

**Comment by 0xalpharush** [comment]
You need to have the files available locally. If you're using hardhat you can try, `npm i @uniswap/v2-core`
