### ISSUE TITLE
Add 0.8.8 support

### ISSUE THREAD

**Issue by montyly** [crytic/slither#951]
https://blog.soliditylang.org/2021/09/27/solidity-0.8.8-release-announcement/

Most relevant:
- https://blog.soliditylang.org/2021/09/27/user-defined-value-types/
- min and max for Enums

**Comment by fiddlemath** [comment]
Just a +1 here; Getting support for user-defined value types into Slither would save me and my team considerable grief.

**Comment by 0xalpharush** [comment]
Need to support
```
contract test {
        enum MinMax { A, B, C, D }

        function min() public returns(uint) { return uint(type(MinMax).min); }
        function max() public returns(uint) { return uint(type(MinMax).max); }
}
```
